- src/modules/backend/components/title.jsx
- src/modules/content/components/search.jsx
- src/modules/content/styles/search.scss
- src/modules/dashboard/components/dashboard.jsx
- src/modules/dashboard/components/messages.jsx
- src/modules/timetable/components/table.jsx
- src/modules/timetable/components/timetable.jsx
including:
Dropdown bei Materialien
Timeline nur beim aktuellen Tag
Krims Krams
Mock 2te Suchergebnis: Integral
> overall changes

- package.json
- src/modules/administration/components/administration.jsx
The components aren't loaded until their tab is selected, which is nice. The buttons are still a bit difficult to see, maybe you can have a look at the CSS @nicoknoll ?
> Add react-tabs with bootstrap classes

- controllers/homework.js
- static/styles/homework/assignment.scss
- static/styles/homework/homework.scss
- static/styles/homework/submissions.scss
- views/homework/overview.hbs
- views/homework/submissions.hbs
Rote Hervorhebung falls 0/X bewertet.
Grüne Markierung, falls 100% abgegeben haben, orange ab 80%.
Anzeige der jeweiligen Statistiken nur wenn dies Sinnvoll --> Keine Durchschnittsnote solange keine Bewertung usw.
> 383 statistik in liste wieviel abgegeben

- controllers/homework.js
- static/styles/homework/assignment.scss
- static/styles/homework/homework.scss
- static/styles/homework/submissions.scss
- views/homework/assignment.hbs
- views/homework/overview.hbs
Farbliche Hervorhebung der Counter in Rot, Orange, Gelb
Abstufungen in der Anzeige: 
> 5 Tage - Datum
< 5 Tage - Tagescountdown
< 1 Tag - Stundengenau
< 3 Stunden - Minutengenau
> 384 wenn abgabedeadline naht counter anzeigen

- controllers/homework.js
bugfix of implementation: moved ifs inside if --> is working now
> 381 homework deadlines optional

- views/administration/forms/form-classes.hbs
- views/administration/forms/form-courses.hbs
Die Felder sollten nicht required sein, weil sonst keine Fehlermeldung geworfen wird, wenn man in diesen nichts angegeben hat. Es reicht ja, wenn erstmal ein leeres Array in die DB geschrieben wird, solange der Kurs richtig angelegt wird.
> remove required values

- controllers/homework.js
- static/scripts/homework.js
- static/styles/homework/assignment.scss
- views/homework/assignment.hbs
- views/homework/form-assignment.hbs
Pull #167 required to work properly
> 439 FIX: edit modal in detail view

- README.md
This is where I would expect testing.
> moved "How to name your branch" section

- controllers/account.js
Approve when [PR161](https://github.com/schul-cloud/schulcloud-server/pull/161) is pushed.
> change get to find for devices

- static/styles/lib/loggedin.scss
> style fixes for branding

- views/lib/loggedin.hbs
> show currently no notifications

- controllers/homework.js
- views/lib/loggedin.hbs
added notifications for created homework and graded submissions
> 564 benachrichtigung für erstellung abgabe oder bewertung einer aufgabe

- static/scripts/homework.js
- static/styles/homework/submissions.scss
- views/homework/evaluation.hbs
Bewertungen können jetzt ohne Pagereload gespeichert werden.
Ebenso können Kommentare erstellt und bestehende Kommentare gelöscht werden. 
Neu erstellte Kommentare können jedoch nicht direkt async gelöscht werden, da die ID dieser noch unbekannt ist. Ebenso kann der aktuelle Name nicht angezeigt werden. Dazu müsste man eventuell den Controller ändern, sodass die Asynchrone Anfrage diese Daten zurück bekommt und im UI nutzen kann.
> 606 abgaben tab reloads durch buttons vermeiden

- static/scripts/homework.js
- static/styles/homework/discussions.scss
- views/homework/discussion.hbs
Changes:
- AJAX is working in student & teacher view of discussions
- error handling
- submitbutton is always shown while loading (for example the delete
comment button)
- renamed variables to CamelCase
> discussions wasn't async anymore after last merge

- static/scripts/homework.js
- views/homework/overview.hbs
move datepicker back do overview.hbs, as it destroys the async tabs
> quickfix for async tabs

- controllers/homework.js
- static/scripts/homework.js
- views/homework/assignment.hbs
- views/homework/overview.hbs
> datepicker in detailview added

- helpers/handlebars/helpers/index.js
- static/styles/lib/base.scss
- views/courses/course.hbs
- views/topic/topic.hbs
> 685 aufgaben übersicht auf kurs und themenseite soll auf und zu klappbar sein

- controllers/login.js
code is not necessary anymore and destroys the login for unknown accounts.
> remove unnecessary code

- controllers/administration.js
- controllers/files.js
- helpers/handlebars/helpers/index.js
- views/administration/school.hbs
depends on https://github.com/schul-cloud/schulcloud-server/pull/224
> 462 show school storage usage for school admin

- controllers/homework.js
- views/homework/components/overview_card_template.hbs
- views/homework/submissions.hbs
Zugehöriger Server-Pull: https://github.com/schul-cloud/schulcloud-server/pull/230
> 583-move-homework-statistics-from-client-to-server

- views/authentication/forms/demo-login.hbs
> 753 - Browser-Empfehlungstext hinzugefügt

- static/styles/homework/homework.scss
- static/styles/homework/overview.scss
- views/homework/components/overview_card_template.hbs
Neue Farben in Lehreransicht (dezenter)
Schüler sieht seine Bewertung nun direkt als Grafik + Beschreibung
Details what was done in push 47c2453 details
> 751-meinel-in-schüleransicht-wenn-feedback-gegeben-wurde

- static/styles/content/content.scss
- views/content/item.hbs
> 448 content to kurs for demoteacher

- controllers/administration.js
> teacher are not allowed deleting users, just editing students

- controllers/administration.js
- static/scripts/administration.js
- static/scripts/tables.js
- views/administration/administration.hbs
- views/administration/classes.hbs
- views/administration/courses.hbs
- views/administration/forms/form-delete-alias.hbs
- views/administration/forms/form-delete-name.hbs
- views/administration/forms/form-delete-user.hbs
- views/administration/students.hbs
- views/administration/systems.hbs
- views/administration/teachers.hbs
everything is sortable but classes for students/teachers as those are not anyhow related to the object
> add sorting for tables and classes for students

- static/styles/content/content.scss
> Content fix tags text overflow

- Dockerfile
- docker-compose.yml
- package.json
- static/styles/content/content.scss
> Add gulp support for docker

- controllers/content.js
- views/content/search-results.hbs
> Added pagination to the content page, if queries respond to much results

- package.json
> nodemon: also watch js files

- views/registration/account.hbs
- views/registration/full.hbs
- views/registration/registration.hbs
now also exists for account/full, meaning either invited through a person or the general invitation link
> add password check for account creation

- static/styles/lib/sc-theme/sc-card.scss
- views/lib/components/sc-card.hbs
added invisible link to title of sc-card
> 844-dateien-öffnen-wenn-auf-ordner-geklickt-wird

- controllers/topics.js
- package.json
- static/scripts/topicEdit.js
- views/topic/components/content-neXboard.hbs
Reverts schul-cloud/schulcloud-client#495
> Revert "693 nexboard via api implementieren"

- static/scripts/homework.js
> more popups to make it clear that content was saved

- controllers/courses.js
- controllers/homework.js
- controllers/news.js
- controllers/topics.js
- static/scripts/administration.js
- static/scripts/calendar.js
- static/scripts/classes.js
- static/scripts/content.js
- static/scripts/courses.js
- static/scripts/dashboard.js
- static/scripts/files.js
- static/scripts/loggedin.js
- static/scripts/login.js
- static/scripts/tools.js
- static/scripts/topic.js
- views/courses/edit-course.hbs
- views/homework/edit.hbs
- views/lib/components/modal-cancel.hbs
- views/news/edit.hbs
- views/topic/edit-topic.hbs
https://github.com/schul-cloud/schulcloud-client/issues/199
> #199 cancel buttons consist naming

- views/imprint/imprint.hbs
> Added Tel and Fax Numbers

- views/authentication/home.hbs
- views/partner/partner.hbs
> new homepage text

- controllers/homework.js
If a student submitted a submission and was deleted later on the homework itself crashed
> stop crashing when student was deleted

- controllers/homework.js
fixes double slash https://schul-cloud.org/homework//?p=1
> Fix pager link in homeworks

- test/account/account.test.js
- views/account/settings.hbs
requested by couple of teachers.
> remove name change for students

- static/styles/lib/loggedin.scss
- theme/n21/views/lib/footer.hbs
- views/lib/footer.hbs
> removed nobr tag and fixed min-height

- static/scripts/spectrum/init.js
- static/scripts/spectrum/spectrum.js
- static/styles/lib/spectrum/spectrum.css
- views/administration/courses.hbs
- views/administration/forms/form-courses.hbs
> color Picker fallback

- static/styles/lib/loggedin.scss
- theme/n21/style.scss
- views/lib/loggedin.hbs
> fixed sidebar logo

- static/scripts/loggedin.js
- static/styles/lib/loggedin.scss
- views/lib/loggedin.hbs
Nativer Vollbildmodus wird nicht genutzt, da a) die [API aktuell noch in der Entwicklung ist](https://caniuse.com/#feat=fullscreen)
und b) dem User so die Möglichkeit gegeben wird selbst zu entscheiden, wie weit er in den Vollbildmodus wechseln möchte. Manuelles triggern des Browser-Vollbildmodus ist ja weiterhin möglich.
> 909-vollbildmodus-content-only

- gulpfile.js
- package.json
If you change something in a sass file that is included anywhere else, gulp will update the file that includes too.
> add sass grapher

- views/authentication/home.hbs
> added explainer video

- controllers/content.js
- static/scripts/dashboard.js
- static/scripts/help.js
- static/scripts/loggedin.js
- views/lib/default.hbs
fixes SC-52
following pages are using the inline function
- file-viewer
- content-search
> just use inline-query param for inlining

- views/homework/assignment.hbs
used parameters in wrong order :disappointed:
> SC-79 ~ Abgabe als Schüler nicht mehr möglich

- static/scripts/base.js
- static/scripts/loggedin.js
- views/lib/loggedin.hbs
add print class & button
display qr-code as image instead of canvas (canvas isn't printable)
> SC-49 ~ make qr printable

- views/registration/account.hbs
- views/registration/full.hbs
- views/registration/registration.hbs
- views/registration/user.hbs
> remove password hint for sso

- controllers/homework.js
- static/scripts/homework.js
- views/homework/components/submission_uploaded_files.hbs
- views/homework/submission.hbs
> fix file upload in submissions

- static/styles/lib/loggedin.scss
Fix for https://github.com/schul-cloud/schulcloud-client/issues/589
and [SC-88](https://ticketsystem.schul-cloud.org/browse/SC-88)
> minor css fix to display fullscreen mode correctly

- controllers/helpdesk.js
changed the school id line. guess it works better now
> school id works now

- views/authentication/home.hbs
Text im Willkommenstext geändert.
> Update home.hbs -Text im Willkommenstext geändert.

- views/courses/edit-course.hbs
Someone removed these changes in an commit. I restored them so the color picker is working again :)
> SC-97 restore edit-course.hbs changes

- controllers/administration.js
- controllers/homework.js
- static/scripts/administration.js
- static/scripts/homework.js
> Sc 101 fix pagination

- theme/n21/views/authentication/home.hbs
> re-add login form

- views/homework/submission.hbs
> fix multi select

- static/scripts/homework.js
- views/homework/assignment.hbs
Fehler war ein verschachtelter eventListener für das gleiche event (siehe letzter commit)
Die Zeilen zum Bewerten von Abgaben sollten nun wieder ausklappbar sein.
> SC-110 ~ abgaben können nicht angezeigt werden

- static/scripts/base.js
- static/styles/lib/loggedin.scss
See: https://github.com/schul-cloud/schulcloud-client/pull/593#issuecomment-374728400
> fix mobile menu and search button not applied

- controllers/homework.js
> fix bug that prevents loading a private task

- views/team/team.hbs
just a quick fix for the team member card mouseover animation - and github skill training ;)
> fix team mouseover reflection

- static/styles/authentication/home.scss
- views/lib/header.hbs
> fix homepage navigation styles on md down devices

- static/styles/team/team.scss
- views/team/team.hbs
> fix styles of team page

- static/styles/team/team.scss
- views/team/team.hbs
its possible to add subheader by adding
"subheader_before": "MINT-EC"
to someones card
> added subheader possibility for team page

- views/authentication/forms/login.hbs
> fix wording

- controllers/administration.js
- controllers/homework.js
- static/styles/lib/base.scss
- views/files/files-grid.hbs
- views/files/files.hbs
- views/homework/components/overview_card_template.hbs
- views/lib/components/table.hbs
/administration/students/
/administration/teachers/
/administration/courses/
/administration/classes/
/administration/helpdesk/
/files/
/homework/
> SC-209 - hover texte ergänzen

- static/scripts/base.js
The problem was `return customReady.apply(this, arguments);` which also applies the default behavior.
> SC-216 - button triggern doppelt

- views/imprint/imprint.hbs
newer text from Karo received today.
> update data security 28.05.

- README.md
nothing to do here. Simply set the enviroment variable where you run the client.
https://stackoverflow.com/questions/8083410/how-can-i-set-the-default-timezone-in-node-js
> add readme how to set timezone

- controllers/account.js
- helpers/handlebars/helpers/index.js
- static/scripts/dashboard.js
- views/dashboard/dashboard.hbs
- views/help/help.hbs
- views/lib/forms/form-poll.hbs
- views/lib/loggedin.hbs
finally make use of preferences.
Introduce the frontend route `/account/preferences`
Post Data as followed : `{ attribute: { key: "key", value: value } }` and it will be written into the preferences.
Preferences are automatically loaded in a hidden object in the loggedin.hbs meaning the preferences are everywhere available for scripts via jquery.
> second poll and preferences

- controllers/administration.js
add technical_problem to enable submits&display of "Technische Probleme"
> SC-207-fix-technical-problem-submit

- views/authentication/forms/demo-login.hbs
ticket: https://ticketsystem.schul-cloud.org/browse/SC-377
Soll:
als Schüler*In einloggen
als Lehrer*In einloggen
> SC-377-Demo-Login-Umbenennung

- static/styles/lib/loggedin.scss
ticket: https://ticketsystem.schul-cloud.org/browse/SC-367
> SC-367-make nav-sidebar always scrollable (bug)

- test/nightwatch/homework/homework_create.js
- test/nightwatch/login/login_demo_lehrer.js
- test/nightwatch/login/login_demo_schueler.js
- test/nightwatch/login/login_schueler.js
- views/lib/loggedin.hbs
Hab die fixes versehentlich im falschen branch gemacht :/
> nightwatch fixes

- controllers/content.js
- helpers/handlebars/middleware.js
- test/nightwatch/login/login_demo_lehrer.js
- test/nightwatch/login/login_demo_schueler.js
- test/nightwatch/login/login_schueler.js
ticket: https://ticketsystem.schul-cloud.org/browse/SC-380
> SC-380-rename 'Materialien' to 'LernStore'

- controllers/homework.js
- controllers/news.js
- helpers/handlebars/middleware.js
- test/mocha/homework/homework.test.js
- test/nightwatch/login/login_demo_lehrer.js
- test/nightwatch/login/login_demo_schueler.js
- test/nightwatch/login/login_schueler.js
- views/dashboard/dashboard.hbs
- views/topic/topic.hbs
ticket: https://ticketsystem.schul-cloud.org/browse/SC-417
wurde schon von Konstantin reviewed
> SC-417-schnelle Wordingänderungen

- views/authentication/forms/demo-login.hbs
workaround for today until the phase 2 patch comes out later this day
> hide demo login buttons

- views/administration/users_edit.hbs
disabled email input, emails cant be changed now. to be fixed by SC-408
> hotfix disable change email

- static/styles/lib/base.scss
ticket: https://ticketsystem.schul-cloud.org/browse/SC-463
nur für den Kursbereich
> SC-463-icons für externe Links

- static/scripts/calendar.js
- static/sw.js
changed messages to use postMessage interface instead
> no more require BroadCastChannel API for calendar event updates

- static/styles/lib/bootstrap/scss/_custom.scss
- views/courses/course.hbs
on course page... this text is not so important, it will just be read by the user once..
> smaller course description, also using full width

- views/courses/components/topics.hbs
> change button color depending on available courses

- views/homework/components/overview_card_template.hbs
https://ticketsystem.schul-cloud.org/browse/SC-546
Fix for the Problem, but I don't know why it's even necessary.
> SC-546 fix: circular progress diagramm sometimes shifted

- static/scripts/sw/metrix.js
do not take logs if logged out, what fails currently because testUserGroup element only in DOM if logged in
> only take logs if logged in

- controllers/topics.js
- static/styles/courses/course.scss
- views/courses/components/groups.hbs
- views/courses/components/tasks.hbs
- views/courses/course.hbs
- views/homework/components/course_overview_card_template.hbs
- views/homework/extended.hbs
> Show counter in course tab so user know if its worth clicking

- static/scripts/courses.js
- static/styles/courses/course.scss
- views/courses/components/groups.hbs
- views/courses/components/topics.hbs
- make card transparent when not visible to students
- minor optical improvement to link:hover effects
> SC-538 make card transparent when not visible to students

- views/homework/assignment.hbs
fixed bug from [SC-516](https://ticketsystem.schul-cloud.org/browse/SC-516)
> Sc 516 schueleraufgaben untereinander sichtbar

- controllers/administration.js
Changed the way it's send to jira, so it uses the normal helpdesk route. this also fixed the bug for me. not sure if i missed something. 
Fixes [SC-532](https://ticketsystem.schul-cloud.org/browse/SC-532)
Needs [403](https://github.com/schul-cloud/schulcloud-server/pull/403)
> fixes bug from SC-532

- static/styles/team/team.scss
ticket: https://ticketsystem.schul-cloud.org/browse/SC-545
Lange Wörter werden nicht mehr abgeschnitten/versteckt, sondern in eine neue Zeile umgebrochen
> SC-545-Teamseite-Namen-Umbruch

- helpers/handlebars/middleware.js
- static/styles/lib/loggedin.scss
Navbar umsortiert (driven by Heatmap)
> reorder navbar

- static/scripts/calendar.js
- static/styles/lib/loggedin.scss
- views/lib/loggedin.hbs
* changed page load transition
> changed default view for calendar

- views/courses/edit-course.hbs
https://ticketsystem.schul-cloud.org/browse/SC-601
> SC-601 - "Enter"-Action bugfix

- controllers/tools.js
Ticket: https://ticketsystem.schul-cloud.org/browse/SC-530
> oauth signature does fail with null values

- views/lib/loggedin.hbs
Avatar BG-Color is now static, as of design decision of Mona
> Make Avatar BG Color Static

- static/styles/lib/loggedin.scss
> fix avatar bg color

- controllers/courses.js
- controllers/topics.js
- static/styles/courses/course-edit.scss
- static/styles/lib/loggedin.scss
- views/courses/edit-course.hbs
- views/lib/loggedin.hbs
- to restrict selectable colors for future color palette features
- default #ACACAC (other server PR reflects to server model)
- it's no beauty but works for now till the bigger rework with onboarding happens...
> UX-7 add new color picker to courses

- views/lib/footer.hbs
Added GitHub Link for logged in Users
> Always show GitHub in Footer

- controllers/login.js
quickfix for https://ticketsystem.schul-cloud.org/browse/SC-661
I think we will never want to limit the school count in this dropdown so limit false should be okay here forever, right?
> remove school cap in login entirely

- controllers/administration.js
> cherrypick H-SC user mgmt fix

- controllers/administration.js
- controllers/login.js
- controllers/schools.js
- helpers/authentication.js
- static/scripts/teamMembers.js
- views/administration/school.hbs
- views/lib/loggedin.hbs
Expertenschule in Dropdowns verstecken und bei eingeloggten Experten nicht im Header anzeigen.
https://ticketsystem.schul-cloud.org/browse/NC-71
> Nc 71 hide expertenschule

- views/administration/school.hbs
- views/administration/students.hbs
- views/administration/teachers.hbs
- views/administration/users_edit.hbs
- views/lib/ldap-info.hbs
Adds info message to all management dialogs, where management functionality was removed due to LDAP connection. https://ticketsystem.schul-cloud.org/browse/NC-29
> NC-29-add-ldap-info-message

- views/community/community.hbs
neue jobanzeigen und rel=noopener für etwas mehr sicherheit
> neue jobanzeigen

- views/account/settings.hbs
ticket: https://ticketsystem.schul-cloud.org/browse/SC-656
> SC-656-Benachrichtigungseinstellungen ausblenden

- controllers/about.js
- static/scripts/about.js
- views/about/about.hbs
- views/about/about_guest.hbs
- views/about/about_loggedin.hbs
ticket: https://ticketsystem.schul-cloud.org/browse/SC-654
> SC-654-Pilotschulen auf about-Seite ausklappbar machen

- views/lib/default.hbs
ticket: https://ticketsystem.schul-cloud.org/browse/SC-586
> SC-586-HPI Schul-Cloud als Titel

- static/styles/authentication/home.scss
- views/authentication/home.hbs
ticket: https://ticketsystem.schul-cloud.org/browse/SC-682
> SC-682-Jobanzeigen auf Startseite

- controllers/homework.js
- test/nightwatch/courses/courses_create.js
- test/nightwatch/homework/homework_create.js
- test/nightwatch/login/login_schueler.js
- test/nightwatch/news/news_create.js
Fix für https://github.com/schul-cloud/schulcloud-client/pull/980
Seit dem Server-Pull https://github.com/schul-cloud/schulcloud-server/pull/433 konnten keine Aufgaben mehr erstellt werden (außer wenn eine courseId angegeben wurde). Dies behebt den Fehler und sollte auch gleichzeitg den Travis Test wieder grün werden lassen.
> Aufgaben quickfix

- controllers/administration.js
Server PR: https://github.com/schul-cloud/schulcloud-server/pull/434
> [NC-76] csv import feedback verbessern

- views/authentication/forms/login.hbs
https://ticketsystem.schul-cloud.org/browse/SC-710
> SC-710 Login-Button identifier

- static/styles/lib/loggedin.scss
ticket: https://ticketsystem.schul-cloud.org/browse/SC-701
> SC-701-QR-code bug

- controllers/help.js
ticket: https://ticketsystem.schul-cloud.org/browse/SC-721
> SC-721-Hilfebereich Umbenennung Willkommens-Dokumente

- views/files/lool.hbs
ticket: https://ticketsystem.schul-cloud.org/browse/SC-622
> SC-622-LibreOffice Wording 

- static/styles/courses/course.scss
little css fix, the weak contrast was bugging me all the time 👯‍♂️
> Give invisible courses a clearer contrast

- controllers/teams.js
- static/scripts/teamMembers.js
- views/teams/forms/form-delete-invitation.hbs
- views/teams/forms/form-resend-invitation.hbs
- views/teams/members.hbs
https://ticketsystem.schul-cloud.org/browse/NC-62
still WIP, team service need to be modified by @CeEv
> [WIP] implement resend pending invitations

- controllers/help.js
> Update MINT-EC Link

- controllers/files.js
- helpers/handlebars/middleware.js
- views/files/files-overview.hbs
This will remove Teams from the UI, unless `env.FEATURE_TEAMS_ENABLED` === `true`
> [SC-777] soft toggle teams

- controllers/teams.js
- static/scripts/teamOverview.js
> Fix team create

- static/styles/lib/sc-theme/sc-card.scss
as discussed in the dev channel
> fix word-break

- controllers/administration.js
Ursache: https://ticketsystem.schul-cloud.org/browse/SC-933
> SC-933 Fix broken registration links

- controllers/homework.js
backend pull can be found here: https://github.com/schul-cloud/schulcloud-server/pull/486
> SC-901 student homework archive

- views/content/item.hbs
ticket: https://ticketsystem.schul-cloud.org/browse/SC-299
avoid the neverending loading screen by opening the mailto-link in a new tab
> SC-299-Melden im Materialbereich

- controllers/news.js
- static/styles/lib/sc-theme/sc-card.scss
- test/nightwatch/courses/courses_create.js
- test/nightwatch/news/news_create.js
- views/lib/components/sc-card.hbs
https://ticketsystem.schul-cloud.org/browse/SC-957
> [SC-957] Fix news actions

- app.js
- controllers/administration.js
Might fix https://ticketsystem.schul-cloud.org/browse/SC-1030, but does definitely fix a yet undiscovered error resulting from a large number of users in the student administration.
Please let me know if this can be achieved more elegantly, it's rather late 😉 Btw, this is another argument for moving most of the logic to the server...
> paginate consent requests

- controllers/administration.js
- views/administration/students.hbs
https://ticketsystem.schul-cloud.org/browse/SC-1038
New:
> SC-1038: fix consent counter

- views/lib/forms/form-features.hbs
requested from @JacquelineThorns
> Change new releases redirect

- static/styles/courses/course-edit.scss
> make colors circle

- controllers/news.js
- controllers/teams.js
- views/news/edit.hbs
- views/teams/team.hbs
https://ticketsystem.schul-cloud.org/browse/SC-1080
> [SC-1080] fix news creation in teams

- static/styles/authentication/home.scss
- views/authentication/home.hbs
... but I kept the css styling for frontpage notifications in case we need that later on until full design rework.
https://ticketsystem.schul-cloud.org/projects/SC/issues/SC-1092
> Remove SC-Forum Notification

- controllers/teams.js
fix files.filter is not a function
> FixTeamFiles

- controllers/files.js
files.filter is not a function
> Fix my files

- static/scripts/files.js
- views/files/file-viewer.hbs
- views/files/files-grid.hbs
https://ticketsystem.schul-cloud.org/browse/SC-1086
* SC-1086: handle unknown filetypes with direct download,
fixing broken click handler on unknown files, remove
"Datei extern öffnen" screen/link completely
* fix permanent #file-view problems, resulting in empty video
player on files reload
> SC-1086 Fix unknown filetype handling and #file-view problems

- helpers/handlebars/helpers/index.js
https://ticketsystem.schul-cloud.org/projects/SC/issues/SC-1117
Fix consents because of vanished helper
> SC-1117 Fix broken firstlogin, add missing helper

- views/news/edit.hbs
[SC-1137](https://ticketsystem.schul-cloud.org/browse/SC-1137)
> renamed date field in news area

- controllers/administration.js
- controllers/login.js
- views/administration/school.hbs
Zusätzlich das Anlegen von mehr als einem LDAP/Schule verhindern
> SC-1072 Inaktive LDAPs nicht als Login-Aktion zeigen

- views/files/forms/form-new-file.hbs
Ticket: https://ticketsystem.schul-cloud.org/browse/SC-563
Reine Textänderung.
> SC-563 Change Microsoft file format names to generic names

- views/topic/components/content-geoGebra.hbs
- views/topic/topic.hbs
[SC-1178](https://ticketsystem.schul-cloud.org/browse/SC-1178)
[SC-462](https://ticketsystem.schul-cloud.org/browse/SC-462)
- Begründung:
- Code
> SC-1178-fix-geogebra-applets-in-topics

- controllers/news.js
> SC-1085 fix type checking for non rss news

- static/scripts/files.js
[SC-1171](https://ticketsystem.schul-cloud.org/browse/SC-1171)
changed clickevent handler for 'move file'-button from .one('click') to .on('click')
- Begründung:
- Code
> SC-1171-make-move-file-clickable-repeatedly

- .pullapprove.yml
- PULL_REQUEST_TEMPLATE.md
Add checklist item to check for UX changes in the beginning
- Begründung:
- Code
> Changes to PR review process with ux-core

- views/teams/team.hbs
I will not delete in case we repair that feature in teams
- Begründung:
- Code
> SC-1186 Themen & Aufgaben in Teams verstecken

- PULL_REQUEST_TEMPLATE.md
Migrationsskript etwas prominenter erwähnt, damit es wahrgenommen wird
- https://github.com/schul-cloud/schulcloud-client/pulls/????
- Begründung:
- Code
- Swagger
> SC-1188 Wording Anpassung

- static/styles/dashboard/dashboard.scss
- views/dashboard/components/card_section.hbs
- views/dashboard/dashboard.hbs
[SC-1212](https://ticketsystem.schul-cloud.org/browse/SC-1212)
Umsetzung:
- Begründung:
- Code
> SC-1212-make-dashboard-headers-clickable

- static/scripts/files.js
> move file to folder

- views/registration/forms/einwilligungserklaerung.hbs
kein Ticket
Die verlinkten Einverständniserklärungsdokumente waren die falschen, ersetzen mit den richtigen Links.
> Fix consent docs

- controllers/courses.js
Fixt Parameter, die dazu führen, dass Schüler nicht mehr in Kurse eingeladen werden können.
- https://github.com/schul-cloud/schulcloud-server/pulls/609
> SC-1320 hotfix

- static/scripts/files.js
> Hotfix: SC-1267

- static/styles/help/help.scss
- theme/brb/views/authentication/home.hbs
- theme/brb/views/lib/extended_footer.hbs
- views/imprint/imprint.hbs
https://ticketsystem.schul-cloud.org/browse/SC-1323
https://ticketsystem.schul-cloud.org/browse/SC-1284
> feature/SC-1323 Update Imprint

- controllers/teams.js
> change displayed time format to 24h

- Dockerfile
- Dockerfile.n21
- Dockerfile.open
tzenv and tzdata in Dockerfiles again. in the internet, it's always to late. A really bad thing ends now.
- Begründung:
- Code
> nochmal tzdata für master

- controllers/teams.js
- static/styles/authentication/home.scss
- theme/brb/views/authentication/home.hbs
- views/authentication/home.hbs
Typo-Fix für https://github.com/schul-cloud/schulcloud-client/pull/1211 + ein paar Theme-Anpassungen für BRB + alte Jobanzeige entfernt
- Gefixter PR: https://github.com/schul-cloud/schulcloud-client/pull/1211
- Begründung:
- Code
> Fix some random bugs/brb/stuff

- controllers/teams.js
-~ [ ] Links zu verwandten PRs anderer Repositories~
- Begründung:
- Code
> sort teamnews newest first

- controllers/teams.js
-~ [ ] Links zu verwandten PRs anderer Repositories~
- Begründung:
- Code
> fix teamnews sorting

- views/news/edit.hbs
- ~[ ] Links zu verwandten PRs anderer Repositories~
- ~[ ] Link zum Ticket https://ticketsystem.schul-cloud.org/browse/SC-????~
- Begründung:
- Code
> disable preplanning news

- static/styles/calendar/calendar.scss
- static/styles/dashboard/dashboard.scss
- theme/default/style.scss
- views/dashboard/dashboard.hbs
> SC-1382 fixing readability and div bleeding over in timetable

- controllers/account.js
- controllers/files.js
- views/files/files-grid.hbs
- https://github.com/schul-cloud/schulcloud-server/pulls/641
> SC-1385-umbennen-von-Dateien

- .travis.yml
> Let travis build all branches. Do not limit to master and PRs

- controllers/administration.js
- controllers/teams.js
- static/styles/administration/teams.scss
- views/administration/teams.hbs
- views/teams/overview-empty.hbs
- views/teams/overview.hbs
- https://github.com/schul-cloud/schulcloud-server/pull/647
- Begründung:
- Code
> SC-1341: Admin kann einstellen, dss Schüler Teams anlegen können

- static/scripts/administration/teams.js
- theme/open/views/lib/header.hbs
> prevent default for disabled buttons with tooltip on admin interface

- views/administration/administration.hbs
- views/administration/classes.hbs
- views/administration/courses.hbs
- views/administration/dashboard.hbs
- views/administration/helpdesk.hbs
- views/administration/partials/data_protection_hint.hbs
- views/administration/school.hbs
- views/administration/students.hbs
- views/administration/teachers.hbs
- views/administration/teams.hbs
> Data-Protection Hinweis Admin Interface

- app.js
> update document basepath

- controllers/pwrecovery.js
- views/pwRecovery/pwRecoveryResponse.hbs
> SC-1317-do-not-show-if-email-exist-during-password-reset

- controllers/pwrecovery.js
- package-lock.json
- package.json
- views/pwRecovery/pwRecoveryResponse.hbs
- https://github.com/schul-cloud/schulcloud-server/pulls/672
- Begründung:
- Code
> SC-1541 - Hotfix 18.1.1: Sent mail for password reset by server

- api.js
- app.js
requires KEEP_ALIVE in boss client
> set keep alive header for external and api requests

- helpers/handlebars/helpers/pagination.js
Pagination wird nun nur noch angezeigt, wenn es mehr als eine Seite gibt.
- https://github.com/schul-cloud/schulcloud-server/pulls/???
- Begründung:
- Code
> SC-1531-bugfix page navigation

- static/styles/dashboard/dashboard.scss
> added padding dashboard stundenplan

- static/styles/dashboard/dashboard.scss
- Begründung:
- Code
Vorher:
Nachher:
> fix indentation

- views/about/about.hbs
- Begründung:
- Code
- [] mind. 1 Screenshot bei Content-Änderungen
> SC-1566 Duplizierter Paper name /about

- static/styles/courses/course.scss
- static/styles/dashboard/dashboard.scss
- static/styles/homepage/header.scss
- static/styles/homework/assignment.scss
- static/styles/homework/homework.scss
- static/styles/lib/bootstrap/scss/_buttons.scss
- static/styles/lib/bootstrap/scss/_custom.scss
- static/styles/lib/loggedin.scss
- static/styles/lib/tabbar/tabbar.scss
- test/nightwatch/login/login_demo_schueler.js
- views/authentication/forms/login.hbs
- views/authentication/home.hbs
- views/courses/components/groups.hbs
- views/courses/components/tasks.hbs
- views/courses/components/tools.hbs
- views/courses/components/topics.hbs
- views/courses/create-course.hbs
Der kleine Bruder von Chris' Typo Rework Branch
Headlines PT Sans Narrow
Font PT Sans
Button-Font PT Sans Narrow bold
- Begründung:
- Code
> changed the headline & button font and sizes according to new design system

- controllers/topics.js
- views/lib/loggedin.hbs
Passt die Reihenfolge der Breadcrumbs in Gruppen-Aufgaben an. 
Thema in Gruppe:
- Begründung:
- Code
> SC-1377-fix-breadcrumb-order-in-topics

- .travis.yml
Travis läuft aktuell meist doppelt, einmal für den Pull Request und einmal für den Branch. An Pull Requests ist jedoch nur der Durchlauf für den PR Pflicht.
Nach diesem PR läuft Travis nur noch für Pull Requests und für wenige Branches (master, develop und alle release/hotfix branches)
Die verwendete Regex kann hier getestet werden: https://regex101.com/r/gEndIV/2/tests
Zugehörige Travis Doku: [Link](https://docs.travis-ci.com/user/customizing-the-build/#building-specific-branches)
- Begründung:
- Code
- Release Notes - wenn es sich um große …
> Run travis builds only on pull requests and staging branches

- deploy.sh
- views/authentication/home.hbs
> merge from master

- controllers/index.js
- controllers/version.js
- package-lock.json
- package.json
> git repo info added in /version

- deploy.sh
The Commit-SHA is desired. Should then be found under api.../commitsha.txt
- https://github.com/schul-cloud/schulcloud-client/pull/????
- Begründung:
- Code
- Swagger
> mit commit-sha, ops-30

- static/styles/about/about.scss
- static/styles/homepage/blog-card.scss
- static/styles/homepage/homepage.scss
- static/styles/homepage/index.scss
- theme/brb/views/imprint/imprint.hbs
- theme/brb/views/lib/extended_footer.hbs
- theme/n21/views/help/mail-card.hbs
- theme/n21/views/lib/extended_footer.hbs
- theme/open/views/imprint/imprint.hbs
- theme/open/views/lib/extended_footer.hbs
- views/about/about.hbs
- views/authentication/home.hbs
- views/community/community.hbs
- views/content/item.hbs
- views/help/mail-card.hbs
- views/imprint/imprint.hbs
- views/lib/extended_footer.hbs
Adjusted video player positions
> Sc 1598 videos verschieben

- deploy.sh
replaced prod deployment by chat message to #deployment
> Disable prod auto deplo

- views/about/about.hbs
> Vorträge des 3. HPI Schul-Cloud-Forums verlinkt

- theme/open/views/imprint/imprint.hbs
removed "KOPIE - TODO: REMOVE !!!"
Ticket: https://ticketsystem.schul-cloud.org/browse/OSC-16
- Begründung:
- Code
> Cleaned first line of Impressum

- views/authentication/home.hbs
fächverbindender > fächerverbindender
Hinweis von Patricia, kein Ticket angelegt.
- Begründung:
- Code
> Tippfehler behoben

- controllers/administration.js
- views/help/forms/form_admin.hbs
- views/help/forms/form_bug.hbs
- views/help/forms/form_wish.hbs
- views/lib/forms/form-contactAdmin.hbs
- views/lib/forms/form-contactHPI.hbs
- https://github.com/schul-cloud/schulcloud-server/pulls/684
- Begründung:
- Code
> SC-1588-Feedback-Teams

- controllers/courses.js
> Sc 1699 hide and share lessons

- controllers/administration.js
- views/administration/students.hbs
- views/administration/users_edit.hbs
> Lehrer und Schüler Papierweg, Skip Consent in Admin Student Edit

- static/styles/administration/progress-static.scss
- static/styles/administration/school.scss
- static/styles/lib/colors.scss
- views/administration/school.hbs
> Fix wording and icon colors

- static/styles/homepage/login.scss
- views/authentication/forms/login.hbs
Ticket: https://ticketsystem.schul-cloud.org/browse/SC-1637
> SC-1637 add search to login schools list

- controllers/courses.js
- https://github.com/schul-cloud/schulcloud-server/pulls/729
- https://ticketsystem.schul-cloud.org/browse/SC-1744
> SC-1744 Fix copy course and lessons

- helpers/recurringEvents.js
- package.json
Der fix behebt nicht die Ursache, fängt aber höchstwarscheinlich den Fehler ab.
> SC-1752 use default color if course or team is not avaible.

- static/scripts/administration/classes/manage.js
- views/administration/forms/form-classes-manage.hbs
> fix class registration links

- .travis.yml
Regex an jene in der deploy.sh angepasst
> Update .travis.yml branch regex

- test/nightwatch/homework/homework_create.js
> Fixing Portofolio Tests

- static/styles/lib/loggedin.scss
[SC-1170](https://ticketsystem.schul-cloud.org/browse/SC-1170)
Auf kleineren Screens wird das Help-Dropdown nun nach links geöffnet, damit es immer vollständig sichtbar ist.
- Begründung:
- Code
> SC-1170 Fix help dropdown

- views/courses/create-course.hbs
> preselect course startdate instead of today

- controllers/help.js
- helpers/content/faq.json
- theme/brb/views/help/mail-card.hbs
- theme/brb/views/help/people.hbs
- theme/open/views/help/mail-card.hbs
- theme/open/views/help/people.hbs
- views/help/people.hbs
n21 hat eine eigene Hilfeseite, daher müssen die Daten für n21 nicht angepasst werden.
> use theme specific contact details

- views/courses/courseGroup.hbs
> SC-1330-student-group-ux

- controllers/courses.js
- static/scripts/coursesOverview.js
- static/styles/courses/course.scss
- views/courses/edit-course.hbs
- https://github.com/schul-cloud/schulcloud-server/pull/760
- Begründung:
- Code
> Sc 1760 sync class in courses

- views/registration/forms/einwilligungserklaerung.hbs
> remove ! in einwilligungserklärung

- helpers/content/tutorials.json
> Konstantin sc patch 1

- helpers/theme.js
Fix broken welcome folder because of missing theme variable
> Release 19.4.0 Hotfix: fix welcome folder

- config/documents.js
- theme/open/views/help/mail-card.hbs
Little fixes for staging/19.4.0
Please green it up
> Hs/little 19.4.0 fixes

- static/scripts/jquery/datetimepicker-easy.js
> SC-1801-disable-date-input-scrolling

- controllers/administration/datasources.js
- controllers/administration/index.js
- controllers/administration/other.js
- controllers/index.js
- helpers/handlebars/middleware.js
- static/styles/administration/dashboard.scss
- views/administration/dashboard.hbs
- views/administration/datasources/overview.hbs
neuen Bereich Datenquellen eingefügt + kleiner bugfix bei schulverwaltung
> new datasources page

- controllers/administration/datasources.js
- static/styles/administration/datasources.scss
- views/administration/datasources/forms/form-webuntis-edit.hbs
- views/administration/datasources/overview.hbs
- views/administration/datasources/webuntis-edit.hbs
- views/administration/datasources/webuntis.hbs
> webuntis page mocks

- views/administration/forms/form-classes-edit.hbs
> SC-1837 schuljahr bearbeiten bugfix (handlebars nesting)

- helpers/handlebars/helpers/index.js
- theme/brb/views/lib/footer.hbs
- theme/n21/views/lib/footer.hbs
- theme/open/views/lib/footer.hbs
- views/lib/footer.hbs
> auto generate currentYear

- static/styles/courses/course.scss
- views/courses/edit-course.hbs
> updated delete course message alert

- controllers/help.js
- views/help/releases.hbs
> Feature/sc-1755 - Removed headers on releases page

- static/scripts/loggedin.js
- static/scripts/login.js
- static/vendor/introjs/introjs.min.css
- views/authentication/forms/demo-login.hbs
- views/authentication/forms/login.hbs
> fixed Intro: - removed unnecessary text - changed position of buttons

- config/documents.js
> fix default documentbasedir

- package-lock.json
- package.json
- views/teams/forms/form-add-member.hbs
https://ticketsystem.schul-cloud.org/browse/SC-2104
> Hotfix/SC-2104 19.5.1 hide class button in teams

- controllers/login.js
- package-lock.json
- package.json
- Branch hotfix number is deprecated. Correct number is in package file
- https://github.com/schul-cloud/schulcloud-server/pull/800
> Hotfix 19.5.2 - Moodle issue with BBS1 Bersenbrück

- theme/brb/views/authentication/home.hbs
- theme/n21/views/authentication/home.hbs
resolve SC-2124, demo login removed in mobile view for theme n21 and brandenburg https://ticketsystem.schul-cloud.org/browse/SC-2142
> SC-2124 demo login removed in mobile view for theme n21 and brandenburg

- views/administration/forms/form-ldap-edit.hbs
- https://github.com/schul-cloud/schulcloud-server/pull/811
- Begründung:
- Code
> fix description for LDAP self-service

- theme/brb/views/dataprivacy/privacy.hbs
- theme/open/views/dataprivacy/privacy.hbs
- theme/open/views/dataprivacy/privacy_tom.hbs
- views/dataprivacy/privacy.hbs
- views/dataprivacy/privacy_tom.hbs
TOMs in privacy page for Main, BRB and OPEN; N21 and THR later.
https://ticketsystem.schul-cloud.org/browse/SC-2133
https://ticketsystem.schul-cloud.org/browse/SC-2134
https://ticketsystem.schul-cloud.org/browse/SC-2135
> SC-2133ff Add TOMs to privacy page

- theme/brb/views/authentication/home.hbs
- theme/n21/views/authentication/home.hbs
> SC-2161 | removed double login shown on mobile version in BRB / NBC

- controllers/content.js
- https://github.com/schul-cloud/schulcloud-server/pull/816
- Begründung:
- Code
> SC-2123 | removed limit of courses displayed

- app.js
- controllers/login.js
- helpers/authentication.js
- nodemon.json
this shoud fix jwt that it timed out, see ticket https://ticketsystem.schul-cloud.org/browse/SC-1726
> Releasefix/logout not working jwt (SC-1726)

- static/scripts/files.js
- views/files/forms/form-new-file.hbs
[SC-1375](https://ticketsystem.schul-cloud.org/browse/SC-1375?focusedCommentId=30360&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-30360)
If the user doesn't choose a file type the error message now indicates that:
- Begründung:
- Code
Weitere Informationen zur DoD [hier im …
> SC-1375 More helpful error message if no file type is chosen on file creation

- controllers/files.js
> SC-1315 Do not return API errors to the user

- controllers/courses.js
- https://github.com/schul-cloud/schulcloud-server/pull/824
- Begründung:
- Code
> SC-1976 | removed limit of classes displayed

- config/http-headers.js
- middleware/cors.js
- static/scripts/loggedin.js
> CORS Update - Possibility to add unsafe-eval and unsafe-inline with *

- controllers/login.js
> disabled http only for working with nuxt client

- static/styles/homepage/header.scss
- static/styles/homepage/variables.scss
Just a small UI  tweak (see header)
> Make the header slightly transparent

- controllers/administration.js
> verhindern, dass QR-Codes werden irrtümlicherweise auch für Lehrer erstellt werden

- helpers/content/schools.json
- views/about/about.hbs
- views/administration/teachers.hbs
- views/teams/forms/form-file-permissions.hbs
https://ticketsystem.schul-cloud.org/browse/SC-1567
https://ticketsystem.schul-cloud.org/browse/ORGA-180
https://ticketsystem.schul-cloud.org/browse/SC-1787
https://ticketsystem.schul-cloud.org/browse/SC-1893
> Some content and wording changes found here and there

- static/styles/lib/loggedin.scss
> SC-2396 | vertical centering of initials in the user avatar

- static/styles/lib/base.scss
- theme/brb/views/lib/extended_footer.hbs
- theme/open/views/lib/extended_footer.hbs
- views/lib/extended_footer.hbs
> SC-2398 | Added app store icon and temporarily remove google play icon

- views/about/about.hbs
> ORGA-237-update about page

- views/administration/teachers.hbs
> SC-2354 | remove legend regarding consent of teachers

- static/scripts/homework.js
- static/styles/homework/submissions.scss
- views/homework/components/submission_uploaded_files.hbs
- views/homework/extended.hbs
- views/homework/submission.hbs
> SC-2446 | Displaying Alert Icon for dangerous files in student submissions

- .travis.yml
- static/scripts/login.js
- static/scripts/pwd.js
- static/scripts/settings.js
- static/styles/homepage/login.scss
- views/account/settings.hbs
- views/administration/forms/form-account-password.hbs
- views/authentication/forms/login.hbs
- views/authentication/forms/pwrecovery.hbs
- views/firstLogin/sections/password.hbs
- views/pwRecovery/pwrecovery.hbs
added pwd visiblity toggle
added autocomplete attributes, particularly for safari etc
- Begründung:
- Code
> whoops, overhauled pwd stuff

- views/help/contact.hbs
- views/help/forms/form_bug.hbs
- views/help/forms/form_wish.hbs
> Feature/fix Contact Form

- theme/brb/views/lib/extended_footer.hbs
- theme/open/views/lib/extended_footer.hbs
- theme/thr/views/lib/extended_footer.hbs
- views/lib/extended_footer.hbs
> SC-2597 | re-added google play icon

- theme/open/views/authentication/home.hbs
- theme/thr/views/lib/extended_footer.hbs
- views/community/community.hbs
- views/lib/extended_footer.hbs
> SC-2595 | added DevOps job advertisement in footer

- config/documents.js
- theme/open/views/lib/extended_footer.hbs
- theme/open/views/lib/footer.hbs
- theme/thr/views/lib/extended_footer.hbs
- theme/thr/views/lib/footer.hbs
- views/lib/extended_footer.hbs
- views/lib/footer.hbs
https://ticketsystem.schul-cloud.org/browse/SC-2606
https://ticketsystem.schul-cloud.org/browse/SC-2607
https://ticketsystem.schul-cloud.org/browse/SC-2608
> Add Nutzungsordnung to all footers

- static/scripts/help.js
- theme/brb/views/help/partials/help_nutzungshilfen.hbs
- theme/open/views/help/partials/help_nutzungshilfen.hbs
- views/help/confluence.hbs
- Added Lern-Nuggets to Bosscloud
- Copied old file to open and brb file to hide Lern-Nuggets for these themes
- Lern Nuggets werden auf S3 abgelegt (HTML5, statisch gehosted)
- In [Confluence Seite https://docs.schul-cloud.org/display/SCDOK/Lern-Nuggets](https://docs.schul-cloud.org/display/SCDOK/Lern-Nuggets) muss für den Einstiegspunkt dieser Nuggets verlinkt werden.
> SC-2626 Lern-Nuggets

- package-lock.json
- package.json
- views/administration/forms/form-classes-edit.hbs
schoolId was being lost... however the hidden field was moved out of an if without removing the `../`
> SC-2671 fix class edit/creation

- theme/n21/views/lib/help_menu.hbs
- views/lib/help_menu.hbs
DEVOps: FEATURE_ENTERTHECLOUD must set true, now set it false
Re-Run the permission migration by manually setting it down in the database @schurigh after deployment
> fix: hide menu entry by a new feature toggle

- theme/brb/views/lib/extended_footer.hbs
- theme/n21/views/lib/extended_footer.hbs
- theme/open/views/lib/extended_footer.hbs
- theme/thr/views/lib/extended_footer.hbs
> remove app icons from footers

- package-lock.json
- package.json
- views/community/community.hbs
> Anpassung Mitmachen Seite Bosscloud

- controllers/administration.js
adds missing column classes to teacher list
> Release fix: SC-2841 show classes in teachers list

- controllers/files.js
As substitution teacher i will see couses listed as folders in /files/courses/
> show files from courses where teachers are listed in substitutions ids

- controllers/courses.js
> sort classes by year (and displayname) in course creation/edit

- api.js
- apiEditor.js
- app.js
- config/global.js
- controllers/courses.js
- controllers/topics.js
- helpers/apiHelper.js
- package-lock.json
- Ticket: https://ticketsystem.schul-cloud.org/browse/SC-2980
- Ticket: https://ticketsystem.schul-cloud.org/browse/SC-2981
- Ticket: https://ticketsystem.schul-cloud.org/browse/SC-2983
- Ticket: https://ticketsystem.schul-cloud.org/browse/SC-2943
> ce/Improve request performance SC-2980

- static/scripts/dataprivacy/registration.js
> SC-2776 | added info for readonly fields in registration

- package-lock.json
- package.json
- views/homework/edit.hbs
Ticket: https://ticketsystem.schul-cloud.org/browse/SC-3073
> Hotfix: SC-3073 fix private assignment submission

- views/authentication/forms/demo-login.hbs
> implement SC-3135 - gender demo login

- controllers/login.js
- helpers/authentication.js
> WIP: Add SSO for Thueringen

- controllers/files.js
- static/scripts/files.js
- views/files/files-grid.hbs
- https://github.com/schul-cloud/schulcloud-server/pull/945
> SC-2418 Direktes Öffnen von PDFs durch Browserpreview

- helpers/logger.js
> remove color log in production

- package-lock.json
- static/scripts/dataprivacy/registration-link-validation.js
- static/scripts/dataprivacy/registration.js
- static/scripts/dataprivacy/user-registration.js
- views/registration/registration-employee.hbs
- views/registration/registration-parent.hbs
- views/registration/registration-student.hbs
> SC-2513 fix registration for detect, and disable second registration .form not found

- views/homework/extended.hbs
> SC-3148 copy button in details for tasks

- controllers/help.js
- theme/brb/views/help/lern-nuggets.hbs
- theme/n21/views/help/lern-nuggets.hbs
- theme/open/views/help/lern-nuggets.hbs
- theme/thr/views/help/lern-nuggets.hbs
- views/help/lern-nuggets.hbs
- views/help/partials/help_nutzungshilfen.hbs
> SC-2034 | lern-nuggets integration

- helpers/content/team.js
- package-lock.json
- package.json
> 20.2.1 fix a team image url

- controllers/topics.js
- package-lock.json
- package.json
https://ticketsystem.schul-cloud.org/browse/SC-2031
> hotfix/20.2.2 - fix plural s that prevents nexboard creation on patch

- package-lock.json
- package.json
- views/homework/extended.hbs
https://ticketsystem.schul-cloud.org/browse/SC-2031
Bitte erst auf staging testen bevor gemerged wird.
> hide homework buttons if displayed in an iframe

- static/scripts/jquery/datetimepicker-easy.js
- static/scripts/teams.js
- views/homework/edit.hbs
> SC-2623-week-start-monday

- theme/brb/views/lib/footer.hbs
> fix wrong document in brb footer

- controllers/dashboard.js
- controllers/videoconference.js
- package-lock.json
- package.json
- static/scripts/courses.js
- views/dashboard/dashboard.hbs
> Big blue button/big bug bashing branch

- package-lock.json
- package.json
- views/community/community.hbs
> SC-3406 change wording

- controllers/calendar.js
- package-lock.json
- package.json
- static/scripts/videoconference.js
- views/administration/school.hbs
- views/calendar/calendar.hbs
- views/lib/forms/form-create-videoconference.hbs
> 22.1.4 SC-3419 SC-3407 SC-3418

- config/default.schema.json
- controllers/login.js
- controllers/oauth2.js
- helpers/authentication.js
- views/authentication/forms/login.hbs
- Adds an environment variable to configure the redirect on 401: NOT_AUTHENTICATED_REDIRECT_URL (Default: "/login")
- Handles `?redirect=` URL parameters for:
- `/login`
- `/tsp-login`
- SSO Logins
- After logging in with the `redirect` parameter given, the login controller will redirect to that URL, or the firstLogin if necessary
- Begründung:
- Code
> SC-3307 configurable login redirect

- theme/open/views/authentication/home.hbs
- theme/thr/views/lib/extended_footer.hbs
- views/community/community.hbs
- views/lib/extended_footer.hbs
> Fix link to web dev job offer

- controllers/courses.js
- controllers/topics.js
- package-lock.json
- package.json
> Add boolean helper, add toogle in topic patch route, linter.

- package-lock.json
- package.json
- views/firstLogin/sections/thanks.hbs
> [HOTFIX] SC-3547 | Update Link for "Online-Fortbildung"

- static/scripts/topicEdit.js
anweisungen von Konsti :)
- Begründung:
- Code
> update warning about inline homeworks

- .mergify.yml
- .pullapprove.yml
Wie hier erklärt: https://docs.schul-cloud.org/pages/viewpage.action?pageId=113643606
kann lokalise PRs erstellen mit aktualisierten übersetzungen. 
Das muss wirklich niemand reviewen, gerade weil lokalise bereits review strategien nutzt. Daher diese automatisierung.
> add automerge rule for lokalise PRs

- controllers/oauth2.js
Es ist jetzt möglich, diesen Consent zu skippen. Kann über das SHD konfiguriert werden
- https://github.com/schul-cloud/schulcloud-server/pull/993
- https://github.com/schul-cloud/superhero-dashboard/pull/72
- Begründung:
- Code
> E-Mail und Name für OAuth2 mit OpenIDConnect und Auto Skipping

- controllers/administration.js
- package-lock.json
- package.json
- views/lib/default.hbs
Guesses the CSV file encoding from the file buffer and converts it to UTF-8, so that all characters are preserved when importing users.
Ticket https://ticketsystem.schul-cloud.org/browse/SC-2899
1 new dependency for guessing the encoding. Performance impact can be neglected: guessing and converting a file with 10K users is nearly instant on my machine.
> [SC-2899] guess csv file encoding

- app.js
- controllers/link.js
- package-lock.json
- package.json
- test/mocha/link/link.test.js
- views/lib/error_content.hbs
handle link redirection inside the client & handle errors in client
https://github.com/schul-cloud/schulcloud-server/pull/1035
> 22.3.0 SC-3586

- helpers/handlebars/helpers/index.js
- views/topic/components/content-neXboard.hbs
- set name based on avatar letters
- disable video conference
> set username based on initials instead of naming all users test

- package-lock.json
- package.json
- theme/brb/views/lib/extended_footer.hbs
- theme/brb/views/lib/footer.hbs
- theme/n21/views/lib/extended_footer.hbs
- theme/open/views/lib/extended_footer.hbs
- theme/open/views/lib/footer.hbs
- theme/thr/views/lib/extended_footer.hbs
- theme/thr/views/lib/footer.hbs
- views/authentication/home.hbs
- views/lib/extended_footer.hbs
- views/lib/footer.hbs
- remove demo login
- add status page link in footer
> 22.3.2 SC-3639

- .mergify.yml
- config/default.schema.json
- controllers/login.js
- static/scripts/login.js
- views/authentication/forms/login.hbs
https://github.com/schul-cloud/schulcloud-server/pull/1043
> SC-3609 extend loggedin time for private devices

- .eslintrc.json
- controllers/files.js
- static/scripts/files.js
- views/files/files.hbs
- implemend default sort and sortBy by url query parameter in the middleware for all file view pages
> SC-2842 - file sort

- controllers/dashboard.js
- package-lock.json
- package.json
- views/dashboard/dashboard.hbs
Ticket: https://ticketsystem.schul-cloud.org/browse/SC-3672
> hotfix 22.4.1 - disable dashboard timetable

- controllers/login.js
- helpers/authentication.js
- package-lock.json
- package.json
> hotfix/22.4.2 - prevent client crash on login

- config/default.schema.json
- theme/open/views/imprint/imprint.hbs
- theme/thr/views/imprint/imprint.hbs
- theme/thr/views/lib/footer.hbs
- views/community/community.hbs
- views/imprint/imprint_rights.hbs
- views/lib/extended_footer_links.hbs
- views/lib/footer.hbs
https://ticketsystem.schul-cloud.org/browse/SC-3689
> SC-3689 replace the current contact email address

- controllers/login.js
- package-lock.json
- package.json
the client should stay alive...
> update clear cookie

- controllers/dashboard.js
- controllers/homework.js
- package-lock.json
- package.json
> Force schoolId for using indexes in homework find requests.

- package-lock.json
- package.json
- views/authentication/home.hbs
- readded demo login
- Links zu verwandten PRs anderer Repositories:
schul-cloud/schulcloud-server#1086
- Ticket:
https://ticketsystem.schul-cloud.org/browse/SC-3773
> [Hotfix] SC-3773 | readded demo login

- package-lock.json
- package.json
- views/community/community.hbs
- replaced and updated text on community page
(contact me for screenshot of ui change)
> [Hotfix] Update text on community page

- config/default.schema.json
- package-lock.json
- package.json
- views/authentication/home.hbs
> Hotfix | announcement on startpage

- package-lock.json
- package.json
- views/community/community.hbs
- update text on community page
> [HOTFIX] | update text on community page

- static/robots.txt
added rule allow /mint-ec/* to allow crawlers there
> SC-3707 allow first steps

- locales/de.json
> Homework speichern label umbenannt

- controllers/homework.js
> SC-3816 | fixed typo in filter

- locales/de.json
I (@tofixx ) will rebase this now into the release @CordlessWool
> fixed typo

- CHANGELOG.md
- controllers/courses.js
- controllers/dashboard.js
- helpers/handlebars/helpers/index.js
- locales/de.json
- static/styles/courses/course.scss
- static/styles/homework/assignment.scss
- static/styles/homework/homework.scss
- views/courses/components/tasks.hbs
- views/courses/course.hbs
- views/courses/overview.hbs
- views/homework/assignment.hbs
- views/homework/components/overview_card_template.hbs
- views/homework/edit.hbs
- views/homework/extended.hbs
- views/homework/feedback.hbs
changed many small things:
- sort order of homeworks on course page (due date homeworks first, then according to creation order)
- added link to archived homeworks on course page
- hid archive button for students on homeworks overview page
- private tasks on course page are now always decollapsed
- removed border from course tab container
- removed topic count badge from course tabs, as it was inconsistent with hidden lessons
- rearranged some navigational buttons on homework detail view
- added user count to homework progress wheel
- added feedback badge for graded homeworks
- made print button smaller and moved it to the top right
- hid task copy button for students... as it does not work
- …
> Homeworks Archive Quick Wins

- CHANGELOG.md
- package-lock.json
- package.json
- views/community/community.hbs
- removed 3. point in list (4. now 3.)
- added bold to headline
> [Hotfix] SC-3884 | update text on community page

- CHANGELOG.md
- package-lock.json
- package.json
- views/community/community.hbs
> [HOTFIX] SC-3900 | Update tsc email on community page

- controllers/addons.js
- locales/de.json
- views/addons/addons.hbs
Co-Authored-By: Fabian <tratori@users.noreply.github.com>
Ticket: https://ticketsystem.schul-cloud.org/browse/SC-SC-3560
cherrypick from #1702 (cherrypick @Tratori /addons completed fc67091)
(themes are currently not localisable)
> SC-3560 localize /addons

- controllers/dashboard.js
- locales/de.json
- views/dashboard/dashboard.hbs
Splitting ffeature/SC-3560 up for better legibility
(I at least hope so)
- Links zu verwandten PRs anderer Repositories
- https://github.com/schul-cloud/schulcloud-client/pull/1702
- Link zum Ticket https://ticketsystem.schul-cloud.org/browse/SC-3560
> finished implementation for /dashboard

- locales/de.json
- views/homework/edit.hbs
die /homework Seiten folgen nicht unserem naming schema, daher müssen wir die schrittweise fixen. Dieser PR fixt /homeworks/_homework/edit
- Link zum Ticket https://ticketsystem.schul-cloud.org/browse/SC-3560
> SC-3560 - fix localization keys on homework/edit

- controllers/coursegroups.js
- controllers/courses.js
- controllers/tools.js
- locales/de.json
- static/scripts/courses.js
- static/scripts/coursesOverview.js
- static/scripts/tools.js
- static/scripts/topic.js
- views/courses/components/topics.hbs
- views/courses/forms/form-import-course.hbs
- views/courses/forms/form-import-topic.hbs
- views/courses/forms/form-invitation.hbs
- views/courses/forms/form-tools.hbs
Co-Authored-By: Fabian <tratori@users.noreply.github.com>
Co-Authored-By: Mohammad Abralur Rahman Akash <abralurrahman@users.noreply.github.com>
Ticket: https://ticketsystem.schul-cloud.org/browse/SC-SC-3560
cherrypick from #1702
> SC-3560 localize /courses/*

- controllers/about.js
- controllers/tools.js
- controllers/topics.js
- locales/de.json
> small i18n fixes

- CHANGELOG.md
- config/default.schema.json
- controllers/ghost.js
- controllers/index.js
- package-lock.json
- package.json
- theme/n21/static/scripts/n21-blog.js
- theme/n21/views/authentication/home.hbs
- ticket: https://ticketsystem.schul-cloud.org/browse/SC-3951
- n21 Frontpage now loading content from n21 blog
> [Hotfix] SC-3951 | n21 Frontpage now loading content from n21 blog

- CHANGELOG.md
- controllers/teams.js
- package-lock.json
- package.json
> hotfix 22.9.2 load all team events

- theme/brb/views/help/people.hbs
Change email and title of DABB
> hs/fix contact details in BRB

- CHANGELOG.md
- views/administration/forms/form-ldap-edit.hbs
- views/administration/ldap-edit.hbs
Ticket https://ticketsystem.schul-cloud.org/browse/SC-3757
> SC-3757 add link to ldap docs

- CHANGELOG.md
- views/lib/loggedin.hbs
- https://github.com/schul-cloud/nuxt-client/pull/901
- Begründung:
- Code
> SC438 - clear localStorage

- locales/de.json
- ticket https://ticketsystem.schul-cloud.org/browse/SC-4130
> Fix: Missing text 

- views/administration/school.hbs
https://github.com/schul-cloud/schulcloud-server/pull/1222
Administrators without `SCHOOL_EDIT` permissions should only be able to edit the messenger options if they have `SCHOOL_CHAT_MANAGE` permissions.
no changes
no changes
> SC-3577:  disable messenger option if user lacks edit permissions

- controllers/blog.js
- controllers/index.js
- controllers/login.js
- views/authentication/home.hbs
https://ticketsystem.schul-cloud.org/browse/SC-4190
This pull request adds the possibility to fetch blogs RSS data on the client side. It is needed to load blog posts asynchronously after the main landing page load.
> SC-4190 - Route for fetching blogs RSS data

- CHANGELOG.md
- config/default.json
- config/default.schema.json
- config/production.json
- helpers/authentication.js
- helpers/version.js
- package-lock.json
- package.json
replaces #1810
This moves the cookie properties to be configurable in the Configuration.
Changes the property `samesite` from `strict` to `none` which should solve javascript based redirect issues that lead into logout users.
This could solve THR login issue @Parnswir could you verify this?
@schurigh this change is required to solve issues. how to handle this cookie property in the future?
commons/configuration updated to 1.1.1 to define required defaults
> Hotfix/22.9.12 SC-4036 

- config/default.schema.json
- static/riot_config.json
- static/scripts/chatLoggedin.js
- static/styles/lib/chatLoggedin.scss
Update messenger version to improve: 
- fix 1-to-1 chats
- device-id support
- simplify UI
- logging
- new bundle
- update riot config
- align messenger css
no changes
no changes
no changes
no changes
> Messenger: update to new messenger version to fix 1-to-1 chats

- CHANGELOG.md
- controllers/homework.js
- locales/de.json
- locales/en.json
- package-lock.json
- package.json
- static/scripts/homework.js
- views/homework/submissions.hbs
[Story](https://ticketsystem.schul-cloud.org/browse/SC-4064)
No accompanying PRs. This could be resolved completely in the client.
- Begründung: `multi-download` is a very small package, but allows us to get notified with new versions in case there are quirks in different browsers.
- Code
Weitere Informationen zur DoD [hier im …
> [#SC-4064] Allow bulk download of ungraded homework files (2/4)

- views/authentication/forms/login.hbs
Restricted length of password input to 50 characters.
https://ticketsystem.schul-cloud.org/browse/SC-4111
> SC-4111 - Bcrypt Passwortlange

- static/vendor/ckeditor/config.js
Just changed the default config of tables so they are visible
Fixes https://ticketsystem.schul-cloud.org/browse/SC-4653
> Make table visible by changing default style

- CHANGELOG.md
- locales/de.json
- package-lock.json
- package.json
- theme/n21/views/help/partials/help_form_invite_external_members.hbs
> [Hotfix] SC-4766  - small text change

- controllers/topics.js
- package-lock.json
- package.json
> fix empty pad name and error logging

- controllers/homework.js
- package-lock.json
- package.json
It should be possible to add/upload additional files to submission if it has already been graded.
https://ticketsystem.schul-cloud.org/browse/SC-4764
> SC-4764 add file to graded submission

- static/styles/lib/forms/form-auto-logout-alert.scss
- views/lib/forms/form-auto-logout-alert.hbs
- views/lib/loggedin.hbs
https://ticketsystem.schul-cloud.org/browse/SC-4931
Vorher
Nachher
> SC-4931 repair auto logout modal styles

- static/scripts/files.js
Fix: Clicking a folder name didn't open the corresponding folder (no action is performed).
https://ticketsystem.schul-cloud.org/browse/SC-5092
Techncial fix: Scoping rules for 'this' have been mixed up in some arrow functions.
> SC-5092 Fixed usage of arrow functions due to scoping rules for 'this'

- views/lib/header.hbs
> deleted duplicate

- controllers/files.js
Fix for opening uploaded course/shared files: Independently of their file type nothing happened when the file name is clicked.
https://ticketsystem.schul-cloud.org/browse/SC-5197
The expected attribute 'saveName' has not been set for course/shared file lists.
> SC-5197 Added missing saveName attribute for course and shared files

- controllers/files.js
Fixed missing file download for teams.
https://ticketsystem.schul-cloud.org/browse/SC-5197
Added missing saveName attribute.
> SC-5197 Fixed missing file download for teams

- deploy.sh
> gitflow-hotfix-stash: 1/deploy_hotfix

- views/administration/classes.hbs
- views/administration/dashboard.hbs
- views/administration/forms/form-classes-edit.hbs
Previous branch was closed due to name change.
Ticket: 
https://ticketsystem.schul-cloud.org/browse/SC-4994
> add testIds for integrations tests

- theme/brb/views/help/partials/help_nutzungshilfen.hbs
- theme/open/views/help/partials/help_nutzungshilfen.hbs
- theme/thr/views/help/partials/help_nutzungshilfen.hbs
- views/help/partials/help_nutzungshilfen.hbs
> Change webinare link

- views/courses/create-course.hbs
Fixed access to students and classes in course creation template.
> Fixed access to students and classes in course creation template

- controllers/administration.js
https://ticketsystem.schul-cloud.org/browse/SC-5463
> Feature/SC-5463 Updating pagination logic

- package-lock.json
- package.json
- views/registration/forms/einwilligungserklaerung.hbs
Changing Einverstandniserklarung checkbox text during registration to proper one for teacher registration process.
https://ticketsystem.schul-cloud.org/browse/SC-5328
> SC-5328 - Text Einverstandniserklarung Lehrer 'mein-kind'

- static/scripts/topicEdit.js
changed minus icon on course to trash icon
- https://ticketsystem.schul-cloud.org/browse/SC-5637
> SC-5637 - change-delete-icon

- views/courses/components/tools.hbs
> Fixed reload issue

- static/styles/about/about.scss
- theme/thr/views/about/about.hbs
- views/about/about.hbs
- A11y improvement to about page
- https://ticketsystem.schul-cloud.org/browse/SC-5661
> [SC-5661] A11y improvement to about page

- theme/n21/views/addons/addons.hbs
- views/addons/addons.hbs
- A11y improvement to addons page
- https://ticketsystem.schul-cloud.org/browse/SC-5716
> [SC-5716] A11y improvement to addons page

- views/community/community.hbs
- https://ticketsystem.schul-cloud.org/browse/SC-5719
- Added missed alts
> [SC-5719] Community page a11y

- locales/de.json
- static/scripts/topicEdit.js
Lokalised topicEdit.js
link to ticket:
- https://ticketsystem.schul-cloud.org/browse/SC-5669
> i18n static scripts topicEdit

- theme/brb/views/lib/extended_footer.hbs
- theme/brb/views/lib/footer.hbs
- theme/n21/views/lib/extended_footer.hbs
- theme/open/views/lib/extended_footer.hbs
- theme/open/views/lib/footer.hbs
- theme/thr/views/lib/extended_footer.hbs
- theme/thr/views/lib/footer.hbs
- views/lib/extended_footer.hbs
- views/lib/footer.hbs
- https://ticketsystem.schul-cloud.org/browse/SC-5741
-https://github.com/hpi-schul-cloud/nuxt-client/pull/1161
> SC-5741- cleanup

- locales/de.json
renamed material button in courses from material to lern-material
- https://ticketsystem.schul-cloud.org/browse/SC-5608
> SC-5608 - rename-material-button-in-courses

- deploy.sh
Teams 6 and 7 requested hotfix instances which were deployed. Changes were made to deploy.sh to accomodate new instances.
- https://ticketsystem.schul-cloud.org/browse/OPS-912
- https://ticketsystem.schul-cloud.org/browse/OPS-913
> include team 6 and 7 hotfix instances

- CHANGELOG.md
- controllers/courses.js
- controllers/teams.js
https://github.com/hpi-schul-cloud/schulcloud-server/pull/1540
https://ticketsystem.schul-cloud.org/browse/SC-5686
> SC-5686 - team can only be edited with permission

- helpers/content/team.js
> Quickfix - Update team page

- deploy.sh
- Added std output commands to see deployment actions
- https://ticketsystem.schul-cloud.org/browse/OPS-886
> add deployment output commands

- CHANGELOG.md
- controllers/administration.js
- package-lock.json
- package.json
https://ticketsystem.schul-cloud.org/browse/SC-5917
https://github.com/hpi-schul-cloud/schulcloud-server/pull/1581
> SC-5917 Fix bug in LDAP activation

- static/styles/lib/base.scss
> SC-5644: main skiplink fix a11y

- views/authentication/forms/login.hbs
- https://ticketsystem.schul-cloud.org/browse/SC-5949
small fixes:
- added h1
- content for href
> Feature/sc 5949/fix a11y firstlogin

- views/administration/forms/form-import.hbs
Quickfix uncheck registrierunglink by default
Origin ticket: https://ticketsystem.schul-cloud.org/browse/SC-5938
Subtask of: https://ticketsystem.schul-cloud.org/browse/SC-3515
> SC-5938 - Quickfix uncheck registrierunglink by default

- locales/de.json
The de.json was changed, so that every tab now is 4 spaces. This is not correct and should be changed back.
> fix spacing issue

- theme/brb/views/lib/extended_footer.hbs
- theme/brb/views/lib/footer.hbs
- theme/n21/views/lib/extended_footer.hbs
- theme/n21/views/lib/footer.hbs
- theme/open/views/lib/extended_footer.hbs
- theme/open/views/lib/footer.hbs
- theme/thr/views/lib/extended_footer.hbs
- theme/thr/views/lib/footer.hbs
- views/lib/extended_footer.hbs
- views/lib/footer.hbs
- views/lib/loggedin.hbs
https://ticketsystem.schul-cloud.org/browse/SC-5957
> SC-5957: removed visual focus from the main sections 

- theme/brb/views/lib/extended_footer.hbs
- theme/brb/views/lib/footer.hbs
- theme/n21/views/lib/extended_footer.hbs
- theme/n21/views/lib/footer.hbs
- theme/open/views/lib/extended_footer.hbs
- theme/open/views/lib/footer.hbs
- theme/thr/views/lib/extended_footer.hbs
- theme/thr/views/lib/footer.hbs
- views/lib/extended_footer.hbs
- views/lib/footer.hbs
- views/lib/loggedin.hbs
https://ticketsystem.schul-cloud.org/browse/SC-5957
> SC-5957: removed visual focus from the main sections (a11y)

- CHANGELOG.md
- package-lock.json
- package.json
- views/teams/edit-team.hbs
When both messengers are activated for an instance the matrix messenger options hide the rocketchat options in teams.
This fix make the two options independent of each other.
ToDo:
- https://ticketsystem.schul-cloud.org/browse/SC-5954
- Show RocketChat options independent of MatrixMessenger configuration
- -
- Hotfix, currently only important for Boss-Instance
- -
- -
> Hotfix SC-5954: configure messengers in teams

- locales/de.json
- static/scripts/homework.js
https://ticketsystem.schul-cloud.org/browse/SC-4336
> SC-4336 Fix the teacher's uploads to students submissions

- static/scripts/homework.js
- static/styles/courses/course.scss
- static/styles/teams/teams.scss
- views/courses/course.hbs
- views/teams/team.hbs
solve deadlock between
https://github.com/hpi-schul-cloud/schulcloud-client/pull/2079 (unmerged)
https://github.com/hpi-schul-cloud/integration-tests/pull/131 (merged)
https://github.com/hpi-schul-cloud/integration-tests/pull/105 (not merged)
https://github.com/hpi-schul-cloud/schulcloud-client/pull/1936 (merged)
will solve https://ticketsystem.schul-cloud.org/browse/SC-5742 and https://ticketsystem.schul-cloud.org/browse/SC-4673
TestPR: https://github.com/hpi-schul-cloud/integration-tests/pull/134
> ckeditor/ updated new icon name - solve deadlock

- static/styles/courses/course.scss
- static/styles/teams/teams.scss
- views/courses/course.hbs
- views/teams/team.hbs
Added a new svg icon to the storybook library
https://ticketsystem.schul-cloud.org/browse/SC-5742
Replaced the font awesome icons to "fa fa-ellipsis-v" and updated the css to match the requirements
Before:
After:
> SC-5742 updated new icon name

- controllers/dashboard.js
- package-lock.json
- package.json
- views/homework/components/bulk-grading.hbs
> hotfix 24.2.2

- views/authentication/forms/login.hbs
added spacing between login and mehr optionen
- https://ticketsystem.schul-cloud.org/browse/SC-6158
> SC-6158 - fix spacing between login and mehr optionen

- controllers/administration.js
The class maintenance screen could not be open because the old consents route is no longer accessible by the admin.
The admin should use the new /users/admin/students route instead
https://ticketsystem.schul-cloud.org/browse/SC-6248
> SC-6248 Switch to the new admin student route

- theme/brb/style.scss
- theme/brb/views/lib/header.hbs
- theme/n21/style.scss
- theme/n21/views/lib/header.hbs
- theme/open/style.scss
- theme/open/views/lib/header.hbs
- theme/thr/style.scss
- theme/thr/views/lib/header.hbs
removed margin on top of header and increased size of n21 logo
- https://ticketsystem.schul-cloud.org/browse/SC-6154
> SC-6154 - header margin top and n21 logo fix

- locales/de.json
- static/scripts/calendar.js
- theme/brb/views/lib/extended_footer.hbs
- views/administration/forms/form-courses.hbs
- views/administration/forms/form-invitation-student.hbs
- views/administration/teams.hbs
- views/administration/users_edit.hbs
- views/courses/create-course.hbs
- views/courses/edit-course.hbs
- views/help/dashboard.hbs
- views/teams/team.hbs
fixed missing keys from de.json
based on https://github.com/hpi-schul-cloud/schulcloud-client/pull/2076
https://ticketsystem.schul-cloud.org/browse/SC-6247
> updated missing keys i18n

- views/administration/forms/form-problem.hbs
- views/partner/partner.hbs
> added missing path to key for partner page

- theme/open/views/imprint/imprint.hbs
- theme/thr/views/imprint/imprint.hbs
- views/imprint/imprint_rights.hbs
changed link to internet on impressum page
Base links to copy
- https://ticketsystem.schul-cloud.org/browse/SC-6380
> SC-6380 - change link in impressum

- CHANGELOG.md
- package-lock.json
- package.json
- static/scripts/calendar.js
- theme/n21/views/firstLogin/partials/welcome_existing.hbs
- https://ticketsystem.schul-cloud.org/browse/SC-6382
> hotfix 24.3.1 fix default text und UTC time

- CHANGELOG.md
- controllers/firstLogin.js
- package-lock.json
- package.json
- https://ticketsystem.schul-cloud.org/browse/SC-6382
> Hotfix SC-6382

- locales/de.json
- theme/demo/style.scss
- theme/demo/views/lib/footer.hbs
https://ticketsystem.schul-cloud.org/browse/SC-6095
https://github.com/hpi-schul-cloud/nuxt-client/pull/1285
Related but different Ticket: https://github.com/hpi-schul-cloud/schulcloud-client/pull/2138
> SC-6095 Add demo theme and adjust footer

- locales/de.json
change wording Abmelden to Logout
https://ticketsystem.schul-cloud.org/browse/SC-5846
> SC-5846 change wording Abmelden to Logout

- views/help/contact-card.hbs
https://ticketsystem.schul-cloud.org/browse/SC-6254
> SC-6254 change option to Wunsch

- CHANGELOG.md
- package-lock.json
- package.json
- static/scripts/ckeditor/ckeditor-config.js
- static/scripts/ckeditor/plugins/ckeditor5-filebrowser/src/filebrowser.js
https://ticketsystem.schul-cloud.org/browse/SC-6526
> Hotfix SC-6526

- CHANGELOG.md
- controllers/teams.js
- https://ticketsystem.schul-cloud.org/browse/SC-6245
> SC-6245 Enable students to invite other students to teams

- locales/de.json
- views/help/partials/help_form_invite_external_members.hbs
Ticket: https://ticketsystem.schul-cloud.org/browse/SC-6529
**Affected Pages**
`/teams > open team detail view > click three dots next to team name > "Teammitglieder verwalten" > "Externe Teilnehmer einladen"`
**Before**
**After**
> i18n SC-6529 Wrong language in team invitation

- locales/de.json
- theme/n21/views/authentication/home.hbs
Change wording Versuchen to lower case
https://ticketsystem.schul-cloud.org/browse/SC-5500
> SC-5500 - change wording Versuchen to lowercase

- theme/brb/views/lib/extended_footer.hbs
- theme/open/views/lib/footer.hbs
- theme/thr/views/lib/extended_footer.hbs
- theme/thr/views/lib/footer.hbs
- views/lib/extended_footer.hbs
Ticket: https://ticketsystem.schul-cloud.org/browse/SC-6588
**Affected Pages:**
- Schul-Cloud Footer: "Datenschutzerklärung" should be right now
> i18n SC-6588 Quickfix wrong text footer

- controllers/administration.js
Changed users route to adminUser service to get the right birthdate
https://ticketsystem.hpi-schul-cloud.org/browse/SC-6604
> SC-6604 - change users admin route

- app.js
- controllers/help.js
- views/help/forms/form_bug.hbs
- views/help/forms/form_wish.hbs
fixed max size of file in MB
user can't upload a file because max size was not visible for .hbs so it was 0MB.
- https://ticketsystem.schul-cloud.org/browse/SC-6714
no UI changed
> SC-6714 - max size in MB fix

- CHANGELOG.md
- controllers/administration.js
- package-lock.json
- package.json
Sending an individual registration email returns a success message but no email has been sent.
Problem: When getting the user data from userService, the email is excluded because it's not part of the allowed attributes.
https://ticketsystem.hpi-schul-cloud.org/browse/SC-6761
Added missing email to user data used when calling sendMailHandler()
> hotfix/SC-6761 - Fixed individual registration emails

- CHANGELOG.md
- controllers/administration.js
- package-lock.json
- package.json
- static/scripts/helpers/printQRs.js
Except the layout issues the main problem was a missing limit parameter. By default, the function on server side collecting the users has a limit of 25. But the function on client side worked with a batchSize of 50 without defining a limit. The solution was setting the limit to the batchSize.
https://ticketsystem.hpi-schul-cloud.org/browse/SC-6637
- Set limit to batchSize (=50)
- Updated CSS of QR-Code items: Fixed height, shorten long names
> Hotfix/1/SC-6637 - Fix QR code generation

- CHANGELOG.md
- controllers/courses.js
- package-lock.json
- package.json
It is possible to allow students to write messages in the course chat via a flag in the course settings.
Somebody disabled saving this flag for archived courses (f589e688efdb66cb605ead839e54bbb0e442ca59). The implementation contained a bug which stopped saving the feature flags.
- https://ticketsystem.hpi-schul-cloud.org/browse/SC-6582
- skip saving features in all unarchive requests
- -
- The messenger beta is currently running only on the hpi/boss instance. This instance requires this fix, it will have no influence on other instances.
- -
- -
More and detailed information on the *definition of done* can be found [on Confluence](https://docs.schul-cloud.org/pages/viewpage.action?pageId=928 …
> Hotfix: SC-6582: save messenger flag in course settings

- CHANGELOG.md
- app.js
- controllers/homework.js
- package-lock.json
- package.json
- static/scripts/homework.js
https://ticketsystem.schul-cloud.org/browse/SC-6762
> Hotfix/3/sc 6762/fix evaluation file upload

- CHANGELOG.md
- package-lock.json
- package.json
- static/scripts/ckeditor/plugins/ckeditor5-filebrowser/src/filebrowser.js
- views/homework/assignment.hbs
- views/homework/evaluation.hbs
- views/homework/submission.hbs
The teacher is not able to insert media files while correcting the homework of a student.
The file browser modal is showing up but the button "Server durchsuchen" doesn't work.
The problem: This page is using multiple tabs and utilizes the editor several times. This includes multiple wrappers for the file browser dialog. The dialog has been created multiple times and because of this the event handling fails.
https://ticketsystem.hpi-schul-cloud.org/browse/SC-6823
Removed double wrappers for file browser
> Hotfix/1/SC-6823 - Fixed inserting media in comments for homework correction

- CHANGELOG.md
- controllers/administration.js
- package-lock.json
- package.json
https://ticketsystem.hpi-schul-cloud.org/browse/SC-6845
https://github.com/hpi-schul-cloud/schulcloud-client/commit/60c3714b992eabcebf4fd567729d5b801ee67da1
> fix reset the consent if inputs disabled

- .travis.yml
This PR fixes issue https://ticketsystem.hpi-schul-cloud.org/browse/OPS-1252 . Mocha tests used to run against default branch when PR originating branch name didn't exist. This was fixed by:
- Error handling in place that checks out target branch if originating branch doesn't exist. (Instead of default branch)
- In addition, Hotfix PRs are always tested against master
- https://ticketsystem.hpi-schul-cloud.org/browse/OPS-1252
> OPS-1252 - Fix Mocha tests

- CHANGELOG.md
- package-lock.json
- package.json
> updated changelog, package, package-lock

- CHANGELOG.md
- controllers/administration.js
- package-lock.json
- package.json
- views/administration/users_edit.hbs
https://ticketsystem.hpi-schul-cloud.org/browse/SC-6927
> SC-6927 Fix Admins can delete teachers

- CHANGELOG.md
- controllers/registration.js
- package-lock.json
- package.json
- static/scripts/dataprivacy/pin.js
Ticket: https://ticketsystem.schul-cloud.org/browse/SC-6973
Related Server PR: https://github.com/hpi-schul-cloud/schulcloud-server/pull/1780
> Hotfix SC-6973

- .pullapprove.yml
changes ux conditions for PR approvals in github
- https://ticketsystem.schul-cloud.org/browse/SC-7052
- https://ticketsystem.hpi-schul-cloud.org/browse/IMP-159
ux approve conditions
> SC-7052 - new conditions for ux approve

- .pullapprove.yml
changes ux conditions for PR approvals in github
- https://ticketsystem.schul-cloud.org/browse/SC-7052
- https://ticketsystem.hpi-schul-cloud.org/browse/IMP-159
ux approve conditions
> SC-7052 - ux approvals fix

- controllers/homework.js
Redirecting to submissions after grading, instead of going back to homework
https://ticketsystem.hpi-schul-cloud.org/browse/SC-6629
no datasecurity topics
> added redirect after graded submissions

- config/development.json
- controllers/administration.js
- locales/de.json
- locales/en.json
Addind specific time error message to csv import for students. So the administrator knows, that its specific to a longer import instead of just saying "error while import".
https://ticketsystem.hpi-schul-cloud.org/browse/SC-6023
no datasecurity topics
> Adding specific time error message to csv import

- CHANGELOG.md
- locales/de.json
Correcting sentence structure for parents during registration for students under certain age.
https://ticketsystem.hpi-schul-cloud.org/browse/SC-7151
Only changing the text of the sentence.
No data security topics.
> Fixing sentence structure parents in registration

- package-lock.json
- static/styles/homework/submissions.scss
fixed border on bottom tables on homework page
- https://ticketsystem.schul-cloud.org/browse/SC-6156
> SC-6156 - last row table border fix

- CHANGELOG.md
- app.js
- config/default.json
- config/default.schema.json
- config/development.json
- config/production.json
- package-lock.json
- package.json
- sc-config.json
- print config on startup, update commons to 1.2.7
- make default.json cookie's valid by adding defaults from schema and remove them in development.json
- cookie settings validation moved out of app.js into schema
- required moving some development settings of cookies moved to default to have default.json valid without updating current production values
> Update commons configuration to 1.3.0

- CHANGELOG.md
- locales/de.json
- locales/en.json
- static/scripts/calendar.js
- views/calendar/forms/form-create-event.hbs
By creating an event and switching the course or team checkbox the dropdown with courses or teams should be visible. 
https://ticketsystem.hpi-schul-cloud.org/browse/SC-7392
> SC-7392 show course / teams dropdown by event creation

- CHANGELOG.md
- locales/de.json
- locales/en.json
- views/courses/components/topics.hbs
In the course topics overview there was a different move icon than in the topic editor. The icon in course topics was changed.
https://ticketsystem.hpi-schul-cloud.org/browse/SC-4209
- changed move icon in course topics
no data security topics
> change move icon in course topics

- CHANGELOG.md
- package-lock.json
- package.json
- static/scripts/administration.js
- static/scripts/administration/classes/manage.js
fixed display of user name on qr code printsheets
- https://ticketsystem.schul-cloud.org/browse/SC-7434
> hotfix/1/SC-7434 - qr code name of username fix

- CHANGELOG.md
- static/scripts/login.js
Fixed undefined value when requesting school systems
https://ticketsystem.hpi-schul-cloud.org/browse/SC-7463
> SC-7463 - fix schoolId value

- CHANGELOG.md
- controllers/administration.js
In courses administration the classes which belong to a course are now shown in the overview.
https://ticketsystem.hpi-schul-cloud.org/browse/SC-6721
- classes are shown in the course administration overview again
No data security topics.
> show classes in course administration

- static/styles/homework/homework.scss
> Fix progress style

- CHANGELOG.md
- locales/de.json
There was a grammar issue for german password recovery that is fixed now.
https://ticketsystem.hpi-schul-cloud.org/browse/SC-5501
- corrected capital letter of "zurücksetzen" with small letter (headline and button)
No data security topics
> fixed grammar issue for password recovery

- CHANGELOG.md
- package-lock.json
- package.json
- theme/brb/views/authentication/home.hbs
- theme/open/views/authentication/home.hbs
- theme/thr/views/authentication/home.hbs
deleted theme-blog.js from landing pages which are not using ghost
- https://ticketsystem.schul-cloud.org/browse/SC-7490
> hotfix/1/SC-7490 - landing page get request fix

- CHANGELOG.md
- package-lock.json
- static/scripts/messenger/welcome.js
- https://ticketsystem.schul-cloud.org/browse/SC-6870
> SC-6870 Improve dont show again checkbox handling

- views/help/dashboard.hbs
deleted class which was affecting page reloading
- https://ticketsystem.hpi-schul-cloud.org/browse/SC-6354
> SC-6354 - fix not necessary page reload

- CHANGELOG.md
- locales/de.json
- locales/en.json
- package-lock.json
- package.json
- static/styles/courses/course.scss
- views/topic/components/content-resources.hbs
- views/topic/topic.hbs
This was already done in develop, but has a hard-deadline and needs to be shipped as hotfix.
https://ticketsystem.hpi-schul-cloud.org/browse/SC-7447
> hotfix/5/SC-7447 - adds warning text for lesson materials external links

- views/administration/school.hbs
- https://ticketsystem.schul-cloud.org/browse/SC-6870
> SC-6870 fix rocket chat condition in school admin area

- CHANGELOG.md
- package-lock.json
- package.json
- views/administration/users_edit.hbs
Fixed disabled attribute definition on registration link buttons
https://ticketsystem.hpi-schul-cloud.org/browse/SC-7502
> SC-7502 - hotfix/fix registration link buttons

- CHANGELOG.md
- helpers/logger.js
- https://github.com/schul-cloud/schulcloud-server/pull/1894
- https://ticketsystem.schul-cloud.org/browse/SC-7413
> Feature/sc 7413/add logger options

- static/scripts/theme-blog.js
fixed theme-blog.js, previously it was not placing html on the page correctly and updated ghost page
- https://ticketsystem.schul-cloud.org/browse/SC-7040
> SC-7040 - landing-page-international-fix

- CHANGELOG.md
- views/courses/create-course.hbs
Fix class names not being properly displayed in course creation class selection field. The Names were invisible when a classname only consisted of a number. 
https://ticketsystem.hpi-schul-cloud.org/browse/SC-5555
List of all classes now shows displayName every time which is always given (displayName = 2a, name = a, name can be empty).
No data security topics
No UI changes, only content of a list will change
> SC-5555 - class name not visible in course creation fix

- views/courses/create-course.hbs
- https://ticketsystem.schul-cloud.org/browse/SC-6582
> SC-6582 Fix variable name to access school data

- CHANGELOG.md
- config/default.json
- config/default.schema.json
- config/production.json
- controllers/version.js
This PR aligns renaming env SHOW_VERSION to required changes in server.
https://ticketsystem.hpi-schul-cloud.org/browse/SC-7530
https://github.com/hpi-schul-cloud/schulcloud-server/pull/1898
> SC-7530 rename SHOW_VERSION

- locales/de.json
- locales/en.json
change variable (Experte) name in de.json and en.json files
https://ticketsystem.hpi-schul-cloud.org/browse/SC-7531
> SC-7531 Translation issues with role Expert

- controllers/courses.js
- helpers/timesHelper.js
- test/mocha/helpers/timesHelper.test.js
> SC-2710 fixed timezone test

- CHANGELOG.md
- views/administration/forms/form-rss.hbs
fix of translation key
- https://ticketsystem.schul-cloud.org/browse/SC-7666
> SC-7666 - translation key fix

- CHANGELOG.md
- controllers/teams.js
- static/scripts/teams.js
Edit team event shows event with wrong timezone.
https://ticketsystem.hpi-schul-cloud.org/browse/SC-7645
> SC-7645 fixed team calendar timezone bug

- CHANGELOG.md
- controllers/courses.js
- static/scripts/coursesOverview.js
sharing course between teachers
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/1909
- https://ticketsystem.hpi-schul-cloud.org/browse/SC-7353
route change
> SC-7353 - fix course sharing

- helpers/handlebars/middleware.js
- package-lock.json
Changed administration link name
> Quickfix - Change administration link name

- CHANGELOG.md
- locales/de.json
- locales/en.json
- static/scripts/calendar.js
- views/calendar/forms/form-create-event.hbs
follow up for https://github.com/hpi-schul-cloud/schulcloud-client/pull/2277 to merge into release branch
- https://ticketsystem.hpi-schul-cloud.org/browse/SC-7392
> SC-7392 - copy paste of changes from develop for 7392 into release

- CHANGELOG.md
- static/scripts/ckeditor/ckeditor.js
- views/homework/assignment.hbs
In Tasks (homework) the CKEditor insert image button, shows the "Server durchsuchen" button, which was leading to My Files instead of Course.
This fix allows students to upload files which are stored in the Course the task belongs to, instead of their private files, thus avoiding permission problems.
https://ticketsystem.hpi-schul-cloud.org/browse/SC-5179
> SC-5179 - CKEditor on Task images selection

- CHANGELOG.md
- package-lock.json
- package.json
- test/mocha/content/content.test.js
the legacy lern-store, which is not used has some mocha test fails (relates to configuration and tests on build - all other tests before run successfully.
This failing tests are blocking the release.
The 2 tests are only commented out, and should be fixed to not to test server route, but client only. Currently, they try to connect to production service https://content.schul-cloud.org
https://ticketsystem.hpi-schul-cloud.org/browse/SC-7803
> hotfix/SC-7803 - comments out failing tests for legacy lern store

- CHANGELOG.md
- views/administration/forms/form-classes-edit.hbs
class name is not required to be clicked before creating a class
- https://ticketsystem.schul-cloud.org/browse/SC-7859
> SC-7859 - class name is not required

- CHANGELOG.md
- package-lock.json
- package.json
- static/scripts/login.js
restored fix done in SC-7463 which fixed logging in with external systems
https://ticketsystem.hpi-schul-cloud.org/browse/SC-7463
https://github.com/hpi-schul-cloud/schulcloud-client/pull/2282
https://ticketsystem.hpi-schul-cloud.org/browse/SC-7881
> Hotfix SC-7881 - restore external login fix

- CHANGELOG.md
- controllers/teams.js
We have already updated the handling of name and description string within team model. But the error handling on legacy client only shows an internal error when creating a team with empty name. The error handling on team update was correct. 
https://ticketsystem.hpi-schul-cloud.org/browse/SC-1589
Use the same error handling on team creation as on team editing
> Hotfix/SC-1589 - Update error handling on team creation

- CHANGELOG.md
- views/about/about.hbs
fix typo on about page
- https://ticketsystem.schul-cloud.org/browse/SC-7842
> SC-7842 - about page typo

- CHANGELOG.md
- locales/de.json
- locales/en.json
- views/community/community.hbs
changed text for all other schools dropdown on registration page
- https://ticketsystem.schul-cloud.org/browse/SC-6119
> SC-6119 - changed text for allOtherSchools on register

- CHANGELOG.md
- static/scripts/base.js
- views/authentication/forms/login.hbs
- views/help/partials/help_confluence_links.hbs
- views/homework/assignment.hbs
- views/homework/submissions.hbs
change collapsable icons
- https://ticketsystem.schul-cloud.org/browse/SC-6825
- https://github.com/hpi-schul-cloud/nuxt-client/pull/1566
changed chevron-down to chevron-up
> SC-6825 - change collapsable icons

- CHANGELOG.md
- app.js
The client tries to access env variables previously stored in globals.js
- https://ticketsystem.hpi-schul-cloud.org/browse/SC-7874
- access removed, the values are not used anymore and all access is via `Configuration`
- -
- -
- -
- -
> SC-7874 remove access to removed env values in global.js

- CHANGELOG.md
- controllers/helpdesk.js
- package-lock.json
- package.json
- theme/n21/views/help/mail-card.hbs
- theme/n21/views/help/partials/help_form_button_label_proper_team_name.hbs
- theme/n21/views/lib/extended_footer.hbs
- views/help/contact-card.hbs
- views/help/forms/form_bug.hbs
- views/help/forms/form_wish.hbs
- views/help/partials/help_form_button_label_proper_team_name.hbs
https://ticketsystem.hpi-schul-cloud.org/browse/SC-6727
> Change email addresses for tickets for niedersachcsen

- CHANGELOG.md
- controllers/login.js
- helpers/csrf.js
- package-lock.json
- package.json
- static/scripts/loggedin.js
- views/lib/loggedin.hbs
This PR reverts a previous commit which caused the error that GET /logout has not been completely replaced by POST.  This is just reverting https://github.com/hpi-schul-cloud/schulcloud-client/commit/09752891a3ea79e6c400424094b96f5d9ac63477 
https://ticketsystem.hpi-schul-cloud.org/browse/SC-8000
> SC-8000 - Hotfix 25.2.5 

- CHANGELOG.md
- package-lock.json
- package.json
- static/scripts/login.js
https://ticketsystem.hpi-schul-cloud.org/browse/SC-8027
> Hotfix - SC-8027 fix IDM login

- CHANGELOG.md
- locales/de.json
- locales/en.json
- theme/n21/views/help/partials/help_form_invite_external_members.hbs
- theme/n21/views/help/partials/help_form_note.hbs
- views/teams/forms/form-invite-external-member.hbs
Change text for inviting experts
- https://ticketsystem.schul-cloud.org/browse/SC-7900
> SC-7900 - text changes for people invite

- CHANGELOG.md
- package-lock.json
- package.json
- static/scripts/theme-blog.js
- theme/n21/views/help/mail-card.hbs
merge hotfix to release/25.3.0 - https://github.com/hpi-schul-cloud/schulcloud-client/pull/2382 and https://github.com/hpi-schul-cloud/schulcloud-client/pull/2384
> Hotfix/4/SC-8075 nbc ghost to Release

- static/scripts/ckeditor/plugins/ckeditor5-filebrowser/src/filebrowser.js
https://ticketsystem.hpi-schul-cloud.org/browse/SC-6563
> Fix overwriting videos and audios files

- helpers/recurringEvents.js
- test/mocha/helper/recurringEvents.test.js
> SC-8176: recurring events end date

- CHANGELOG.md
- controllers/courses.js
- controllers/dashboard.js
- controllers/helpdesk.js
> fix common import after hotfix merge

- CHANGELOG.md
- static/scripts/datetime/datetime.js
> SC-8307 use default date formatter when fromats from translations are missing

- CHANGELOG.md
- controllers/homework.js
- views/homework/assignment.hbs
https://ticketsystem.hpi-schul-cloud.org/browse/SC-8272
> SC-8272 - Error message shown even without submission date

- CHANGELOG.md
- static/styles/homework/homework.scss
- views/homework/feedback.hbs
- views/registration/registration-parent.hbs
- views/registration/registration-student.hbs
When testing the ticket small things were found for courses and tasks. Here are the fixes:
- div for printing feedback changed to button so it can be reached with the keyboard
- fixed styling for the student view of archived tasks (no styling for an ordered list)
production:
fix:
button fix:
> SC-5710 - small fixes for the course page

- CHANGELOG.md
- views/firstLogin/partials/language-hint.hbs
- views/help/confluence.hbs
- views/help/contact.hbs
- views/help/help.hbs
- views/registration/registration-employee.hbs
- views/registration/registration.hbs
https://ticketsystem.hpi-schul-cloud.org/browse/SC-7345
> SC-7345 - Unnötiger Gender-Disclaimer im Englischen

- CHANGELOG.md
- static/styles/homework/homework.scss
- static/styles/lib/base.scss
- static/styles/lib/loggedin.scss
- views/homework/edit.hbs
There is no acceptance criteria regarding the max length. It was set to 36 characters. Feel free to suggest a different value.
https://ticketsystem.hpi-schul-cloud.org/browse/SC-8259
'homework/{id}' view:
'/homework/#?sort=dueDate&sortorder=-1' view:
'/courses/{id}/?activeTab=homeworks' view:
> SC-8259: task title shortened

- CHANGELOG.md
- controllers/files.js
- package-lock.json
- package.json
> SC-8337 file upload show error

- .travis.yml
- CHANGELOG.md
This PR enables docker hub authentication for clients' mocha tests to avoid running into limits without authentication enabled.
> SC-8356 add docker login helper from docker-compose repo for mocha tests

- static/scripts/files.js
> SC-8322: improve s3 stability

- static/scripts/files.js
> SC-8322: error handling for files

- CHANGELOG.md
- locales/de.json
- locales/en.json
- static/scripts/base.js
There was an issue, that printing content was undefined. The issue was fixed with this PR.
https://ticketsystem.hpi-schul-cloud.org/browse/SC-6363
> SC-6363: fix print error

- .github/workflows/main.yml
- k8s/configmap.yaml
- k8s/ingress.yaml
> Kubectls experiments ssl

- CHANGELOG.md
- locales/de.json
- locales/en.json
- views/administration/school.hbs
Restored school administration missing text
https://ticketsystem.hpi-schul-cloud.org/browse/SC-8531
> SC-8531 - Restored school administration missing text

- views/files/files.hbs
Small css change in the filters
-->
- https://ticketsystem.schul-cloud.org/browse/SC-8157
> SC-8157 usability filters last minute update 

- views/teams/team.hbs
Fixed the position of the dots icon menu on the teams page
- https://ticketsystem.schul-cloud.org/browse/SC-8526
before:
after:
> SC-8526 menu icon misplaced

- CHANGELOG.md
- app.js
- config/default.schema.json
- config/development.json
Add Feature flag for logging request infos.
https://ticketsystem.hpi-schul-cloud.org/browse/SC-8447
FEATURE_LOG_REQUEST default not set
> add feature toggle for request infos

- CHANGELOG.md
- config/default.json
- locales/de.json
- locales/en.json
- locales/es.json
- test/mocha/helpers/i18n.test.js
- test/mocha/i18n/i18n.test.js
- views/lib/forms/form-change-language.hbs
Adds necessary changes to introduce Spanish as a language to the platform
https://ticketsystem.hpi-schul-cloud.org/browse/SC-8156
> SC-8156 - introduce spanish

- CHANGELOG.md
- controllers/courses.js
DeleteEvents for course will call delete all events for scope instead of deleting all course events in a loop.
https://ticketsystem.hpi-schul-cloud.org/browse/SC-8408
https://github.com/hpi-schul-cloud/schulcloud-server/pull/2249
https://github.com/hpi-schul-cloud/schulcloud-calendar/pull/69
> SC-8408: delete by scope route

- CHANGELOG.md
- controllers/homework.js
- helpers/authentication.js
- views/homework/overview.hbs
https://ticketsystem.hpi-schul-cloud.org/browse/SC-8210
-  create button is removed for students
Before
After
> SC-8210 - remove possibility for students to create tasks

- CHANGELOG.md
- static/scripts/help.js
- views/help/confluence.hbs
The help area search wasn't functioning because the url was blocked by CORS. Changing the url to docs.**hpi**-schul-cloud.org fixed it
https://ticketsystem.hpi-schul-cloud.org/browse/SC-6923
> SC-6923 fixed help area search by changing request url

- CHANGELOG.md
- config/default.schema.json
- package-lock.json
- package.json
https://ticketsystem.hpi-schul-cloud.org/browse/VOR-2
> VOR-2 adjust default for teacher visibilty

- CHANGELOG.md
- controllers/dashboard.js
- package-lock.json
- package.json
- static/scripts/dashboard.js
- views/dashboard/dashboard.hbs
> provide initial code for privacy message

- CHANGELOG.md
- locales/de.json
- locales/en.json
- locales/es.json
- theme/brb/views/authentication/home.hbs
- views/help/language-hint.hbs
Add missing gender; delete language hint out of the language files and hbs; removed space in the code ; remove wrong list-element from the brb landing page
https://ticketsystem.hpi-schul-cloud.org/browse/SC-8595
Add missing gender; delete language hint out of the language files and hbs; removed space in the code; remove wrong list-element from the brb landing page
> SC-8595 – add missing changes after testing

- CHANGELOG.md
- locales/en.json
- theme/open/views/authentication/home.hbs
- theme/thr/views/lib/extended_footer.hbs
add missing changes for job offers in the instances thr, boss and thr
https://ticketsystem.hpi-schul-cloud.org/browse/SC-8660
add missing changes for job offers in the instances thr, boss and thr
> SC-8660 – add missing changes for thr and open instances

- CHANGELOG.md
- locales/de.json
- locales/en.json
the new help area contact page had a typo that I fixed
> Feature/SC-8599 - follow up fixed naming of Schul-Cloud to HPI Schul-Cloud

- CHANGELOG.md
- theme/n21/views/help/help.hbs
- views/help/confluence.hbs
- views/help/contact.hbs
- views/help/help.hbs
There was a PR that removed the linguistic note from the help area. However, this hasn't been done correctly and due to that the help area page doesn't work. I am fixing this with this PR.
bug came from here
- https://github.com/schul-cloud/schulcloud-server/pull/2494
fix the help area page
> SC-8595 remove linguistic note from help page correctly

- CHANGELOG.md
- controllers/index.js
SC-8248 removed the helpdesk, it wasn't removed properly and due to some weird connections with e.g. the contact form some stuff must be kept. 
https://github.com/hpi-schul-cloud/schulcloud-client/pull/2488 here helpdesk was removed
https://github.com/hpi-schul-cloud/schulcloud-client/pull/2489 for that i need the helpdesk route
fix the issue that the helparea contact form can't be submitted
> feature/SC-8248 follow up to fix missing router.use in index.js

- CHANGELOG.md
- locales/de.json
- locales/en.json
- locales/es.json
- package-lock.json
- package.json
- https://ticketsystem.schul-cloud.org/browse/SC-8822
- added availability to phone numbers
- n21/nbr deployment  unneeded
> Hotfix/3/SC-8822 Add availibility to phone number

- CHANGELOG.md
- locales/en.json
- locales/es.json
- theme/open/views/imprint/imprint.hbs
- theme/thr/views/imprint/imprint.hbs
- views/imprint/imprint_rights.hbs
Some changes made to the localize file were lost during the merge of release 26.1.0. This PR is meant to fix that.
> SC-8861 - restore changes lost after release merge

- CHANGELOG.md
- controllers/administration.js
- package-lock.json
- package.json
fixes...
```
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
TypeError: Cannot read property 'displayName' of undefined
at /home/node/app/controllers/administration.js:2473:82
at Array.map (<anonymous>)
at /home/node/app/controllers/administration.js:2473:26
at Array.map (<anonymous>)
at /home/node/app/controllers/administration.js:2470:36
```
required for merging servers feathers-mongoose update as issues occuring (that should not occure...) see https://github.com/hpi-schul-cloud/schulcloud-server/pull/2369
More and detailed information on the …
> feathers-mongoose update at server

- CHANGELOG.md
- views/administration/school.hbs
- https://ticketsystem.hpi-schul-cloud.org/browse/SC-6950
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/2506
> SC-6950 - validation for officialSchoolNumber now allows 5-6 digits instead of 5

- CHANGELOG.md
- locales/de.json
- locales/en.json
- locales/es.json
Base links to copy
- https://ticketsystem.hpi-schul-cloud.org/browse/SC-8730
> SC-8730 Fixing sharing text for sharing whole course

- CHANGELOG.md
- locales/de.json
- locales/en.json
- locales/es.json
- static/styles/help/help.scss
- views/help/forms/form_bug.hbs
- views/help/forms/form_wish.hbs
Yet another PR for SC-8599 to fix some UI issues due to CSS dependencies 
https://ticketsystem.hpi-schul-cloud.org/browse/SC-8599
> SC-8599 UI adjustments of support contact page

- .travis.yml
- CHANGELOG.md
> OPS-1499; OPS-1559 - fixes tests stage condition in travis

- CHANGELOG.md
- controllers/account.js
- locales/de.json
- locales/en.json
- locales/es.json
- package-lock.json
- package.json
> add additional check for email changes

- CHANGELOG.md
- controllers/administration.js
- views/administration/classes_skipregistration.hbs
- https://ticketsystem.hpi-schul-cloud.org/browse/SC-8440
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/2553
> SC-8440 - fix manual consent for class

- CHANGELOG.md
- controllers/administration.js
- https://ticketsystem.schul-cloud.org/browse/SC-7042
> SC-7042 - fix permissions: teachers can send invite link

- CHANGELOG.md
- controllers/registration.js
this PR fixes a problem with registration: the registration also checks that the school exists, so the old endpoint cannot be used anymore, since it requires authentication
- https://ticketsystem.schul-cloud.org/browse/SC-9003
> SC-9018; SC-9003 - fixes registration usage of schools endpoint

- CHANGELOG.md
- helpers/handlebars/middleware.js
- package-lock.json
- package.json
> rename permission TASK_DASHBOARD_VIEW_V3

- CHANGELOG.md
- static/scripts/administration/classes/manage.js
- views/administration/forms/form-classes-manage.hbs
https://ticketsystem.hpi-schul-cloud.org/browse/SC-8073
- Adding students from the previous year feature is disabled for this page. 
> Feature/SC-8073 - Disabling add students from previous year option 

- CHANGELOG.md
- helpers/handlebars/middleware.js
- locales/de.json
- locales/en.json
- locales/es.json
- package-lock.json
- package.json
Adding a new menu entry for the teacher task dashboard with the TASK_DASHBOARD_TEACHER_VIEW_V3 permission
> SC-9143 teacher task overview menu item

- controllers/dashboard.js
- controllers/news.js
- controllers/teams.js
- views/news/article.hbs
This pr switches all news api requests to v3 while feathers services in server have been removed. 
- instead of `api/news`, `api/v3/news` will be used
- news dto field `_id` has been renamed to `id`
- every scoped page might use an own server route, `news/team/:teamId` has been added in server for team news tab
> SC-9159 use news v3

- CHANGELOG.md
- config/default.schema.json
- views/topic/topic.hbs
Hides share button on topic page
- https://ticketsystem.schul-cloud.org/browse/SC-9124
> SC-9124 - hide theme share

- scripts/unitTest.sh
https://github.com/hpi-schul-cloud/docker-compose/pull/43
> Start rabbitMq for unit tests

- CHANGELOG.md
- static/styles/homework/submissions.scss
- fixed layout issue on submissions overview page
- https://ticketsystem.schul-cloud.org/browse/SC-9196
**BEFORE**
**AFTER**
> fixed submissions overview

- static/styles/files/files.scss
Fixed a layout issue which caused a button to be misplaced.
- https://ticketsystem.schul-cloud.org/browse/SC-9208
BEFORE:
AFTER: 
> fixed misplaced button

- CHANGELOG.md
- static/scripts/pwd.js
- views/account/settings.hbs
- views/authentication/forms/login.hbs
https://ticketsystem.hpi-schul-cloud.org/browse/SC-9167
- Fixing show/hide button's bug
- Adding show/hide buttons to each password inputs
> Feature/SC-9167 - Fixing show/hide password buttons' feature

- views/lib/components/sc-card.hbs
- views/news/article.hbs
> Feature/sc 9190 show target/school of news in cards and detail page

- CHANGELOG.md
- static/scripts/pwd.js
- views/account/settings.hbs
- views/authentication/forms/login.hbs
- https://ticketsystem.hpi-schul-cloud.org/browse/SC-9216
- fixing show/hide button's bug for password input on login page
> Feature/SC-9216 - fixing login page password input show/hide functionality

- CHANGELOG.md
- ansible/roles/schulcloud-client/templates/configmap.yml.j2
- locales/de.json
- locales/en.json
- locales/es.json
- theme/n21/views/dataprivacy/privacy_anschrift.hbs
- theme/n21/views/imprint/imprint_rights.hbs
- theme/open/views/imprint/imprint.hbs
- theme/thr/views/imprint/imprint.hbs
- views/imprint/imprint_rights.hbs
Changed contact data in imprint (phone and fax number were removed) and updated email address for brb.
- https://github.com/hpi-schul-cloud/nuxt-client/pull/1849
- https://github.com/hpi-schul-cloud/dof_app_deploy/pull/11
- https://ticketsystem.schul-cloud.org/browse/SC-9221
**BEFORE:**
**AFTER:**
> SC-9221 changed contact data in imprint

- CHANGELOG.md
- controllers/administration.js
- https://ticketsystem.schul-cloud.org/browse/SC-9212
> SC-9212 fix CSV import message formatting

- static/scripts/homework/edit.js
> SC-9230 fix missing text

- .github/workflows/test_e2e.yml
> Add E2E test GitHub action

- CHANGELOG.md
- locales/de.json
- locales/en.json
- locales/es.json
- static/scripts/topicEdit.js
Combined the closed PRs (https://github.com/hpi-schul-cloud/schulcloud-client/pull/2559 &  https://github.com/hpi-schul-cloud/schulcloud-client/pull/2568) and made a minor additional change by renaming the key from internLink to internalLink.
- https://ticketsystem.schul-cloud.org/browse/SC-9074
> SC-9074-wording change for Intern(al) Link in edit topic page

- CHANGELOG.md
- locales/de.json
- locales/en.json
- locales/es.json
- views/courses/overview.hbs
Removed an icon and made changes to a link on courses page.
- https://ticketsystem.schul-cloud.org/browse/SC-6071
> SC-6071 changed wording on courses page

- CHANGELOG.md
- package-lock.json
- package.json
- theme/brb/views/lib/footer.hbs
- theme/thr/views/lib/footer.hbs
- https://ticketsystem.schul-cloud.org/browse/SC-9236
> SC-9236 remove HPI footer logo

- .github/PULL_REQUEST_TEMPLATE.md
Extended pull request template with QA check to verify the change was tested manually if possible.
https://github.com/hpi-schul-cloud/schulcloud-server/pull/2863
> extended pull request template with QA check

- .github/workflows/test_e2e.yml
- CHANGELOG.md
This PR aligns e2e test execution to SC-9191 to how it works currently for the server repo. 
> SC-9191 run e2e tests in pull requests with 'run tests' label

- CHANGELOG.md
- ansible/roles/schulcloud-client/templates/configmap.yml.j2
- config/global.js
- controllers/dashboard.js
- controllers/news.js
- controllers/teams.js
- helpers/apiHelper.js
- package-lock.json
- package.json
> SC-9192 Fix path mapping

- .github/workflows/test_e2e_pull_request.yml
- .github/workflows/test_e2e_push_main.yml
- CHANGELOG.md
This action adds execution for e2e tests for push on main like on the server
BC-67 
> BC-64 BC-67 enable e2e tests for push on main

- CHANGELOG.md
- ansible/roles/schulcloud-client/templates/deployment.yml.j2
Reduce resource consumption for deployed client.
https://ticketsystem.hpi-schul-cloud.org/browse/BC-37
https://ticketsystem.hpi-schul-cloud.org/browse/BC-55
Make CPU and memory resource consumption configurable.
Set the default for memory to be between 128mb and 1gb.
Set the default pod count to 1 pod
> BC-37 - BC-55 - reduce resource consumption for deployed client

- .dockerignore
- .github/workflows/main.yml
- Dockerfile
- package-lock.json
improve Dockerfile and pipeline
> BC-107 improve Dockerfile and pipeline

- .github/workflows/build_push_service.yml
- .github/workflows/tag.yml
- Dockerfile
- scripts/unitTest.sh
those changes are needed for dependency updates from bc-8
> bc-111 improve build pipeline further

- .github/workflows/test_unstable_e2e.yml
- CHANGELOG.md
trigger e2e tests with label on PR `run unstable tests`.
These tests are not mandatory, and can be re-run in about 6 min
- https://ticketsystem.hpi-schul-cloud.org/browse/BC-364
- https://github.com/hpi-schul-cloud/end-to-end-tests/pull/347
- https://github.com/hpi-schul-cloud/nuxt-client/pull/1925
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/3041
> BC-364 - run unstable e2e tests on label run unstable tests

- .github/workflows/push.yml
- CHANGELOG.md
- https://github.com/hpi-schul-cloud/nuxt-client/pull/1952
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/3151
- https://ticketsystem.schul-cloud.org/browse/BC-402
> BC-402 - change e2e test include to reusable workflows

- CHANGELOG.md
- views/administration/teams.hbs
- views/teams/team.hbs
> Create data-testids for e2e test

- CHANGELOG.md
- controllers/courses.js
- controllers/logs.js
> BC-650 - course copy error

- CHANGELOG.md
- helpers/logger.js
- package.json
> hotfix BC-650 - dont exit on error

- .github/workflows/clean.yml
- .github/workflows/push.yml
- CHANGELOG.md
- hpi-schul-cloud/dof_app_deploy#57
- hpi-schul-cloud/schulcloud-server/pull/3169
- https://github.com/hpi-schul-cloud/nuxt-client/pull/1957
- https://github.com/hpi-schul-cloud/schulcloud-calendar/pull/93
- https://github.com/hpi-schul-cloud/superhero-dashboard/pull/137
- https://github.com/hpi-schul-cloud/antivirus_check_service/pull/13
> BC-589 - BC-651 - Change auto deployment to a reusable workflow

- CHANGELOG.md
- package-lock.json
- package.json
- https://ticketsystem.schul-cloud.org/browse/BC-597
> BC-597 - update mathjax

- .github/workflows/clean.yml
- .github/workflows/push.yml
- CHANGELOG.md
Fix for mistake on branch delete event.
It's not GITHUB_REF what shoud be usedm but github.event.ref.
The actions are triggered on the main branch, so GITHUB_REF shows to main and github.event.ref has the branchname of the deleted branch.
https://docs.github.com/en/rest/reference/git#delete-a-reference
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/3190
- https://github.com/hpi-schul-cloud/nuxt-client/pull/1959
- https://github.com/hpi-schul-cloud/schulcloud-calendar/pull/94
- https://github.com/hpi-schul-cloud/antivirus_check_service/pull/14
- https://github.com/hpi-schul-cloud/superhero-dashboard/pull/138
- https://github.com/hpi-schul-cloud/dof_app_deploy/pull/60
More and …
> BC-589 - fix ref branch for delete event

- CHANGELOG.md
- static/scripts/teams.js
Due to working on https://ticketsystem.hpi-schul-cloud.org/browse/BC-563 I found a failing success message string while permission saving. This is fixed by this PR.
Ticket: https://ticketsystem.hpi-schul-cloud.org/browse/BC-563
Server-PR team fix: https://github.com/hpi-schul-cloud/schulcloud-server/pull/3174
- fixing correct link to language file
BEFORE
AFTER
> Fixing success message for permission saving in teams

- CHANGELOG.md
- ansible/group_vars/all/schulcloud-client.yml
- ansible/roles/schulcloud-client/templates/deployment.yml.j2
> BC-740 change ansible vars for docker image and tag

- CHANGELOG.md
- views/courses/edit-course.hbs
Added data-testId to edit-course.hbs to fix e2e test.
- https://github.com/hpi-schul-cloud/end-to-end-tests/pull/349
> added data-testId to fix e2e test

- CHANGELOG.md
- static/scripts/topicEdit.js
https://ticketsystem.hpi-schul-cloud.org/browse/BC-856
plus in the add btn isn't italic anymore
> BC-856-adjust-add-btn-on-topic

- CHANGELOG.md
- theme/thr/views/lib/footer.hbs
https://ticketsystem.hpi-schul-cloud.org/browse/BC-885
adjust thuringia footer
> BC-855-adjust-footer

- ansible/roles/schulcloud-client-core/meta/main.yml
- ansible/roles/schulcloud-client-ldap/meta/main.yml
hpi-schul-cloud/antivirus_check_service#19
hpi-schul-cloud/dof_app_deploy#84
hpi-schul-cloud/nuxt-client#2017
hpi-schul-cloud/schulcloud-calendar#106
hpi-schul-cloud/schulcloud-server#3270
hpi-schul-cloud/superhero-dashboard#153
https://ticketsystem.hpi-schul-cloud.org/browse/BC-1006
> BC-1006 - Meta file for the roles

- package-lock.json
- package.json
The used version of the sanitize-html package is outdated. In the used version, there is a known vulnerability to Arbitrary Code Execution. So the version is updated to the latest one.
The latest update info says:
> The primary change in the 2.x version of sanitize-html is that it no longer includes a build that is ready for browser use. Developers are expected to include sanitize-html in their project builds (e.g., webpack) as they would any other dependency. So while sanitize-html is no longer ready to link to directly in HTML, developers can now more easily process it according to their needs.
Ticket: https://ticketsystem.hpi-schul-cloud.org/browse/BC-1106
More and detailed information …
> BC-1106 Arbitrary Code Execution - sanitize-html Version outdated

- package-lock.json
- package.json
hpi-schul-cloud/schulcloud-server#3304
hpi-schul-cloud/nuxt-client#2035
hpi-schul-cloud/dof_app_deploy#102
> version 27.3.0

- ansible/roles/schulcloud-client-ldap/templates/deployment.yml.j2
Fix an missing ldap in the name of an deployment 
https://ticketsystem.hpi-schul-cloud.org/browse/BC-1202
> BC-1202 - Fix missing ldap at some metadata

- package-lock.json
- package.json
> version 27.4.1

- ansible/roles/schulcloud-client-core/templates/client-configmap-files.yml.j2
add frameSrc to the CSP Rules
https://ticketsystem.hpi-schul-cloud.org/browse/BC-1282
hpi-schul-cloud/nuxt-client#2048
> BC-1282 - add frameSrc to the CSP Rules

- ansible/roles/schulcloud-client-core/templates/client-configmap-files.yml.j2
Fix Ansible role
https://ticketsystem.hpi-schul-cloud.org/browse/BC-1287
> BC-1287 - Fix Ansible role

- ansible/roles/schulcloud-client-core/templates/client-configmap-files.yml.j2
add nexboard to frame source for courses
https://ticketsystem.hpi-schul-cloud.org/browse/BC-1334
hpi-schul-cloud/nuxt-client#2064
> BC-1334 - add nexboard to frame source for courses

- controllers/topics.js
- views/topic/topic.hbs
the buttons to create new tasks and task drafts to a lesson
should only be visible to teachers. also the section to show
all task drafts for the lesson are only shown to teachers.
students can only see the given tasks to a lesson.
Ticket: https://ticketsystem.hpi-schul-cloud.org/browse/BC-1381
> BC-1381 - change behavior for shown tasks below lesson

- controllers/homework.js
As a teacher I should be able to use the task functions via the "three dot menu" on the task card. I should have the option to delete or copy the task and get a confirmation modal to confirm the deletion of a task.
-> to allow that, the return Url to rooms needs to be forwarded during the copy routing
Ticket: https://ticketsystem.dbildungscloud.de/browse/BC-1461
Nuxt-PR: https://github.com/hpi-schul-cloud/nuxt-client/pull/2115
> BC-1461 - Implement task functions into rooms view

- config/default.schema.json
- locales/de.json
- locales/en.json
- locales/es.json
- locales/ua.json
- package-lock.json
- package.json
- views/lib/forms/form-change-language.hbs
- views/lib/loggedin.hbs
- views/user/forms/language.hbs
hpi-schul-cloud/schulcloud-server#3400
hpi-schul-cloud/nuxt-client#2121
hpi-schul-cloud/dof_app_deploy#218
> BC-1617 - ukrainian feature flag

- controllers/topics.js
- views/courses/components/topics.hbs
- views/courses/courseGroup.hbs
- views/topic/edit-topic.hbs
As a teacher, I want to return after creating (discarding) a lesson from where I started the adding flow, so that I don't get confused and save time.
Ticket: https://ticketsystem.dbildungscloud.de/browse/BC-1607
Nuxt Client PR: https://github.com/hpi-schul-cloud/nuxt-client/pull/2127
> BC-1607 - redirect after lesson creation

- controllers/topics.js
- helpers/nexboard.js
- package-lock.json
- package.json
Move code for the neXBoard api from the nexboard-api-js package to this reposetory
https://ticketsystem.dbildungscloud.de/browse/BC-1634
> BC-1634 - Move code for the neXBoard api from the nexboard-api-js package to this reposetory

- views/authentication/forms/login.hbs
fixed password showing/hiding button not working
removed "email" from ids in the email-login-form
> BC-1675-password-showing-not-working

- static/styles/lib/bootstrap/scss/_input-group.scss
During the login on the instances (also on mobile) the hide/show password button looks out of place. Styling should be used to make it look nice again. This behaviour also makes the button in the settings area of ones own account way too big for the line height.
Ticket: https://ticketsystem.dbildungscloud.de/browse/BC-1700
* change padding for button so it fits into the line height with 1/4 of the line height to each side
> BC-1700 - Password login button has wrong size

- views/courses/components/tasks.hbs
- views/topic/topic.hbs
As a teacher within a lesson I am able to create tasks directly linked to that topic. After creating the new task via this way the redirect does not work properly.
Ticket: https://ticketsystem.dbildungscloud.de/browse/BC-1711
- task creation within lesson redirects to the correct page
- task creation (draft) within legacy task view in a course also redirects now to the correct page
> BC-1711 - Redirect after task creation in lesson does not work

- test/mocha/homework/homework.test.js
> remove depricated tests

- views/homework/extended.hbs
Deleting the task from the task detail page is directing to the error page and after refreshing the page task deletion is taking place.
The source is a wrong redirect after deletion which does not work anymore due to the changed task cards behaviour including room view.
https://ticketsystem.dbildungscloud.de/browse/BC-1722
- redirect to main tasks overview after deleting a task via the detail task view
> BC-1722 - Deleting task from task detail leading to error

- locales/de.json
- locales/en.json
- locales/es.json
- locales/ua.json
- views/administration/forms/form-message-owner.hbs
Found another language key while testing in administration teams -> send message to team owner modal, and fixed it.
- BC-1736-language-key-teams-administration
> BC-1736-fixed broken language key in teams administration

- controllers/administration.js
- views/administration/school.hbs
Related to https://github.com/hpi-schul-cloud/schulcloud-server/pull/3440
> BC-1738 Remove unnecessary call for student visibility

- static/scripts/homework.js
The removed call lead to the log entries . Under what conditions is unclear though. I think, the call can be safely removed anyway, because it doesn't do anything besides making GET requests. Please confirm that in review.
https://ticketsystem.dbildungscloud.de/browse/BC-1646
> BC-1646 Remove unnecessary call on file submission

- config/default.schema.json
> BC-1723 Add NO_COLOR Environment variable.

- static/styles/courses/course-edit.scss
Short description
The color picker and modal (on cancel and on delete) do not fit within the screen on mobile. 
Steps to reproduce
Go to course edit page on mobile screen size
Click on cancel or delete
Current result
Color picker & modal "overflow" 
Expected result
Color picker & modal should fit the screen width
https://default-bc-1815-course-edit-responsiveness.cd.dbildungscloud.dev/login
https://ticketsystem.dbildungscloud.de/browse/BC-1815
> BC-1815 - fixed color picker for mobile

- config/default.schema.json
- controllers/homework.js
- views/homework/extended.hbs
Nest task copy service in legacy task detail view.
Ticket: https://ticketsystem.dbildungscloud.de/browse/BC-1552
https://github.com/hpi-schul-cloud/schulcloud-server/pull/3485
> BC-1552 - Nest task copy service in legacy task detail view

- controllers/homework.js
In some cases, the duedate of a task is undefined instead of null.
These cases falsely showed a warning to students that they have less
than 24 hours left.
- https://ticketsystem.dbildungscloud.de/browse/BC-1908
> BC-1908 correctly handle tasks with duedate undefined

- controllers/login.js
The link to IServ was missing a '&' character. This is a quick fix.
> fixed oauth link

- package-lock.json
- package.json
https://github.com/hpi-schul-cloud/dof_app_deploy/pull/296
https://github.com/hpi-schul-cloud/schulcloud-server/pull/3527
https://github.com/hpi-schul-cloud/nuxt-client/pull/2219
https://github.com/hpi-schul-cloud/schulcloud-client/pull/2916
https://github.com/hpi-schul-cloud/end-to-end-tests/pull/420
> version 28.4.0

- views/topic/topic.hbs
the path of the delete was depending on trailing slash
without the trailing slash, this was not correct
BC-2076
> BC-2076 - fix delete path

- controllers/teams.js
- locales/de.json
- locales/en.json
- locales/es.json
- locales/ua.json
- views/courses/course.hbs
- views/courses/overview.hbs
Changing the wording from duplicate to copy
https://ticketsystem.dbildungscloud.de/browse/BC-2073
Nuxt: https://github.com/hpi-schul-cloud/nuxt-client/pull/2233
> BC-2073 - Change wording from "Duplicate" to "Copy"

- controllers/login.js
The data model changed to only having one redirectUri. Therefor the oauth request link has to be changed according to that
https://ticketsystem.dbildungscloud.de/browse/N21-137
https://github.com/schul-cloud/schulcloud-server/pull/3548
> change in oauth request link

- views/homework/edit.hbs
> BC-2119 - Implement data-testid's for creation and deletion of tasks

- package-lock.json
- package.json
- https://ticketsystem.dbildungscloud.de/browse/BC-2078
> remove version from package.json

- views/homework/edit.hbs
> BC-2173 - Add data-testids for confirmation windows in edit tasks

- views/homework/extended.hbs
> Add data-testids in button for homework page

- controllers/teams.js
- controllers/videoconference.js
- static/scripts/videoconference.js
- views/calendar/card.hbs
- views/lib/forms/form-create-videoconference.hbs
Only show the join link for video conferences to experts, if the conference was started with a waiting room.
https://ticketsystem.dbildungscloud.de/browse/N21-182
https://github.com/hpi-schul-cloud/schulcloud-server/pull/3573
> N21-182 allow experts to join video conferences

- locales/de.json
- locales/en.json
- locales/es.json
- locales/ua.json
Changes info texts for not started video conferences
https://ticketsystem.dbildungscloud.de/browse/N21-252
https://docs.dbildungscloud.de/x/cgP-Cw
> N21-252 Changed info texts for videoconferences

- static/scripts/topicEdit.js
There is error in the browser console when creating a new topic, linked to the implemented calendar.
BC-2236
> BC-2236 - Console Error in Browser while creating a new Topic/Lesson

- views/lib/components/files-storage/file-upload.hbs
> Add  data-testids for fileupload field

- views/help/partials/help_nutzungshilfen.hbs
Change link to Schnellstart-Document in all instances > help area (/help/articles) > Nutzungshilfen > Schnellstart-PDF
BC-2265
> BC-2265 - Change link to Schnellstart document in help area

- static/scripts/dropzone/dropzone.js
- views/homework/assignment.hbs
- views/homework/evaluation.hbs
- views/homework/submission.hbs
- views/homework/submissions.hbs
- views/lib/components/files-storage/files-grid.hbs
> BC-2235 more data-testids for file upload

- config/default.schema.json
- controllers/administration.js
- helpers/theme.js
- views/administration/forms/form-classes-manage.hbs
- views/administration/users_edit.hbs
https://ticketsystem.dbildungscloud.de/browse/BC-2289
> consent feature flag

- controllers/link.js
This is to prevent unauthenticated users from resolving share links of files.
https://ticketsystem.dbildungscloud.de/browse/BC-2180
> BC-2180 - Shared links resolve without authentication

- controllers/administration.js
Currently the old school year is automatically selected during class creation. This is due to a wrong sorting in the first place and should be removed.
BC-2313
* remove unnecessary sorting before showing available school years in class creation page
> BC-2313 - Newly created class in the old school year Ticket

- views/administration/partials/ldap_migration_link.hbs
after ldap migration is done, don't show the migration link on Administration page anymore.
This is consistent with the yellow banner message.
BC-2311 
> BC-2311 - hide migration link

- middleware/i18n.js
- static/scripts/dataprivacy/registration.js
- static/scripts/dataprivacy/user-registration.js
- static/scripts/helpers/language.js
- views/registration/registration-employee.hbs
- views/registration/registration.hbs
https://default-bc-2292-language-selection-on-registration-page.cd.dbildungscloud.dev/
> BC-2292 - language selection on registration page

- controllers/homework.js
- static/scripts/base.js
- static/scripts/files-storage.js
- views/homework/extended.hbs
> BC-2290 - change redirect logic

- controllers/teams.js
- views/lib/components/table.hbs
- views/news/article.hbs
> BC-2244 - Add test IDs for several scenarios

- locales/de.json
- locales/en.json
- views/lib/loggedin.hbs
BC-569
https://github.com/hpi-schul-cloud/nuxt-client/pull/2268
> BC-569 - localised tooltip for popup icon initials

- controllers/courses.js
There is a standard on the amount of coursegroups that can be displayed in the coursegroups overview page. To deactivate that standard we specify the limit during the request.
BC-2422
* as there is a small amount of people having more then 25 coursegroups we removed the limit in the request as the performance does not suffer from it
> BC-2422 - Display more than 25 coursegroups in groups tab of courses

- static/scripts/ckeditor/plugins/ckeditor5-filebrowser/src/file-browser-helper.js
> BC-2443 - Topics not editable

- controllers/topics.js
> BC-1513 Replace delete lesson v1 url with v3 url

- views/homework/components/homework_uploaded_files.hbs
- views/homework/components/submission_files.hbs
- views/homework/submission.hbs
Added a new data-testid for file upload sections in submission and grading.
> data-testids added

- static/scripts/dataprivacy/user-registration.js
- static/scripts/settings.js
https://ticketsystem.dbildungscloud.de/browse/BC-2521
> BC-2521 trigger valididation on password confirmation input

- static/styles/authentication/home.scss
Adjust font size for login view (affects NBC instance)
https://ticketsystem.dbildungscloud.de/browse/EW-351
Default CSS for login component
NA
NA
> EW-351 Fix login form font size

- controllers/account.js
https://ticketsystem.dbildungscloud.de/browse/BC-2530
> BC-2530 Add notification after changing own account details

- locales/de.json
- locales/en.json
- locales/es.json
- locales/ua.json
- views/homework/assignment.hbs
Teachers should be able to see, that a task is not accessible for their students, if they have a parent lesson, that is hidden/unpublished.
https://ticketsystem.dbildungscloud.de/browse/BC-2550
https://github.com/hpi-schul-cloud/schulcloud-server/pull/3681
https://github.com/hpi-schul-cloud/nuxt-client/pull/2293
> BC-2550 - task of hidden lesson

- helpers/handlebars/middleware.js
This PR adds a new entry "Dateien" to the sidebar if the user has the permission to see it.
https://ticketsystem.dbildungscloud.de/browse/N21-400
https://ticketsystem.dbildungscloud.de/browse/N21-221
https://github.com/hpi-schul-cloud/nuxt-client/pull/2297
> N21-400 Adds new sidebar entry for files

- views/courses/course.hbs
https://ticketsystem.dbildungscloud.de/browse/BC-2542
Removed invite button in a course details page.
No data-related changes.
No new deployment-related requirements.
No new repos/packages used.
Before:
After:
> remove invite button from the course details template

- static/scripts/administration/users_edit.js
https://ticketsystem.dbildungscloud.de/browse/BC-2612
Fixing the name of button in modal after generating invitation link
>  BC-2612-wrong-button-after-generating-invitation-link

- views/teams/team.hbs
Files are now shown again after upload in the legacy team files section.
https://ticketsystem.dbildungscloud.de/browse/N21-413
https://ticketsystem.dbildungscloud.de/browse/BC-2671
> N21-413 flag around files section

- views/homework/assignment.hbs
Teachers should be able to see, that a task is not accessible for their students, if they have a parent lesson, that is hidden/unpublished.
https://ticketsystem.dbildungscloud.de/browse/BC-2661
> BC-2661 - Fix information text on task details view

- .github/workflows/push.yml
- .github/workflows/security-audit.yml
- .github/workflows/tag.yml
- .github/workflows/test.yml
- .github/workflows/test_unstable_e2e.yml
> BC-2684 update github actions

- static/styles/oauth2/username.scss
- views/oauth2/username.hbs
Base links to copy
- https://github.com/hpi-schul-cloud/schulcloud-client/pull/3003
- https://ticketsystem.dbildungscloud.de/browse/BC-2610
- displaying the whole surname instead of the first letter (ellipsis if text too long)
- font adjusted to bettermarks
> BC-2610 Fix abbreviated names in bettermarks

- package-lock.json
- package.json
https://github.com/hpi-schul-cloud/schulcloud-client/security/code-scanning/179
> BC-2558 - update video.js

- package-lock.json
- package.json
> BC-2558 - remove marked package

- config/default.schema.json
- views/administration/partials/ldap_migration_link.hbs
- views/lib/ldap_migration_banner.hbs
https://ticketsystem.dbildungscloud.de/browse/EW-414
> add feature flag to use central ldap for user migration

- views/courses/edit-course.hbs
After deleting an archived course, return to all courses instead of current courses
- https://github.com/hpi-schul-cloud/schulcloud-client/pull/3051
- https://ticketsystem.dbildungscloud.de/browse/BC-2908
- Change redirect
> BC-2908 After deleting an archived course, return to all courses

- static/scripts/dropzone/dropzone.js
- views/lib/components/files-storage/file-upload.hbs
- views/lib/components/files-storage/files-grid.hbs
> BC-2911 adaopt data test ids

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/push.yml
- .github/workflows/security-audit.yml
- .github/workflows/tag.yml
- .github/workflows/test.yml
- .github/workflows/test_unstable_e2e.yml
https://ticketsystem.dbildungscloud.de/browse/BC-2889)
> BC-2889 limit github action permissions

- package-lock.json
- package.json
> BC-2920 - reinstall browser-sync

- controllers/homework.js
> BC-2825 consider logic submission rule

- package-lock.json
- package.json
CVE-2022-23529
BC-2937
https://github.com/hpi-schul-cloud/schulcloud-server/pull/3800
https://github.com/hpi-schul-cloud/superhero-dashboard/pull/193
> BC-2937 - jwt security update

- views/courses/components/tools.hbs
Removal of misleading text in "Tools"
BC-2868
> BC-2868-Removal-of-misleading-text

- config/default.schema.json
BC-2785
https://github.com/hpi-schul-cloud/dof_app_deploy/pull/425
> BC-2785 - make hydra legacy false by default

- .github/workflows/test.yml
https://ticketsystem.dbildungscloud.de/browse/BC-2867
> BC-2867 Change workflow triggers

- static/styles/courses/course.scss
- views/topic/components/content-text.hbs
* Content area in lessons too narrow (Tablet)
* Title element has no Grid Classes
BC-2906
> BC-2906 - Content area in lessons too narrow

- static/scripts/topicEdit.js
- views/topic/edit-topic.hbs
new data-testids in editTopic for Cypress tests
> BC-2972 added datatestids

- locales/de.json
- locales/en.json
- locales/es.json
- locales/ua.json
- static/scripts/teamMembers.js
- views/teams/forms/form-invite-external-member.hbs
https://github.com/hpi-schul-cloud/schulcloud-server/pull/3808
https://ticketsystem.dbildungscloud.de/browse/BC-2909
> BC-2909 - change external teacher permission

- controllers/homework.js
(https://ticketsystem.dbildungscloud.de/browse/BC-3030)
https://default-bc-3030-submission-overview.cd.dbildungscloud.dev/
> BC-3030 - change assign of submitters

- static/styles/homework/submissions.scss
- views/homework/evaluation.hbs
- views/homework/submission.hbs
> BC-2575 - Use new file storage for embedded grading files

- views/homework/evaluation.hbs
> BC-2575 - Use old file storage for embedded grading files

- controllers/homework.js
> BC-3051 - merge teachers array correctly

- .github/workflows/tag.yml
> BC-2996 generate an sbom for a release

- controllers/coursegroups.js
- views/courses/courseGroup.hbs
> BC-3077 - Remove delete button on lessons for students in course groups

- .github/workflows/push.yml
> BC-3076 removal of trivy exit-code: 1

- views/administration/school.hbs
- views/calendar/card.hbs
[BC-3078](https://ticketsystem.dbildungscloud.de/browse/BC-3078)
- Assigned data-testids on different web elements
> added data test ids

- locales/de.json
- locales/en.json
- locales/es.json
- locales/ua.json
- static/scripts/teamMembers.js
- views/teams/forms/form-invite-external-member.hbs
This reverts commit 0c2ad5092eeb51e5e598c4e6ba355ca01a2059f2.
(reverts PR https://github.com/hpi-schul-cloud/schulcloud-client/pull/3061)
Reverts ticket BC-2909
https://github.com/hpi-schul-cloud/schulcloud-server/pull/3875
> Revert "BC-2909 - change external teacher permission (#3061)"

- static/scripts/teamMembers.js
- views/lib/components/table.hbs
- views/lib/loggedin.hbs
- views/teams/members.hbs
Added sorting function for all users for Teams
- https://ticketsystem.dbildungscloud.de/browse/BC-3164
> BC-3164-Added sort for all users

- theme/thr/views/lib/no-create-info.hbs
> BC-3069 - Fix text in no create info

- controllers/login.js
- change /system to /systems/public
https://ticketsystem.dbildungscloud.de/browse/N21-500
https://github.com/hpi-schul-cloud/dof_app_deploy/pull/450
https://github.com/hpi-schul-cloud/schulcloud-server/pull/3864
> N21-500 change systems endpoint

- controllers/homework.js
- helpers/files-storage.js
> BC-2189 - Handle file service not available

- static/scripts/topicEdit.js
- views/teams/topics.hbs
- views/topic/topic.hbs
Added data-testids for cypress test createEditDeleteTopic
> added data-testids for cypress tests

- config/default.schema.json
- helpers/handlebars/helpers/index.js
- views/lib/loggedin.hbs
Implement new env vars for role specific status infos for federal states as well as info in dof deploy repo.
BC-3152
https://github.com/hpi-schul-cloud/dof_app_deploy/pull/479
- implement new functionality to show role specific message with new logic in legacy client
- GLOBAL_ANNOUNCEMENT_TEXT will set the text of the status which will be shown to the roles set in the (array) GLOBAL_ANNOUNCEMENT_ROLES
> BC-3152 - Display blue status bar info

- views/courses/create-course.hbs
data-testids should be in english language, so two, that were in german, are changed now.
> changed to english data-testids

- .github/workflows/dependabot-to-jira.yml
- .github/workflows/push.yml
- .github/workflows/tag.yml
> BC-3143 adding dependabot to jira workflow

- .github/workflows/push.yml
> BC-3143 differentiate between prs and branches

- .github/workflows/push.yml
> BC-3143 fix trivy action

- controllers/login.js
Thueringen wants to use the Nextcloud. When logging in to THR, one is first redirected to the THR Schulportal site. In order for the user to get redirected to Nextcloud after authenticating to THR Schulportal site, the default redirect to the schulcloud site cant be /dashboard but has to be /. The user is still redirected to /dashboard when he opens the schulcloud site.
I tested the functionality of the redirect on sc-staging for thr, by changing the image of the client deployment temporarily to ghcr.io/hpi-schul-cloud/schulcloud-client-thr:7b432d9b6c9d4fab3aa8736781a998b593347920. 
https://ticketsystem.dbildungscloud.de/browse/OPS-4312
> OPS-4312-thr-connect-nextcloud

- static/styles/lib/loggedin.scss
Improves styling of the sidebar items
Ticket: https://ticketsystem.dbildungscloud.de/browse/BC-3925
Vue Client: https://github.com/hpi-schul-cloud/nuxt-client/pull/2504
> BC-3925 - adjust styling sidebar items

- .github/workflows/tag.yml
https://ticketsystem.dbildungscloud.de/browse/BC-3778
> BC-3778 push container image to quay.io

- views/administration/school.hbs
Due to previous changes in the _button.scss in the ticket mentioned below, the new admin page button is greyed out. 
This PR changes the color to show the button correctly.
https://ticketsystem.dbildungscloud.de/browse/BC-3348
https://ticketsystem.dbildungscloud.de/browse/N21-903
> N21-903-admin-page-btn-fix

- app.js
> BC-4103 - fix redirect to login

- app.js
- config/default.schema.json
this is a second fix (see #3194 already merged)
> BC-4103 - fix login redirect

- views/help/releases.hbs
Change URL to fetch release notes from to new repo and adjust appearance in Frontend.
BC-4055
https://github.com/hpi-schul-cloud/schulcloud-server/pull/4153
Before:
After:
> BC-4055 - Replace release notes repo

- views/authentication/forms/pwrecovery.hbs
Remove maxlength Increase the character limit for pwrecovery
https://ticketsystem.dbildungscloud.de/browse/BC-4107
> BC-4107 Remove limit character for pwrecovery.

- app.js
This reverts commit bded482677765556773f496e2070d4cc13531976.
this is a revert of a revert (i.e. a restoration)
The assumption was the original change (client tag 31.8.5) caused a problem with the release, so a revert was was implemented in 31.8.6
It turned out, the release problem had nothing to do with it, so here we reinstate the original change.
BC-4152
> Revert "BC-4152 revert redirect changes (#3202)"

- controllers/login.js
- helpers/authentication.js
lets user always reauthenticate when migrating to moin.schule.
https://ticketsystem.dbildungscloud.de/browse/N21-989
> add prompt = login in the user-login-migration flow

- controllers/courses.js
- locales/de.json
- locales/en.json
- locales/es.json
- locales/uk.json
- views/courses/create-course.hbs
- views/courses/edit-course.hbs
- views/teams/edit-team.hbs
https://ticketsystem.dbildungscloud.de/browse/N21-883
> N21-883 Add checkbox for videoconferences to courses

- .github/workflows/push.yml
https://ticketsystem.dbildungscloud.de/browse/BC-4051
> BC-4051 Add cypress tests to push workflow

- views/authentication/forms/login.hbs
hotfix - with this we use the old (server) oauth flow
> N21 1049 old button

- static/scripts/helpers/AlertMessageController.js
The red status flag of a 02.06.23 message is sometimes displayed. The status message should not be displayed because of being "solved" on the status page.
https://ticketsystem.dbildungscloud.de/browse/BC-4259
Link to deployment : https://default-bc-4259-hide-done-sc-status.cd.dbildungscloud.dev/
Link to board : https://default-bc-4259-hide-done-sc-status.cd.dbildungscloud.dev/rooms/64b79e59796c66b39c512db3/board
> BC-4259 - Flag of SC status may show in NBC despite being turned off

- .github/dependabot.yml
https://ticketsystem.dbildungscloud.de/browse/BC-4645
https://github.com/hpi-schul-cloud/nuxt-client/pull/2678
https://github.com/hpi-schul-cloud/schulcloud-client/pull/3234
https://github.com/hpi-schul-cloud/schulcloud-server/pull/4264
> BC-4645 re-enabled dependabot for dependency updates

- controllers/administration.js
- controllers/courses.js
- controllers/teams.js
- helpers/users.js
- static/scripts/administration/classes/edit.js
- static/scripts/bootstrap-fix/bootstrap-select-hidden-options.js
- views/administration/classes-edit.hbs
- views/administration/classes-manage.hbs
- views/administration/forms/form-classes-edit.hbs
- views/administration/forms/form-classes-manage.hbs
- views/courses/create-course.hbs
- views/courses/edit-course.hbs
- views/teams/forms/form-add-member.hbs
- views/teams/members.hbs
https://ticketsystem.dbildungscloud.de/browse/N21-900
https://github.com/hpi-schul-cloud/schulcloud-server/pull/4292
> N21-900 Hide outdated users

- controllers/administration.js
- controllers/teams.js
- static/scripts/administration/teams.js
- views/administration/forms/form-courses.hbs
- views/administration/forms/form-teams.hbs
- views/courses/create-course.hbs
- views/courses/edit-course.hbs
- views/teams/forms/form-add-member.hbs
https://ticketsystem.dbildungscloud.de/browse/N21-956
https://github.com/hpi-schul-cloud/schulcloud-server/pull/4296
https://github.com/hpi-schul-cloud/end-to-end-tests/pull/440
> N21-956 Add ~~ to display names of outdated users

- controllers/blog.js
- package-lock.json
- package.json
> BC-4667 - update feedr

- config/default.schema.json
- locales/de.json
- locales/en.json
- locales/es.json
- locales/uk.json
- static/styles/dashboard/dashboard.scss
- views/dashboard/dashboard.hbs
QA note:
Tested on env: https://brb-bc-4463-add-bettermarks-announcement.cd.dbildungscloud.dev/
No issues found.
https://ticketsystem.dbildungscloud.de/browse/BC-4463
https://github.com/hpi-schul-cloud/dof_app_deploy/pull/599
> add bettermarks announcement

- .github/workflows/push.yml
- https://ticketsystem.dbildungscloud.de/browse/BC-4624
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/4320
- https://github.com/hpi-schul-cloud/nuxt-client/pull/2727
> BC-4624 - failed builds should be reported

- static/styles/lib/base.scss
- static/styles/lib/bootstrap/scss/_navbar.scss
- static/styles/lib/loggedin.scss
- theme/brb/style.scss
- theme/n21/style.scss
- views/lib/default.hbs
- views/lib/loggedin.hbs
- views/lib/simple.hbs
QA note:
change tested on: 
https://brb-bc-4845-fix-header-and-footer.cd.dbildungscloud.dev/
https://nbc-bc-4845-fix-header-and-footer.cd.dbildungscloud.dev/
https://default-bc-4845-fix-header-and-footer.cd.dbildungscloud.dev/
No isuess found. Header & footer on login page looks ok. 
https://ticketsystem.dbildungscloud.de/browse/BC-4845
> fix header and footer

- locales/en.json
- locales/es.json
- locales/uk.json
QA note:
Tested on env:
https://nbc-bc-3188-fix-translation.cd.dbildungscloud.dev/
Rest of env brb dbc not working.
On env NBC no issues found.
Changes address env TSP, verification when the change enters staging.
https://ticketsystem.dbildungscloud.de/browse/BC-3188
> fix translations for add member

- views/lib/forms/form-change-language.hbs
QA note:
Tested on env:
https://brb-bc-1802-fix-school-language-settings.cd.dbildungscloud.dev/
https://nbc-bc-1802-fix-school-language-settings.cd.dbildungscloud.dev/
https://default-bc-1802-fix-school-language-settings.cd.dbildungscloud.dev/
No issues found. The language dropdown is set to the current language of the schoo 
https://ticketsystem.dbildungscloud.de/browse/BC-1802
https://github.com/hpi-schul-cloud/nuxt-client/pull/2731
> fix displaying school lnguage settings

- locales/de.json
[#](url) Description
Fixed typo for german language key for the error bird.
Current text:
Da ist etwas schief gelaufen!
Corrected text:
Da ist etwas schiefgelaufen!
> BC-3216-Langage key typo for german locales is fixed.

- .github/PULL_REQUEST_TEMPLATE.md
To make sure the accessability is kept in mind, the PRs for FE should include a reminder checkbox for that topic.
BC-4870
https://github.com/hpi-schul-cloud/nuxt-client/pull/2738
> BC-4870 - Add a11y reminder checkbox into FE PR templates

- static/scripts/topicEdit.js
Necessary changes to support the other PRs
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/4364
- https://github.com/hpi-schul-cloud/nuxt-client/pull/2775
> THR-6 H5P Editor authorization

- helpers/content/tutorials.json
https://ticketsystem.dbildungscloud.de/browse/BC-5070
> BC-5070 Anpassung Hilfebereich Update tutorials.json

- .github/workflows/push.yml
- .github/workflows/tag.yml
the current version 4.2.0 for the github action docker/build-push-action who is pulled if we use as version set v4 hass an issue with our metadata json so we must pin it to version 4.1.1 for now
hpi-schul-cloud/superhero-dashboard#229
hpi-schul-cloud/antivirus_check_service#41
hpi-schul-cloud/version-aggregator#10
hpi-schul-cloud/h5p-staticfiles-server#3
hpi-schul-cloud/schulcloud-server#4396
hpi-schul-cloud/nuxt-client#2795
hpi-schul-cloud/schulcloud-calendar#141
> BC-5100 - Pin docker/build-push-action to version 4.1.1 

- controllers/oauth2.js
Shows username when user will be found
https://ticketsystem.dbildungscloud.de/browse/N21-1269
> N21-1269 change pseudonym display

- controllers/oauth2.js
Fixes the resolution of usernames
https://ticketsystem.dbildungscloud.de/browse/N21-1269
> N21-1269 pseudonym username fix

- helpers/authentication.js
Bug Fix
Due to logic changes in server and nuxt repo regarding migration control, we need to add validation in legacy client.
https://ticketsystem.dbildungscloud.de/browse/N21-841
https://github.com/hpi-schul-cloud/nuxt-client/pull/2769
https://github.com/hpi-schul-cloud/schulcloud-server/pull/4356
> N21-841-use-user-login-migration

- controllers/files.js
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/4453
- https://ticketsystem.dbildungscloud.de/browse/BC-5461
> BC-5461 - fix personal file page error

- controllers/administration.js
- views/administration/forms/form-teams.hbs
QA note:
I tested your tickiet on env: 
https://brb-bc-4879-assign-additional-owner-search.cd.dbildungscloud.dev/
No issues found. Sorting is done last name, first name. Added possibility to insert text when searching.
Problem with adding a new owner to a team created by a teacher (Error details:Can not patch team.), wrong display of members, adding the same user several times is not related to this change.  
For Thueringen, change requires re-testing on staging env: https://test.schulportal-thueringen.de/ on new release.
https://ticketsystem.dbildungscloud.de/browse/BC-4879
> BC-4879 - Make the 'Assign an additional owner' field usable

- controllers/courses.js
> BC-5477 - Add optional chaining operator to course.times

- views/courses/edit-course.hbs
Adds a check if the course is archived. if true disable checkbox for videoconferences.
https://ticketsystem.dbildungscloud.de/browse/N21-1314
> N21-1314 bbb-toggle-in-archived-course

- controllers/login.js
- static/scripts/login.js
Fixes error handling of the user login migration and prevents opening logout window when no logoutEndpoint is set in the systems oauth config.
https://ticketsystem.dbildungscloud.de/browse/N21-1378
> N21-1378 fix migration error

- config/default.schema.json
- locales/de.json
- locales/en.json
- locales/es.json
- locales/uk.json
- static/styles/dashboard/dashboard.scss
- views/dashboard/dashboard.hbs
New message in announcement bar on dashboard for teacher only.
BC-5536
https://github.com/hpi-schul-cloud/dof_app_deploy/pull/683
- new message in dashboard announcement for teacher only
- adjust code style to more general approach (instead of bettermarks specific)
From ticket: "To be merged on 6th November to meet target release date. (depending on actual release planning)"
> BC-5536 - Add Information about user survey (for teachers only) in multi-message-banner

- config/default.schema.json
- controllers/login.js
- static/scripts/login.js
- views/authentication/forms/login.hbs
Removes the old login which handled the oauth login on server side. Now it will be only handled on client side.
- https://ticketsystem.dbildungscloud.de/browse/N21-1374
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/4541
- https://github.com/hpi-schul-cloud/dof_app_deploy/pull/699
- https://github.com/hpi-schul-cloud/nuxt-client/pull/2905
> N21-1374 removes old login flow

- static/scripts/topicEdit.js
- views/topic/edit-topic.hbs
This reverts commit eee257ae30a4c99406293b1d29aee2d104a64bde.
The schulcloud-client PR from [BC-5119](https://ticketsystem.dbildungscloud.de/browse/BC-5119) was merged before the other PRs from that ticket were ready. Therefore we want to revert that merge.
BC-5901
> BC-5901: Revert "BC-5119-Prevent create new neXboard (Front)  (#3313)"

- ansible/roles/schulcloud-client-core/templates/client-configmap-files.yml.j2
- https://ticketsystem.dbildungscloud.de/browse/BC-5862
- hpi-schul-cloud/dof_app_deploy#712
> BC-5862 Added configurable bettermarks urls

- ansible/roles/schulcloud-client-core/templates/client-configmap-files.yml.j2
- config/http-headers.js
- views/lib/extended_footer.hbs
https://ticketsystem.dbildungscloud.de/browse/BC-5980
> BC-5980 cleanup cors rules

- controllers/administration.js
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/4573
> BC-5829 - update mongoose for feathersjs 5

- controllers/login.js
> BC-6097 - fix filter when school has no system

- controllers/courses.js
add query parameter
https://ticketsystem.dbildungscloud.de/browse/N21-1623
https://github.com/hpi-schul-cloud/schulcloud-server/pull/4659
https://github.com/hpi-schul-cloud/nuxt-client/pull/2967
> N21-1623 fix class visibility

- ansible/roles/schulcloud-client-core/templates/deployment.yml.j2
/login waas chosen because on THR, the / redirects to TSP
this will ensure K8 probes pass through the client application, so that no downtime happens. Also, in cause of trouble, would the pod restart should work better, etc
BC-6292
> BC-6292 - change K8 probe

- package-lock.json
Updated follow-redirects from 1.15.2 to 1.15.5
https://ticketsystem.dbildungscloud.de/browse/BC-6213
> BC-6213-Updated follow-redirects from version: 1.15.2  to 1.15.5

- app.js
https://ticketsystem.dbildungscloud.de/browse/BC-6318
https://github.com/hpi-schul-cloud/schulcloud-server/pull/4708
> BC-6318 Register error event handler for redis client

- controllers/administration.js
- views/administration/dashboard.hbs
Hides migration button on administration dashboard if instance is nbc
https://ticketsystem.dbildungscloud.de/browse/N21-1624
> N21-1624 migration wizard

- controllers/courses.js
- views/courses/edit-course.hbs
a list of groups and classes were saved on the global level of the controller to remember data over multiple endpoints
https://ticketsystem.dbildungscloud.de/browse/N21-1706
https://github.com/hpi-schul-cloud/schulcloud-server/pull/4728
> N21-1706 Fix concurrency bug for classes when saving a course

- config/documents.js
- controllers/dataprivacy.js
- controllers/termsofuse.js
- locales/en.json
- locales/es.json
- locales/uk.json
- views/administration/classes_skipregistration.hbs
- views/registration/forms/einwilligungserklaerung.hbs
Old (invalid) documents for privacy and terms of use during registration process. 
BC-6258
- replace old document links with behaviour for recent links
- remove unused legacy code for old privacy and terms of use links (follow up for vue client)
> BC-6258 - Documents in the registration process are outdated for external experts

- controllers/courses.js
- views/courses/edit-course.hbs
https://ticketsystem.dbildungscloud.de/browse/N21-1767
https://github.com/hpi-schul-cloud/schulcloud-server/pull/4812
> N21-1767 configure synced course

- static/styles/lib/bootstrap/scss/_custom.scss
- static/styles/lib/bootstrap/scss/utilities/_background.scss
- static/styles/lib/bootstrap/scss/utilities/_text.scss
> BC-6972 - adjust css for alert info

- views/courses/create-course.hbs
- views/courses/edit-course.hbs
- https://ticketsystem.dbildungscloud.de/browse/N21-1862
- https://github.com/hpi-schul-cloud/e2e-system-tests/pull/193
- https://github.com/hpi-schul-cloud/nuxt-client/pull/3223
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/4966
> N21-1862 add data-testids

- controllers/courses.js
- https://ticketsystem.dbildungscloud.de/browse/BC-7281
> BC-7281 - fix redirection to a non-existent page

- locales/de.json
- locales/en.json
- locales/es.json
- locales/uk.json
To provide further information for our users (teachers and admins) we want to display the blue status bar again.
Visibility should be set for admins and teachers only.
BC-6916
https://github.com/hpi-schul-cloud/dof_app_deploy/pull/882
> BC-6916 - SJW display blue status bar (dBC, NBC, TSC)

- helpers/files-storage.js
- static/scripts/ckeditor/plugins/ckeditor5-filebrowser/src/file-browser-helper.js
- static/scripts/files-storage.js
- static/scripts/helpers/storage.js
- https://ticketsystem.dbildungscloud.de/browse/N21-1967
- https://github.com/hpi-schul-cloud/nuxt-client/pull/3280
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/5051
> N21-1967 Adjust Filestorage for instance files

- helpers/handlebars/middleware.js
The sidebar menu item "Trainings" was taken out and needs to be added back.
BC-7510
https://github.com/hpi-schul-cloud/nuxt-client/pull/3292
> BC-7510 - Add Training Link to Sidebar

- views/lib/topbar.hbs
The user menu button in the legacy client has a duplicated data-testid, one of which needs to be removed.
https://ticketsystem.dbildungscloud.de/browse/BC-7523
> BC-7523- remove duplicated data-testid

- static/styles/lib/sidebar.scss
Fixing last styling issues
BC-6930
- fixing spacing on windows devices below "System" in sidebar
> BC-6930 - Fixing last styling issues

- controllers/users.js
- locales/de.json
- locales/en.json
- locales/es.json
- locales/uk.json
- static/scripts/teamMembers.js
- views/teams/forms/form-invite-external-member.hbs
- https://ticketsystem.dbildungscloud.de/browse/N21-2057
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/5114
> N21-2057 Team invitations with duplicate emails

- config/default.schema.json
- helpers/handlebars/middleware.js
- static/scripts/loggedin.js
- static/styles/lib/loggedin.scss
- views/lib/loggedin.hbs
Remove old layout code(sidebar, topbar). Remove usage of feature flag `FEATURE_NEW_LAYOUT_ENABLED`
BC-7492
> BC-7492 - remove old layout

- static/scripts/loggedin.js
https://ticketsystem.dbildungscloud.de/browse/BC-7636
https://github.com/hpi-schul-cloud/nuxt-client/pull/3337
> BC-7636- Keyboard navigation in hidden sidebar

- config/default.schema.json
- locales/de.json
- locales/en.json
- locales/es.json
- locales/uk.json
- static/styles/dashboard/dashboard.scss
- views/dashboard/dashboard.hbs
Since school starts again on 02.09., please rollout with the release 32.42 (21.08.24).
Dashboard banner for BRB regarding betttermarks, only for teacher and admins.
BC-7480
https://github.com/hpi-schul-cloud/dof_app_deploy/pull/927
> BC-7480 - Display Dashboard banner SC BB: Bettermarks and course overview

- theme/thr/views/lib/header.hbs
- views/lib/sidebar.hbs
- views/lib/topbar.hbs
BC-7826
https://github.com/hpi-schul-cloud/nuxt-client/pull/3359
> BC-7826 - fix logo redirect on THR

- views/calendar/calendar.hbs
> BC-7815 - Add datatestid to delete button

- .github/workflows/push.yml
https://ticketsystem.dbildungscloud.de/browse/BC-7913
removed Selenium test code from push.yml
> BC-7913 removed selenium test from push.yml

- controllers/administration.js
- views/administration/classes.hbs
- views/administration/forms/form-classes-edit.hbs
- views/administration/forms/form-classes-manage.hbs
- views/lib/components/table.hbs
BC-7824
- Added the data-testids on the class related page elements.
> BC-7824 add data testid for classes

- locales/de.json
- locales/en.json
- locales/es.json
- locales/uk.json
- theme/brb/views/authentication/home.hbs
- https://ticketsystem.dbildungscloud.de/browse/BC-7724
> BC-7724 - Update Landing-Page with Phone Number 

- controllers/courses.js
- https://ticketsystem.dbildungscloud.de/browse/N21-2180
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/5233
- https://github.com/hpi-schul-cloud/nuxt-client/pull/3400
> N21-2180 Fix date for synchronized courses

- controllers/administration.js
- https://ticketsystem.dbildungscloud.de/browse/BC-8120 
> BC-8120 - fix error logging in userIdToAccountIdUpdate function

- ansible/roles/schulcloud-client-core/templates/deployment.yml.j2
Add annotations to the kubernetes deployments so that they cann automaticly restart by the stakater reloader if configmaps or secrets change 
- hpi-schul-cloud/schulcloud-server#5265
- hpi-schul-cloud/dof_app_deploy#981
- hpi-schul-cloud/nuxt-client#3413
- hpi-schul-cloud/superhero-dashboard#267
- hpi-schul-cloud/shd-client#21
- hpi-schul-cloud/antivirus_check_service#64
- hpi-schul-cloud/schulcloud-calendar#164
- hpi-schul-cloud/version-aggregator#23
- hpi-schul-cloud/h5p-staticfiles-server#12
- hpi-schul-cloud/tldraw-server#20
- hpi-schul-cloud/tldraw-client#100
- https://ticketsystem.dbildungscloud.de/browse/BC-5112
>  BC-5112 - add Annotations to deployment for Restart

- controllers/login.js
- https://ticketsystem.dbildungscloud.de/browse/N21-2200
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/5278
> N21-2200 Move logout to nest

- theme/brb/style.scss
- theme/thr/style.scss
- https://ticketsystem.dbildungscloud.de/browse/BC-7832
- https://github.com/hpi-schul-cloud/schulcloud-client/pull/3537
- https://github.com/hpi-schul-cloud/nuxt-client/pull/3440
> BC-7832 Change brb primary color.

- locales/de.json
- locales/en.json
- locales/es.json
- locales/uk.json
- https://ticketsystem.dbildungscloud.de/browse/BC-8322
- https://github.com/hpi-schul-cloud/dof_app_deploy/pull/1040
> BC-8322 - Remove Information about User Survey 2024

- helpers/contactHelper.js
- locales/de.json
- locales/en.json
- locales/es.json
- locales/uk.json
SVS contact form
- adapt text and options
- replace support mail adresses for nbc
BC-8608
https://github.com/hpi-schul-cloud/dof_app_deploy/pull/1080
> BC-8608  - Adjust Feedback/ Contact form

- ansible/roles/schulcloud-client-core/templates/deployment.yml.j2
- https://ticketsystem.dbildungscloud.de/browse/BC-8876
- hpi-schul-cloud/dof_app_deploy#1100
- hpi-schul-cloud/schulcloud-server#5475
- hpi-schul-cloud/schulcloud-calendar#170
- hpi-schul-cloud/tldraw-server#52
- hpi-schul-cloud/antivirus_check_service#70
- hpi-schul-cloud/nuxt-client#3530
- hpi-schul-cloud/superhero-dashboard#277
- hpi-schul-cloud/version-aggregator#28
- hpi-schul-cloud/tldraw-client#123
- hpi-schul-cloud/h5p-staticfiles-server#17
- hpi-schul-cloud/shd-client#40
> BC-8876 - add os to the pod template from the deployment

- controllers/oauth2.js
- https://ticketsystem.dbildungscloud.de/browse/N21-2400
> N21-2400 Fix OAuth2 tool login

- package.json
use watch or start instead
https://ticketsystem.dbildungscloud.de/browse/BC-9240
> BC-9240 removed dysfunction task (dev)

- controllers/login.js
- helpers/authentication.js
- views/authentication/forms/login.hbs
- https://ticketsystem.dbildungscloud.de/browse/N21-2456
> N21-2456 Add login_hint for oauth2 login

- controllers/courses.js
- views/courses/edit-course.hbs
Archived courses cannot be retrieved.
Wrong redirect after course deletion.
BC-9246
https://github.com/hpi-schul-cloud/dof_app_deploy/pull/1134
https://github.com/hpi-schul-cloud/nuxt-client/pull/3620
- allow separate post for unarchiving courses
- removing deprecated `rooms-list` route
> BC-9246 - Archived courses cannot be retrieved

- static/scripts/topicEdit.js
- https://ticketsystem.dbildungscloud.de/browse/N21-2494
- https://github.com/hpi-schul-cloud/nuxt-client/pull/3653
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/5654
> N21-2493 Create H5P content in board

- controllers/administration.js
- controllers/helpdesk.js
https://ticketsystem.dbildungscloud.de/browse/BC-9681
> BC-9681 remove unnecessary context-less log message

- static/scripts/topicEdit.js
- views/topic/components/content-H5P.hbs
- https://ticketsystem.dbildungscloud.de/browse/N21-2497
- https://github.com/hpi-schul-cloud/nuxt-client/pull/3684
> N21-2497 Play H5P content in board

- static/scripts/coursesOverview.js
What is required here is to let the frontend (nuxt-client) use the CC-import not the schulcloud import.
https://ticketsystem.dbildungscloud.de/browse/EW-1215
https://github.com/hpi-schul-cloud/schulcloud-server/pull/5698
https://github.com/hpi-schul-cloud/nuxt-client/pull/3696
Change here is only in the endpoint of import
> EW-1215: changing course import endpoint to utilize CC-import

- controllers/login.js
> N21-2441 test redirect

- views/account/settings.hbs
Adding test id for cypress tests.
BC-9414
https://github.com/hpi-schul-cloud/e2e-system-tests/pull/348
> BC-9414 - Cypress Tests SÜA F3

- static/scripts/login.js
> BC-9532 - Login on CSV school not possible if user selects&deselects a school from the list

- config/default.schema.json
- config/development.json
- helpers/handlebars/middleware.js
- views/account/settings.hbs
BC-9793
Vue: https://github.com/hpi-schul-cloud/nuxt-client/pull/3736
Dof: https://github.com/hpi-schul-cloud/dof_app_deploy/pull/1185
> BC-9793 - add sidebar link to rooms for SuS

- static/scripts/course.js
- static/scripts/courses.js
> BC-10303 - fix validation for teacher

- controllers/files.js
Uploading files (= image, audio, video) does not work in CK Editor anymore when trying to embed those into texts of tasks or topics.
BC-10309
https://github.com/hpi-schul-cloud/file-storage/pull/60
> BC-10309 - fix ck5 file uploads

- views/lib/topbar.hbs
> BC-7846 - Align QR code dropdown menu to the right
