hpi-schul-cloud/schulcloud-client

- controllers/files.js
- static/scripts/files.js
- views/files/files.hbs
- views/files/forms/form-share-file.hbs
First merge [Server-PR](https://github.com/schul-cloud/schulcloud-server/pull/174)
Simple way for sharing files. Creates a tiny-link, with which other users can create a permission for the give file. More logic (like read-write permissions, disable sharing, show all shared files in a folder etc.) will be implemented later on.
> 552 evaluate file sharing

- static/styles/content/content.scss
- views/content/item.hbs
#484 
if logged in as teacher there is a + symbol to add the content to a course right next to the report link. how should I fix this layout problem? center the +?
> add mailto link for reporting external content

- helpers/googleAnalytics.js
If a request results in an error page, it is sent as exception hit to Google Analytics.
> Send exception hits for error pages.

- controllers/content.js
- views/content/search-results.hbs
Only works with schulcloud-content branch [fix-search-pagination](https://github.com/schul-cloud/schulcloud-content/tree/fix-search-pagination)
> Fix search pagination, use $limit & $skip

- app.js
Since the client is behind a load balancer, the ip of the request is not the one of the user. By enabling the `trust proxy` config option, the user ip is extracted from the `X-Forwarded-For` header instead.
This is needed for the google analytics tracking.
> Enable trust proxy config.

- .travis.yml
the backend url is set in the envs of travis itself.
- Changed the BACKEND_URL to a different backend in Travis.
> Remove BACKEND_URL from .travis

- controllers/files.js
- static/scripts/files.js
- static/scripts/homework.js
- views/files/files-grid.hbs
- views/homework/components/submission_uploaded_files.hbs
Scheinbar ist es neuerdings so, dass der `xmlhttprequest` Probleme macht, wenn umlaute in den Dateinnamen sind. Das wird durch diesen PR behoben.
[Server-PR](https://github.com/schul-cloud/schulcloud-server/pull/295)
> SC-116  ~ Umlaute erlauben File Upload

- controllers/files.js
- views/files/files.hbs
Latest PR #644 reveals in a new bug that prevents deleting course-folders. This PR is fixing it.
fixes SC-162
> Bugfix for deleting course-folders

- controllers/topics.js
On any patch request to a topic, the server checks if the course in the request matches any course of the teacher who made the request.
However, if someone tries to make a topic invisible, no courseId is added to the request, therefore that check always fails, and the server denies any attempt to do so.
This is one way to fix it, and im pretty sure it has no unwanted side effects, but someone should definetly check.
According to my testing the same applies to changes in the ordering of topics, but this change is not enough to fix that as well.
> add courseId to request to pass ownership check on server

- controllers/homework.js
For private assignments (homework), we're allowing to **not** specify a course ("Keine Zuordnung"). In this case `courseGroups` is `undefined` and we're getting an error when accessing ```.data```. This PR fixes this with ```(courseGroups || {}).data```.
> also allow coursegroups to be undefined

- helpers/handlebars/helpers/index.js
- package.json
- views/files/files-overview.hbs
- views/lib/components/sc-card.hbs
render secondary title again, stripping caused newlines to disappear entirely.
As they aren't written in html we couldn't preserve them.
Solution: strip only script tags and style tags.
Only user field is Room, rest is client side
> SecondaryTitle - SC_Card - fix

- gulpfile.js
Problem, dass N21 keine Bilder anzeigt: Problem liegt darin, dass wir Docker nutzen und Docker fürs theming nicht nochmal komplett gulp laufen lässt sondern eben nur `build-theme-files` und da dort nur `styles` als nochmal zu bauen angegeben wurde `images` komplett fehlte.
> N21 image fix

- static/styles/lib/colors.scss
- static/styles/lib/loggedin.scss
- theme/default/style.scss
new color layout sidenav for desktop and mobile
first reorganisation of a centralised stylesheet for colors
> F navigation redesign

- static/scripts/coursesTimes.js
- static/scripts/jquery/datetimepicker-easy.js
- views/courses/edit-course.hbs
https://ticketsystem.schul-cloud.org/browse/SC-512
Removed code from coursesTimes.js (saw no reason for being there)
--> in datetimepicker-easy.js locale and input patterns are already set:
```javascript
$.datetimepicker.setLocale('de');
document.querySelectorAll('input[data-date], input[data-datetime]').forEach((input)=>{
$(input).datetimepicker(readPickerConfig(input));
input.setAttribute("autocomplete","off");
// modified regex from: https://www.regextester.com/97612
let pattern =`(3[01]|[12][0-9]|0?[1-9])\\.(1[012]|0?[1-9])\\.((?:19|20)[0-9]{2})`;
if(input.dataset.datetime !== undefined){ pattern += `[[:space:]][0-2][0-3]:[0-5][0-9]`; }
input.setAttribute("pattern", pattern);
});
```
feedback required
> removed buggy code

- views/topic/topic.hbs
don't know why this was changed from /courses to /{{context}} but reverting fixes the problem. maybe check if {{context}} was needed for something else?
> fix topic edit button link

- controllers/administration.js
Schüler-/Lehrerverwaltung war nicht aufrufbar, wenn kein Schüler oder kein Lehrer an der Schule existierte. Das Problembild, dass ein Consent eines nicht mehr existierenden Users Probleme macht, kann eigentlich nicht auftreten. Es werden nur die Consents der User abgefragt, die in dieser Liste stehen. Gelöschte Nutzer stehen nicht mehr in der Nutzerliste, daher auch keine Abfrage auf diese ID. Somit wird es Consentleichen bei gelöschten Nutzern geben aber sie betreffen nicht das Problem der defekten Nutzerverwaltung.
> Hs/fix broken user mgmt if no students/teachers in school

- static/styles/calendar/calendar.scss
> calendar:removed event top-bottom borders, and half hour grid

- controllers/administration.js
- controllers/teams.js
https://ticketsystem.schul-cloud.org/browse/HEL-253
Es gab Limits, die jetzt erstmals an einer N21 Schule mit mehr als 1000 Schülern dazu führte, dass an verschiedenen Stellen nicht alle Nutzer/Schüler angezeigt wurden.
Entfernt bei:
Verwaltung -> Klassen -> Klasse verwalten (Schülerliste)
Verwaltung -> Schüler -> der Text unten "4471 von 4473 Schüler in deiner Klasse benötigen noch die Einverständniserklärung ..." war vorher capped auf 1000 und daher "998 von 4473 Schüler ..." ([HEL-251](https://ticketsystem.schul-cloud.org/browse/HEL-251))
Teams -> Team -> Teilnehmer-Übersicht -> Interne Teilnehmer hinzufügen (Schülerliste)
Wenn ihr eure Datenbank mit ein paar Tausend Nutzer füllen wollt, siehe [DB-Skripte](https://docs.schul-cloud.org/display/Intern/Datenbank-Skripte)
[Allgemeine …
> HEL-253 Limits an verschiedenen Stellen entfernen

- views/dashboard/components/card_section.hbs
fixes a bug where the attribute `data-id` in the sc-card.hbs was wrapper inside `data-rss`
> add missing quotes for card data-rss

- static/.well-known/assetlinks.json
**Issue:** [AN-62: Link autofill with website](https://ticketsystem.schul-cloud.org/browse/AN-62)
Android 8.0 and later enables autofill providers to use credentials stored for schul-cloud.org for our Android app as well. This requires the added file to be present at <https://schul-cloud.org/.well-known/assetlinks.json>. Is it enough to just add it to the `./static` folder?
For more information see the [Google Developers guide](https://developers.google.com/identity/smartlock-passwords/android/associate-apps-and-sites#associate_your_app_with_your_website) and the corresponding PR on schul-cloud/schulcloud-mobile-android#159
> AN-62: Link autofill with website

- static/scripts/files.js
Kein Ticket. Das Problem betraf PDF Dateien, die nicht mehr geöffnet werden konnten.
> Fix download problem of pdf files

- static/scripts/homework.js
- views/homework/submission.hbs
[SC-1018](https://ticketsystem.schul-cloud.org/browse/SC-1018)
Umsetzung:
Wenn der Editor keinen Inhalt (außer Whitespaces) enthält, ist der "Speichern"-Button deaktiviert:
Sobald Inhalt eingegeben wurde, wird der "Speichern"-Button aktiviert:
- Begründung:
- Code
Weitere Informationen zur DoD [hier im Confluence](https://docs.schul-cloud.org/pages/viewpage.action …
> SC-1018-reject-empty-submissions

- controllers/courses.js
[SC-1244](https://ticketsystem.schul-cloud.org/browse/SC-1244)
Beim Menü zur Kurserstellung wird der aktuelle Nutzer nun aus der Liste der möglichen Vertretungslehrer herausgefiltert, sodass sich er sich nicht mehr als selbst als Vertretung hinzufügen kann:
- Begründung:
- Code
Weitere Informationen zur DoD [hier im …
> SC-1244-teacher-and-substitution-of-course-should-be-different

- controllers/registration.js
Formularfelder wurden beim Ausfüllen durch Eltern (Registration unter 16) nicht korrekt erkannt und der Consent mit falses abgespeichert. Dadurch wurde im Firstlogin nochmal nach Elternconsents gefragt.
Server-PR: https://github.com/schul-cloud/schulcloud-server/pull/602
- https://github.com/schul-cloud/schulcloud-server/pull/602
> Hotfix/SC-1306 Fix too long firstlogin

- controllers/administration.js
- views/administration/teams.hbs
Change logic to set student creation on team in administration settings
- Begründung:
- Code
> SC-1480 - Fix merging issue for SC-1341 and SC-1469 Administration Logic

- controllers/teams.js
- views/teams/members.hbs
Ticket: https://ticketsystem.schul-cloud.org/browse/SC-811
Server-PR: https://github.com/schul-cloud/schulcloud-server/pull/665
Überprüft die im Server-PR eingeführte Berechtigung beim Rendering der Team-Mitglieder-verwalten-Seite und entfernt den entsprechenden Button und das Modal.
Läuft auch ohne Server-PR, allerdings kann dann niemand mehr externe Mitglieder einladen :-)
> SC-811 Check new TEAM_INVITE_EXTERNAL permission

- controllers/teams.js
- static/scripts/calendar.js
- static/scripts/teams.js
- views/calendar/calendar.hbs
- views/calendar/card.hbs
- views/teams/team.hbs
Ticket: https://ticketsystem.schul-cloud.org/browse/SC-1327
Server-PR: https://github.com/schul-cloud/schulcloud-server/pull/661
Migrationen: siehe Server-PR
Mit diesen Änderungen werden Team-Event-Edits bzw. Deletes nur noch zugelassen, wenn entsprechende Team-Permissions vorhanden sind. Gleiches gilt (wie gehabt) für die Erstellung von Team-Events. Bisher sind das nur UI-Changes; ein größerer API-Rewrite steht noch aus (Folgeticket siehe Server-PR).
> SC-1327 team calendar permissions

- webpack.config.js
- Fixt einen Bug im Webpack Script Cache Plugin, wodurch beim deployment die scripts nicht gebuilded wurden. Das Problem tritt vereinzelt auf, wenn es noch keinen cache (gulp und plugin cachefiles) und build ordner gibt. Im Plugin sekbst konnte ich keinen offensichtlichen Bug finden, aber das Plugin zu deaktiveren hat lokal bei mir geholfen. In Production benötigen wir sowieso kein caching.
> Update webpack.config.js build cache bug

- views/homework/extended.hbs
- views/homework/submission.hbs
Es wurde HOMEWORK_CREATE statt SUBMISSION_CREATE benutzt und Studenten konnten deswegen keine Hausaufgaben mehr abgeben.
Die Seed Daten sind soweit korrekt, allerdings enthalten die Datenbanken der verschiedenen Instanzen vermutlich noch alte Stände in der roles Collection.
> SC-1663 fix wrong permissions to fix student submissions

- controllers/teams.js
- ~~[ ] Links zu verwandten PRs anderer Repositories~~
- Begründung:
- Code
> SC-1720 fix teammembers error (federalstate of undefined)

- controllers/administration.js
Fix a bug that resulted in a 504 if there are classes without a year
> Don't break if class has no year set

- .travis.yml
- simplify travis.yml by using jobs and moving the integration-test setup [into a gist](https://gist.github.com/schul-cloud-bot/a849c38804174f99ca7818782bf03c00).
- add nuxt to the integration test setup
```bash
curl https://gist.githubusercontent.com/schul-cloud-bot/a849c38804174f99ca7818782bf03c00/raw/index.sh > integration-test.sh
chmod 700 integration-test.sh
bash integration-test.sh
```
related pulls:
- required to be merged at the same time
- https://github.com/schul-cloud/docker-compose/pull/5
- https://github.com/schul-cloud/nuxt-client/pull/314
- optional, can also be merged later
- https://github.com/schul-cloud/schulcloud-client/pull/1457
- https://github.com/schul-cloud/integration-tests/pull/31
> integrate the nuxt client into the integration-test workflow

- controllers/homework.js
fixes different behaviour with homeworks:
- homework created inside a course for a course
- homework created inside a course without course reference
- homework created from homeworks overview
- homework submission contains just a file not text
https://ticketsystem.schul-cloud.org/browse/SC-1253
https://ticketsystem.schul-cloud.org/browse/SC-2064
> SC-1253 SC-2064 fix homework create handling

- package-lock.json
- static/scripts/dataprivacy/paginated_form.js
The UX is also getting improved by this, because the Element.scrollTo is kind of broken because of out fixed positioned topbar that lays above everything.
With window.scrollTo this is not relevant anymore.
> SC-2622 - use window.scrollTo instead of Element.scrollTo

- .travis.yml
- added an option to skip the test stage for really urgant changes that need to be deployed fast. Just **add `skip-test-stage` to your commit message**
- only works if the pull targets the master branch
- it's not possible to change the order of the stages using this approach, because I am only allowed to define each stage name once (in line 19-22) and travis will ignore the second definition + conditions. So in order to execute the tests afterwards you need another commit (where you **add `skip-deploy-stage` to the commit message** )
- serverPR: https://github.com/schul-cloud/schulcloud-server/pull/872
> allow to skip travis stages

- views/authentication/forms/login.hbs
- save password still works, so you don't loose any comfort
- the username/email does not get suggested on shared devices (on all devices)
> SC-2780 - disable autocomplete on login form

- theme/n21/views/help/help.hbs
Help page now only contains a confluence search bar and contact form, nothing more. Confluence page is still the official N21 help page.
Ticket: https://ticketsystem.schul-cloud.org/browse/SC-2854
> SC-2854 quick hotfix n21 help page contact form

- views/about/about.hbs
School logos for "Mai 2018" was broken by another change, fixed that.
> hotfix about page school listing

- controllers/tools.js
- views/courses/components/run-lti-frame.hbs
Kleiner Fix, damit die OAuth-Signatur für LTI1.1 übereinstimmt. Der CSRF-Token wird nur dem Formular hinzugefügt, wenn es sich um LTI1.3 handelt, um dort Deep-Linking-Antworten zu handeln.
> use csrf token only in LTI1.3

- gulpfile.js
- static/scripts/base.js
- static/scripts/dataprivacy/pin_input.js
- static/scripts/helpers/inputFromQuery.js
This should fix a lot of compatibility errors  from sentry and definetly should not hurt:
- https://sentry.schul-cloud.dev/schul-cloud/schul-cloud-client/issues/361
by simply adapting our build pipeline to output more compatible code:
- old: https://browserl.ist/?q=%3E+1%25%2C+not+dead
- new: https://browserl.ist/?q=%3E+0.2%25%2C+last+9+version%2C+not+dead
> update browserlist supported ranges

- config/default.schema.json
- package-lock.json
- package.json
- static/scripts/helpers/storage.js
- static/scripts/login.js
- views/authentication/forms/login.hbs
- add check for blocked cookies and show info how to resolve
- make localStorage safe to access if storage is blocked (happens when cookies are blocked), otherwise the script failed to execute and the error for blocked cookies couldn't be shown.
https://michalzalecki.com/why-using-localStorage-directly-is-a-bad-idea/
> hotfix - show info if cookies are blocked

- .dockerignore
adds the .gulp-changed-smart.json filepath into .dockerignore file to avoid caching issues 
@adrianjost it's not planned to copy precreated files into the docker containers, right? 
> SC-3472 extend dockerignore

- CHANGELOG.md
- views/courses/create-course.hbs
- SC-3785: link to course after course creation corrected
> SC-3785 link to course after course creation corrected

- static/scripts/chatLoggedin.js
- static/styles/lib/chatLoggedin.scss
The chat currently tries to enter the wrong chat rooms based on the course url, eg. on https://test.schul-cloud.org/courses/5e8ae0eec39059002b3b7e7a because the matrix server name was hardcoded.
This fix extracts the servername vom the matrix-userId instead.
> fix(messenger): change chat window based on course url

- .eslintrc.json
- CHANGELOG.md
- package-lock.json
- package.json
My IDE and `npm run lint` suggest to: Arrow functions can omit parentheses when they have exactly one parameter.
But on Codacy an error is reported when the are removed. My changes align the eslint config with the codacy handling.
eslint rule:
https://eslint.org/docs/rules/arrow-parens#requireforblockbody
> Fix: adjust eslint config to match CI

- .mergify.yml
Use mergifys smart merge strategy to save some CI execution time.
The smart merge mode will queue all prs to be merged and will only update one by on, so there will never be two PRs that compete against each other which would get merged first.
Documentation:
https://doc.mergify.io/actions.html#merge
> use smart merge strategy

- static/scripts/chatLoggedout.js
`window.indexedDB.databases()` was used to retrieve the active databases. But the function is not available in all browsers: https://developer.mozilla.org/en-US/docs/Web/API/IDBFactory/databases
Therefor it replaced with a hardcoded list of IndexedDB database names used by the embedded messenger client.
ensures that user related data is deleted on logout
> Fix: delete indexedDB databases in all browsers

- controllers/help.js
- views/help/partials/help_nutzungshilfen.hbs
simple wording change, rename "Lern-Nuggets" to "Datenschutzkurs", requested by Sophie Plötz via RC, so there is no ticket.
I would leave the URL as is so that we dont need to set up a redirection and it should fine to leave it.
> hs/rename Lern-Nuggets

- config/default.schema.json
- views/administration/school.hbs
- views/courses/edit-course.hbs
- views/teams/edit-team.hbs
To allow a manuell rollout and onboarding of individual schools the settings to activate the messenger should be hidden in the UI until we set a feature flag.
https://ticketsystem.schul-cloud.org/browse/SC-4328
- add feature flag
no changes
New feature flag `FEATURE_MESSENGER_SCHOOL_SETTINGS_VISIBLE` should stay disabled for now.
no changes
no changes
> SC-4328: add flag to hide school messenger settings

- static/vendor/ckeditor/config.js
Stopped Border deletion inside of CKEditor.
- https://ticketsystem.schul-cloud.org/browse/SC-4653
This PR will restore borders inside of the CKEditor.
Only CSS-Changes, should be not security relevant
No extra ENV.
No REPOs, no NPM-Dependencies
> commented deletion of borders out; does it have any sideeffects?

- views/registration/pin.hbs
- views/registration/registration-employee.hbs
- views/registration/registration-parent.hbs
- views/registration/registration-student.hbs
https://ticketsystem.schul-cloud.org/browse/SC-4931
The CSS for the inputs of the PIN in registration were missing. With this fix it looks exactly as before the CSP changes.
> SC-4931 Fix Styling of PIN inputs in registration

- locales/de.json
I have tried on master, develop, on staging and niedersachsen. On every page there is button Verwaltung for teacher.
This button is missing on schul-cloud.org because it has another release version than others (https://dashboard.schul-cloud.dev/#/home/dashboard)
So button is there, but schulcloud.org needs to be upgraded to new version.
- https://ticketsystem.schul-cloud.org/browse/SC-5206
Changed name of button Verwaltung to Verwaltungsbereich
> SC-5206 - change-button-name

- static/scripts/i18n.js
Ticket: https://ticketsystem.schul-cloud.org/browse/SC-5262
i18n-initialization is sometimes slower than loading the page content (for example in static scripts), which results in only displaying the keys. With this PR I've added the option `initImmediate: false`. This is responsible for initializing i18n synchronously and therefore avoid the bug.
> i18n SC-5262 Bugfix: content sometimes loads before initialization

- locales/de.json
- static/scripts/base.js
- views/courses/components/tools.hbs
- views/courses/forms/form-tools.hbs
If configured in SHD tools should be opened directly in a new tab.
https://ticketsystem.schul-cloud.org/browse/SC-5289
Requires: https://github.com/schul-cloud/schulcloud-server/pull/1475
Add hint to affected tools and directly show frame content when opening the tool in course section.
Not relevant.
-
-
> Feature/SC-5289 Open tools in new tab if set

- views/administration/school.hbs
Hide messenger options only using css but keep them in the DOM to send the form data back to the server.
- https://ticketsystem.schul-cloud.org/browse/SC-5926
- elements are still in the dom and information is send back to the server on submit
- no changes
- -
- -
- - 
> SC-5926: hide messenger options only using css

- controllers/teams.js
- locales/de.json
- views/lib/loggedin.hbs
The criteria to show the notification messages in teams have to be based on the school settings of the different users participating in a team. The previous implementation was based on unrelated flags which resulted in notifications even when only users of one school are in a team and the bidirectional chat is disabled.
- https://ticketsystem.schul-cloud.org/browse/SC-5927
- fix criteria
- add message why the team has no messenger for users which are used to use the messenger in their schools
- -
- -
- -
> SC-5927: Only show team messenger notification if the criteria are met

- views/lib/components/sc-card.hbs
original problem of ticket was not present on develop, but I found one another bug, there was always simple end quote at the end of text in sc-card footer 
this bug is fixed here and also aria label
- https://ticketsystem.schul-cloud.org/browse/SC-6552
> SC-6552 - quote at end of footer in sc-card is deleted

- views/lib/components/sc-card.hbs
- views/lib/forms/paginatedForm.hbs
deleted name of card in sc-card footer,
fixed i18n missing in paginatedForm.hbs
- https://ticketsystem.schul-cloud.org/browse/SC-6800
> SC-6800 - deleted name in sc-card next to open text

- CHANGELOG.md
- package-lock.json
- package.json
- views/firstLogin/firstLogin.hbs
- views/firstLogin/sections/pin.hbs
When parent consent is not given, the first login wizzard takes the user to parent consent. The consent is confirmed via a PIN sent to parent email. This was not working, giving a an error about missing importHash.
Furthermore, missing css made the pin entering practically impossible for the user. 
There is a second case, when the account is via LDAP, but this case is not covered here.
- https://ticketsystem.hpi-schul-cloud.org/browse/SC-7085
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/1837
> SC-7085 - fixes parent consent pin request

- CHANGELOG.md
- controllers/schools.js
- locales/de.json
- locales/en.json
- views/administration/school.hbs
Creates input to type the school id in the school administration for users who have admin permissions.
https://github.com/hpi-schul-cloud/schulcloud-server/pull/1833
https://ticketsystem.hpi-schul-cloud.org/browse/SC-7083
Adds school id input text input to type the school id in the school administration view.
> Feature/SC - 7083 get school id from admin

- CHANGELOG.md
- locales/de.json
- locales/en.json
- views/firstLogin/firstLoginExistingUser.hbs
While first login there was no max option shown for the second age range for users with existing account but missing birthday and consent. Also the grammar was not always clear for the range of ages during registration or first login.
https://ticketsystem.hpi-schul-cloud.org/browse/SC-7589
- fix code for correct age range
- change sentence structure in de and en for clearance
No data security topics.
> Show correct age options while registration

- CHANGELOG.md
- static/scripts/calendar.js
Note:
I have checked the calendar event generation for teams and courses. But it will work like this:
1. You create or edit a event and select a course
2. The course will be assigned to this event
3. You edit this course event
4. The course name will appear in the title
5. the course and team selection is removed. Removed for the rest of the calendar session
=> You can't switch to another course
1. You create or edit a event and select a team
2. The team will be assigned to this event
3. You edit this team event
4. You will be immediately redirected to the teams page on tab events
=> You can't switch to another team
https://ticketsystem.hpi-schul-cloud.org/browse/SC-7453
More and detailed …
> SC-7453 - course team display fix

- CHANGELOG.md
- locales/de.json
- locales/en.json
- views/account/settings.hbs
- views/account/teams.hbs
missing word on account page
- https://ticketsystem.schul-cloud.org/browse/SC-5498
> SC-5498 - fixed a source for shortTitle of instance

- CHANGELOG.md
- views/courses/create-course.hbs
- views/courses/edit-course.hbs
Editing the teacher of a course suggests adding a student:in in the text field. Only teachers can be selected.
- https://ticketsystem.schul-cloud.org/browse/SC-7771
> SC-7771 - wrong hint for teachers on edit course

- CHANGELOG.md
- views/courses/edit-course.hbs
Editing the teacher of a course suggests adding a student:in in the text field. Only teachers can be selected.
FIX
- https://ticketsystem.schul-cloud.org/browse/SC-7771
> SC-7771 - wrong hint for teachers- fix

- CHANGELOG.md
- controllers/administration.js
- locales/de.json
- locales/en.json
- views/administration/users_registrationcomplete.hbs
Wording verwirrend (!!) - Please change text on one button from "Zurück" to "Fertig"
- https://ticketsystem.schul-cloud.org/browse/SC-6975
changed button text, color and position
> SC-6975 - Fertig button instead of zuruck

- CHANGELOG.md
- views/administration/school.hbs
LDAP schools weren't able to edit the school number field. Now there is no difference between LDAP / non-LDAP schools.
https://ticketsystem.hpi-schul-cloud.org/browse/SC-8414
all schools can edit school number field once
> made school number field editable for ldap schools

- CHANGELOG.md
- theme/brb/views/lib/extended_footer.hbs
- views/lib/extended_footer_links.hbs
Removed the link datenschutzbeauftragter@hpi-schul-cloud.de from the Footer in HPI Schul-Cloud
Schul-Cloud Brandenburg and HPI Schul-Cloud International
- https://ticketsystem.schul-cloud.org/browse/SC-8495
before:
after:
> SC - 8495 remove link from footer

- CHANGELOG.md
- static/styles/courses/course.scss
Course name title has wrong color
https://ticketsystem.hpi-schul-cloud.org/browse/SC-8597
set course name title primary color
before:
after:
> SC-8597 – Course name title has wrong color

- views/courses/course.hbs
- views/lib/components/sc-card.hbs
In the teams and courses cards, the text does't wrap, but rather has an overflow:hidden effect. I added a white-space property to wrap it on the next line.
- https://ticketsystem.schul-cloud.org/browse/SC-8565
before:
after:
> SC - 8565 long text not wrapping

- CHANGELOG.md
- static/styles/courses/course.scss
drag icon on the topic card is not visible; make it visible again
https://ticketsystem.hpi-schul-cloud.org/browse/SC-8594
css - add color: $white
before 
after:
> SC-8594–drag icon on the topic card is not visible

- CHANGELOG.md
- ansible/roles/schulcloud-client/tasks/main.yml
- ansible/roles/schulcloud-client/templates/onepassword.yml.j2
Rename ansible variables for OnePassword
https://ticketsystem.hpi-schul-cloud.org/browse/BC-331
https://ticketsystem.hpi-schul-cloud.org/browse/BC-354
Rename ansible variables for OnePassword
https://github.com/hpi-schul-cloud/dof_app_deploy/actions/runs/1283239384
> BC-331 - BC-354 - rename ansible variables for OnePassword

- views/homework/edit.hbs
there was a bug in the lesson picker of the task edit page, that
prevented the user from assigning no lesson for a task if there was at
least one viable lesson.
ticket https://ticketsystem.hpi-schul-cloud.org/browse/BC-858
> fix assigning no lesson during task edit

- ansible/roles/schulcloud-client-core/tasks/main.yml
Change the mode for the configmaps at the ansible roles to apply for configmaps and secrets
https://ticketsystem.hpi-schul-cloud.org/browse/BC-1230
hpi-schul-cloud/dof_app_deploy#111
hpi-schul-cloud/antivirus_check_service#20
hpi-schul-cloud/superhero-dashboard#157
hpi-schul-cloud/schulcloud-server#3311
hpi-schul-cloud/schulcloud-calendar#109
hpi-schul-cloud/nuxt-client#2040
> BC-1230 - change mode for configmaps to apply

- ansible/group_vars/all/schulcloud-client.yml
- ansible/group_vars/reference/schulcloud-client.yml
Set the ansible variabel SCHULCLOUD_CLIENT_IMAGE will be set default to the schulcloud/schulcloud-client as docker regestry.
It will be overwritten by the value from ansible/group_vars/develop/schulcloud-client.yml for the develop instances
hpi-schul-cloud/schulcloud-server#3321
hpi-schul-cloud/nuxt-client#2051
hpi-schul-cloud/schulcloud-calendar#112
hpi-schul-cloud/superhero-dashboard#161
hpi-schul-cloud/antivirus_check_service#22
https://ticketsystem.hpi-schul-cloud.org/browse/BC-1302
> BC-1302 - set the default docker registry for all, will be overwritten for develop

- package.json
For work on the nexboard-api-js repository the used version is pinned to Version 1.1.2
Later planned to release new versions on https://www.npmjs.com/package/nexboard-api-js
> Pin self developted nexboard-api-js to version 1.1.2

- lint-staged.config.js
After using "git add" and "git commit" the message "some of your tasks use git add command. Please remove it from the config since all modifications made by tasks will be automatically added to the git commit index." is displayed.
Ticket: https://ticketsystem.dbildungscloud.de/browse/BC-1695
Removing 'git add' from the lint-staged.config.js
According to https://github.com/okonet/lint-staged/issues/775 it's not necessary  anymore.
> BC-1695 - Removing 'git add' from lint-staged config

- locales/de.json
- locales/en.json
- locales/es.json
- locales/ua.json
- views/calendar/forms/form-create-event.hbs
As a user I don't want to see the options for courses and teams on creating an appointment inside the calendar, because the creation of course and team-appointments doesn't work from the calendar.
BC-2168
> BC-2168 - Hide dropdowns for course/team in appointment creation

- static/styles/lib/loggedin.scss
Fixes an error with CSS styles. When the user switches tabs in the navigation bar, the tab jumps.  When switching to the courses tab and other navigation tabs, the tabs also jump. Added indents to prevent sidebar jumps when switching navigation tabs.
> BC-2932-Fix sidebar(navigation) jumping

- static/styles/lib/tabbar/tabbar.scss
- views/news/overview.hbs
currently when the news section is opened in mobile, it does not show the two headers (once future news are present) as the icons are not implemented
BC-3072
*Desktop*
*Mobile*
> BC-3072 - News tab headers not showing up in mobile view

- controllers/administration.js
- views/administration/school.hbs
This PR is about hiding the system buttons for admins in the nbc instance. The admin is not allowed to change Systems in the SVS anymore.
https://ticketsystem.dbildungscloud.de/browse/N21-800
https://github.com/hpi-schul-cloud/schulcloud-server/pull/4042
https://github.com/hpi-schul-cloud/nuxt-client/pull/2475
> N21-800-hide-system-buttons

- controllers/dashboard.js
After the fetching of new release notes, a pop-up with animated presents notifies users about the presence of new release notes. This pop-up is missing!
**Reason is**, that currently the _createdAt_ (for determing the newest release) was taken by the most recent merged commit. As for the new repo there are no commits after the initial ones and hence the createdAt value is always the old one and so no new releases are shown. Now the _publishedAt_ date is taken as determing value as this is changed with the new repo everytime a new release is done.
BC-5749
- determine new release by **publishedAt** instead of **createdAt**
> BC-5749 - Missing pop-up for new release notes

- ansible/roles/schulcloud-client-core/templates/deployment.yml.j2
To Improve the distribution of PODs to the least number of kubernetes worker nodes who is Required 
but also to secure that the PODs of one Deployment are distributed over the Fault Zones and Node pools
the pod affinity and anti affinity are set.
**Affernety number calculation:** 
**_Assign Number for an host_** = 0 - 20 X _Fault Zone_  - 10 X _Node Pool_ + 9 X _Host_ 
**_Host_**  = 1 if on the host runs an POD from the Schulcloud-Verbund on any namespace
**_Host_**  = 0 if on the host runs no POD from the Schulcloud-Verbund on any namespace
**_Node Pool_** = 1 if on a host of this node pool runs an POD from the Deployment
**_Node Pool_** = 0 if on no host of this node pool runs an POD from the Deployment
**_Fault Pool_** = 1 if on a host of this fault zone runs an POD from the Deployment …
> BC-5423 - Add POD affinity and anti-affinity

- ansible/roles/schulcloud-client-core/templates/deployment.yml.j2
hopefully this is a workaround for a problem that we can not fully identifiy
we can only pin point it to the k8s probe itself, if it is the k8s version, the affected version would be v1.26.11
to try it out, stop or restart redis, try the probe, it will fail, where the k8s http-get one succeeds
BC-6292
> BC-6292 using wget as the k8s http probes were not failing

- ansible/roles/schulcloud-client-core/templates/deployment.yml.j2
> BC-6303 reduce startupProbe failureThreshold

- .github/workflows/clean.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/dependabot-to-jira.yml
- .github/workflows/dependency-review.yml
- .github/workflows/push.yml
- .github/workflows/tag.yml
https://ticketsystem.dbildungscloud.de/browse/BC-6589
https://github.com/hpi-schul-cloud/schulcloud-server/pull/4771
https://github.com/hpi-schul-cloud/schulcloud-client/pull/3414
https://github.com/hpi-schul-cloud/nuxt-client/pull/3112
https://github.com/hpi-schul-cloud/superhero-dashboard/pull/250
https://github.com/hpi-schul-cloud/schulcloud-calendar/pull/157
https://github.com/hpi-schul-cloud/antivirus_check_service/pull/52
https://github.com/hpi-schul-cloud/version-aggregator/pull/19
https://github.com/hpi-schul-cloud/dof_app_deploy/pull/798
https://github.com/hpi-schul-cloud/h5p-staticfiles-server/pull/9
https://github.com/hpi-schul-cloud/tldraw-client/pull/58
> BC-6589 update gh-actions

- static/scripts/topicEdit.js
H5P-Editor doesn't load with recent changes in the nuxt-client and/or server (dev stage, main).
BC-6752
> BC-6752 - Fix H5P editor loading

- locales/de.json
- locales/en.json
- locales/es.json
- locales/uk.json
- views/dashboard/dashboard.hbs
https://ticketsystem.dbildungscloud.de/browse/BC-6926
> BC-6926 - Change banner text

- .prettierrc.js
- helpers/i18n.js
- helpers/momentHelper.js
- locales/calendar/de.json
- locales/calendar/es.json
- locales/calendar/uk.json
- static/scripts/helpers/AlertMessageController.js
> BC-6672 fix incorrect translation in alert

- config/default.schema.json
- locales/de.json
- locales/en.json
- locales/es.json
- locales/uk.json
- views/lib/loggedin.hbs
Adding translations for online events announcement.
- <https://ticketsystem.dbildungscloud.de/browse/EW-841>
- <https://github.com/hpi-schul-cloud/dof_app_deploy/pull/853>
- Announcement is only active on DBC
**TBD**
> EW-841 Adding translations for online events announcement

- controllers/coursegroups.js
- controllers/courses.js
- controllers/files.js
- controllers/help.js
- controllers/teams.js
- controllers/topics.js
- views/files/files.hbs
- views/lib/loggedin.hbs
https://ticketsystem.dbildungscloud.de/browse/BC-7618
> BC-7618 - Missing breadcrumbs

- .github/workflows/dependabot-to-jira.yml
Fix that the jira ticket for dependabot pr's where wrong, without name and infos
- https://ticketsystem.dbildungscloud.de/browse/BC-7716
> BC-7716 - fix dependabot to jira

- config/default.schema.json
- helpers/handlebars/middleware.js
- theme/thr/views/about/about.hbs
- views/community/community.hbs
- views/firstLogin/components/welcome_greeting.hbs
- views/help/partials/help_nutzungshilfen.hbs
- views/lib/help_menu.hbs
Changing the location of the video training material to a separate federal state location for each state.
For that a new env var `TRAINING_URL` is introduced.
+ editing `ACCESSIBILITY_REPORT_EMAIL` for dBC (currently not visible, just for keeping it up to date)
BC-7700
BC-7701
BC-7702
https://github.com/hpi-schul-cloud/dof_app_deploy/pull/929
https://github.com/hpi-schul-cloud/schulcloud-server/pull/5170
https://github.com/hpi-schul-cloud/nuxt-client/pull/3350
> BC-7700 BC-7701 BC-7702 - replacing LC links on platform

- package-lock.json
- package.json
BC-7842
https://github.com/hpi-schul-cloud/schulcloud-server/pull/5178
> BC-7842 - downgrade npm

- .github/workflows/push.yml
- ansible/roles/schulcloud-client-core/tasks/main.yml
- hpi-schul-cloud/superhero-dashboard#262
- hpi-schul-cloud/dof_app_deploy#936
- hpi-schul-cloud/schulcloud-server#5189
- hpi-schul-cloud/nuxt-client#3365
- hpi-schul-cloud/tldraw-client#80
- hpi-schul-cloud/version-aggregator#21
- hpi-schul-cloud/h5p-staticfiles-server#11
- hpi-schul-cloud/schulcloud-calendar#163
- hpi-schul-cloud/antivirus_check_service#58
- hpi-schul-cloud/shd-client#7
- https://ticketsystem.dbildungscloud.de/browse/BC-7854
> BC-7854 - split Ansible Jobs by Tags

- app.js
- controllers/files.js
- controllers/homework.js
- helpers/logger.js
> BC-7804 - prevent logging of headers

- controllers/users.js
- static/scripts/teamMembers.js
- https://ticketsystem.dbildungscloud.de/browse/N21-2216
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/5286
> N21-2216 Fix outdated users for team invitations

- static/scripts/calendar.js
- views/calendar/calendar.hbs
- views/calendar/forms/form-create-event.hbs
https://ticketsystem.dbildungscloud.de/browse/BC-7936
> BC-7936 Refactor calendar test to handle multiple selectors for form fields.

- locales/de.json
- locales/en.json
- locales/es.json
- locales/uk.json
Present a hint containing a link to the user survey 2024 on the start page (dashboard).
BC-8292
https://github.com/hpi-schul-cloud/dof_app_deploy/pull/1004
- added translations
> BC-8292 - add hint and link for user survey 2024

- controllers/courses.js
- views/courses/create-course.hbs
- views/courses/edit-course.hbs
- https://ticketsystem.dbildungscloud.de/browse/N21-2151
- https://github.com/hpi-schul-cloud/nuxt-client/pull/3430
- https://github.com/hpi-schul-cloud/schulcloud-server/pull/5314
- https://github.com/hpi-schul-cloud/e2e-system-tests/pull/253
> N21-2151 Partial course sync

- views/administration/users_edit.hbs
- views/authentication/forms/login.hbs
BC-8180
- Added new data-testids
> BC-8180 Added data-testids

- static/scripts/consent.js
- views/oauth2/consent.hbs
User can have multiple pending requests at a time in the form that submits the consent for oauth operations (that affects at least bettermarks)
BC-8356
- "Akzeptieren" button (see screenshot) will be disabled after first click, no option to send two requests anymore
> BC-8356 - Bettermarks and other oauth apps not openable if user double clicks on consent button

- config/default.schema.json
there is logic that encodes the oauth state into the sseion for thr and moin schule, thus when logging in the session info gets lost for the second request from a redirect (sorry hard to explain)
https://ticketsystem.dbildungscloud.de/browse/BC-8974
> BC-8974 change session cookie same site to lax

- static/styles/authentication/home.scss
- theme/brb/views/authentication/home.hbs
https://ticketsystem.dbildungscloud.de/browse/BC-8989
Short description
In the SC BB, the former logo of the Lisum is to be replaced by the new Libra logo. 
The link should be changed to https://libra.brandenburg.de/
Steps to reproduce
Go to https://brandenburg.cloud/ --> scroll down to "Projektdurchführung" -> Logos
Current result
LISUM Logo with link to LISUM
Expected result
libra Logo with link to libra
> BC-8989 - Replacement of the LISUM-logo on the login/start page with libra-logo

- views/teams/forms/form-file-permissions.hbs
Inside the dialog "change share settings" the text "File sharing settings The following permissions will be activated for newly uploaded/created folders and files within the team:" is there 2x. The second one should be deleted.
BC-8966
> BC-8966 - Delete text in teams share settings

- static/styles/files/files.scss
- views/files/file-upload.hbs
- views/files/files.hbs
Buttons in course and team files are broken due to wrong clearance styling.
BC-9619
- clear floating of files buttons after rendering due to conditional rendering
> BC-9619 - Inactive and unsorted buttons in team-files
